---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: ebrains
spec:
  encryptedData:
    client_id: AgAO12MP+9xJKG5Ivu5KDkVGtBPVlsPROdwM2KdZaVAgyFkfTtz77cRKBFkhKMODJxXcF3Blr7HGFDO1RWoE6W+avEwQ0gpLWny0/Xww9PLJ3APP/0NcdripRi3WJb3qlSENp5Q9xhXu7RT4VMKJ0NPKyyW5l5TztUpc2C1AJsjGIBh6fGWssthm220CP5s1QNA6IuRY3Ut3zYcxRbwIBT3jne0GtMiSCjNuGqtszqJH2+bwn2xV/qvDnDVECkEJIZMpRcHBw/bAybuVaDFibpJKasy9oLyjXVabWygzDXfb/67jBQW7mIKVuu+PxhMRc79S4/r1/BEOmCMNGXIxgoSry/sVVEIpnolezhxY53sduKaoqqIc3SxbHVMdi367czvfs3/KkTXdY1lT45PP633cCHMkgW8QU4ud54YoIVhkDsdoMnK22Os/V9Ut+bjhoxL2i/tfe1pgwjcgt2DT4xmehBkVPAZYqHmybly3iwRSuIIVSKR3PRinug+ZZZu20oXWGdKh0JWdydhujfRkjJW3MI/h10P3ZYxhW6kUhBRx/YFZFZN4dKaViRHp6Hr92i0Xa09orLCKfdzVVEYBayl3MtZqFXcE7hcAlARGsUi6v131Q0l7aRmwz+Uw075QFAlkRClQYN/TZFnmstYxgbbyPnbJ8SB/tk6kvFPI+wdUuzjN+ri42CqL4+FrChqhMAWBaT4Ii8maRpWO5UXrprg=
    client_secret: AgC8Lund8bwR0AVAmYuE5hNKLhFetJCopvTAaPpr2VpbHZq+oE6sHBn672YtB4Rjb7maAr5vtbug+yVSN7VQHneC0fccvY8Q4EkHWuva9M3cVIiIvmkPKVpkyT7c9ETRbzH73BcfO7Sbvwjm4hv0Jro+RXySmavfrAPO8XDIoovewJfTJ/HvY6s1Ya/VFijsGnz9mnJZcgu0YyIkTdNMkTEfA665zR+bf1fB5prrRQuf7oCpsgis8in7KTy9hNlSXtBI01ZrURoTaLTuGzUeS6myGgMufsvXqF6e/j1HhW7ZbYZjD+T2I2hoOw4qO8cCSfGPqHIJA1p/dJGLAqZG2m7y5WSWVu1Mj0Ku6P5a6KSSkQxdGzpHGPhPbNRX0KIofaXtj0j7HwqBOZzXEQ9p/MD5O6saBIkwtqaOZHnOb91kJr+IHXbyzZ1TjyV0ANwsDTg7HT4CkDzUk8Syd24KT6wchtCF0DCh6TOjNF4/cr5DO8XDz6s0uuh3WDpc96Rtsjeo3qRlcLtKINMMucZs7XZeHCvh49masE0R6Cu0DbMypNWlQvkrA8+a0U3NCpU114wLpFCEoy/BiZDF2d2zhJFGs0ivWLO1uJ2x4kUzZIKT6CMSv0gZlnYmj1osliXQdYmGejej3wlAvNtcM+yzbGfkf4j/gJWX755MyETSIakwxiFM5Px7UK5spoa8k4VDG7SsB02eXMHJwOznkr3RrY/RIo6rSEHAnWN7Hj4zpthkMxMoSbsoJCSC+uDJec1hk8OY2Qw4OlZv8Io4TRjDvB0Q
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: ebrains
    type: Opaque
