apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "drf-tunnel.name" . }}-files
  labels:
    app: {{ template "drf-tunnel.name" . }}
    chart: {{ template "drf-tunnel.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  authorized_keys: |
    {{- range $auth_key := .Values.authorized_keys }}
    {{ $auth_key }}
    {{- end }}
  config: |
    Host *
        ServerAliveInterval {{ default 60 .Values.ssh_config_hosts_defaults.serverAliveInterval }}
        ServerAliveCountMax {{ default 5 .Values.ssh_config_hosts_defaults.serverAliveCountMax }}
        StrictHostKeyChecking {{ default "no" .Values.ssh_config_hosts_defaults.strictHostKeyChecking }}
        UserKnownHostsFile {{ default "/dev/null" .Values.ssh_config_hosts_defaults.usersKnownHostsFile }}
        ControlMaster {{ default "auto" .Values.ssh_config_hosts_defaults.controlMaster }}
        ControlPersist {{ default 0 .Values.ssh_config_hosts_defaults.controlPersist }}
    {{- range $jupyterhub := .Values.jupyterhubs }}
    {{- range $host := .ssh_config_hosts }}
    {{- if not $jupyterhub.disabled }} 
    {{- if not $host.disabled }}

    Host tunnel_{{ $host.name }}
        User {{ $host.user }}
        Port {{ default 22 $host.port }}
        HostName {{ $host.hostname }}
        IdentityFile /mnt/shared-data/keypairs/tunnel{{ $host.tunnelKeySuffix | default "" }}
        ControlPath /tmp/control_tunnel_{{ $host.name }}
    
    Host remote_{{ $host.name }}
        User {{ $host.user }}
        Port {{ default 22 $host.port }}
        HostName {{ $host.hostname }}
        IdentityFile /mnt/shared-data/keypairs/remote{{ $host.remoteKeySuffix | default "" }}
        ControlPath /tmp/control_remote_{{ $host.name }}
    
    {{- range $additional_remote_host := .additional_remote_hosts }}
    Host remote_{{ $host.name }}_{{ $additional_remote_host }}
        User {{ $host.user }}
        Port {{ default 22 $host.port }}
        HostName {{ $host.hostname }}
        IdentityFile /mnt/shared-data/keypairs/remote_{{ $additional_remote_host }}
        ControlPath /tmp/control_remote_{{ $host.name }}_{{ $additional_remote_host }}
    {{- end }}

    {{- range $additional_host := .additional_hosts }}
    Host tunnel_{{ $host.name }}_{{ $additional_host }}
        User {{ $host.user }}
        Port {{ default 22 $host.port }}
        HostName {{ $host.hostname }}
        IdentityFile /mnt/shared-data/keypairs/tunnel_{{ $additional_host }}
        ControlPath /tmp/control_tunnel_{{ $host.name }}_{{ $additional_host }}
    {{- end }}

    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
