apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "drf-tunnel.name" . }}-mw
  labels:
    app: {{ template "drf-tunnel.name" . }}
    chart: {{ template "drf-tunnel.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  run.sh: |
    #!/bin/bash
    while true;
    do
      sleep 60
      /bin/bash /mnt/volumes_mw/mount_watch/..data/compare.sh
    done
  compare.sh: |
    #!/bin/bash
    compare () {
      if [[ ! -f $1 ]]; then
        echo "$(date) $1 does not exist. Exit 1"
        exit 1
      fi
      if [[ ! -f $2 ]]; then
        echo "$(date) $2 does not exist. Create it."
        cp -rp $1 $2
      fi
      cmp -s $1 $2
      EC=$?
      if [[ ! $EC -eq 0 ]]; then
        # File has changed. It's important, that the files have the correct ownership 
        echo "$(date) $1 changed"
        filename=$(basename $1)
        cp $1 /tmp/$filename
        chown 1000:100 /tmp/$filename
        chmod 400 /tmp/$filename
        cp -rp /tmp/$filename $2 && rm /tmp/$filename
      fi
    }
    while true;
    do
      sleep 60
      echo "$(date) Compare configmaps with current files"
      compare "/mnt/volumes_certs/certs/..data/tls.crt" "/mnt/shared-data/certs/tunnel.crt"
      compare "/mnt/volumes_certs/certs/..data/tls.key" "/mnt/shared-data/certs/tunnel.key"
      compare "/mnt/volumes_files/files/..data/config" "/mnt/shared-data/files/config"
      compare "/mnt/volumes_keypairs/keypairs/..data/tunnel" "/mnt/shared-data/keypairs/tunnel"
      compare "/mnt/volumes_keypairs/keypairs/..data/remote" "/mnt/shared-data/keypairs/remote"
      compare "/mnt/volumes_keypairs/keypairs/..data/remote_juniq" "/mnt/shared-data/keypairs/remote_juniq"
      compare "/mnt/volumes_files/files/..data/authorized_keys" "/mnt/shared-data/files/authorized_keys"
    done
