apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "drf-tunnel.name" . }}-scale-down
  labels:
    app: {{ template "drf-tunnel.name" . }}
    chart: {{ template "drf-tunnel.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  suspend: true
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: {{ template "drf-tunnel.name" . }}
            cron: scale-down
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          serviceAccountName: {{ include "drf-tunnel.name" . }}-svc-acc
          initContainers:
          - name: prepare-shared-data
            image: alpine:3.14
            imagePullPolicy: Always
            command: ["/bin/sh"]
            args:
            - -c
            - >-
                mkdir -p /mnt/shared-data/certs && cp -rp /mnt/volumes_certs/certs/..data/tls.ca /mnt/shared-data/certs/ca.pem && chmod 400 /mnt/shared-data/certs/* && chown -R 1000:100 /mnt/shared-data && chmod 755 /mnt/shared-data
            volumeMounts:
              - name: shared-data
                mountPath: /mnt/shared-data
              - name: certs
                mountPath: /mnt/volumes_certs/certs
          containers:
          - name: scale-down
            image: "python:3.9-alpine3.16"
            imagePullPolicy: IfNotPresent
            env:
              - name: DEPLOYMENT_NAME
                value: {{ include "drf-tunnel.name" . }}
              - name: DEPLOYMENT_NAMESPACE
                value: {{ .Release.Namespace }}
              - name: CERTIFICATE_PATH
                value: "/mnt/shared-data/certs/ca.pem"
              - name: TUNNEL_URL
                value: "https://drf-tunnel.jupyter.svc/api/forwarder/tunnel/"
              - name: TUNNEL_USER_PASS
                valueFrom:
                  secretKeyRef:
                    name: drf-tunnel-passwds 
                    key: TUNNEL_USER_PASS
                    optional: false
            command: ["/bin/sh"]
            args:
              - -c
              - >-
                pip install kubernetes tornado && source /mnt/scaledown/run.sh
            resources:
              limits:
                cpu: 50m
                memory: 256Mi
              requests:
                cpu: 50m
                memory: 256Mi
            volumeMounts:
              - name: scaledown-cm
                mountPath: /mnt/scaledown
              - name: replicas
                mountPath: /mnt/replicas
              - name: shared-data
                mountPath: /mnt/shared-data
          nodeSelector:
            worker: "true"
          restartPolicy: Never
          volumes:
            - name: scaledown-cm
              configMap:
                defaultMode: 400
                name: {{ include "drf-tunnel.name" . }}-scale-down
            - name: replicas
              configMap:
                defaultMode: 400
                name: {{ include "drf-tunnel.name" . }}-desired-replicas
            - name: shared-data
              emptyDir: {}
            - name: certs
              secret:
                defaultMode: 400
                secretName: {{ include "drf-tunnel.name" . }}-certs
