apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ template "drf-tunnel.name" . }}-certs
  labels:
    app: {{ template "drf-tunnel.name" . }}
    chart: {{ template "drf-tunnel.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
{{ ( include "drf-tunnel.gen-certs" . ) | indent 2 }}
