apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "drf-tunnel.name" . }}-svc-acc
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "drf-tunnel.name" . }}-cluster-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "drf-tunnel.name" . }}-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: {{ include "drf-tunnel.name" . }}-svc-acc
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "drf-tunnel.name" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
