apiVersion: v1
kind: Service
metadata:
  name: hub-static-files
spec:
  ports:
  - name: hub-static
    port: 8090
    protocol: TCP
    targetPort: hub-static
  selector:
    app: jupyterhub
    component: static-files
    release: jupyterhub
  type: ClusterIP
