apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "drf-k8smgr.name" . }}-certs
  labels:
    app: {{ template "drf-k8smgr.name" . }}
    chart: {{ template "drf-k8smgr.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
{{ ( include "drf-k8smgr.selectorLabels" . ) | indent 2 }}
