apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8smgr.name" . }}
  labels:
    {{- include "k8smgr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "k8smgr.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8smgr.name" . }}-jupyterhub-forward
  labels:
    {{- include "k8smgr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "k8smgr.selectorLabels" . | nindent 4 }}
