apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "drf-k8smgr.name" . }}-svc-acc
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "drf-k8smgr.name" . }}-cluster-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "drf-k8smgr.name" . }}-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: {{ include "drf-k8smgr.name" . }}-svc-acc
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "drf-k8smgr.name" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
