{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}

{{- if .Values.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "{{ $release_name }}"
  labels:
    chart: "{{ $chart_name }}-{{ $chart_version }}"
spec:
  selector:
    matchLabels:
      {{- include "imagepuller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "imagepuller.name" . }}
        {{- include "imagepuller.selectorLabels" . | nindent 8 }}
        {{- with .Values.labels }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - image: k8s.gcr.io/pause:3.2
        imagePullPolicy: IfNotPresent
        name: pause
        livenessProbe:
          enabled: false
        readinessProbe:
          enabled: false
      dnsPolicy: ClusterFirst
      initContainers:
      {{- range $image := .Values.images }}
      - command:
        - /bin/sh
        - -c
        - echo "Pulling complete"
        image: {{ $image.image }}
        imagePullPolicy: Always
        name: {{ $image.name }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}