apiVersion: v1
kind: ConfigMap
metadata:
  name: outpost-kube-flavors-external
  namespace: outpost
data:
  flavors.yaml: |
    flavors:
      m1:
        max: -1
        weight: 10
        display_name: "2GB RAM, 1VCPU, 7 days"
        description: "JupyterLab will run for max 7 days with 2GB RAM and 1VCPU."
        runtime:
          days: 7
        resources:
          cpu_guarantee: 0.1
          cpu_limit: 1
          mem_guarantee: "512M"
          mem_limit: "2048M"
      l1:
        max: 20
        weight: 9
        display_name: "4GB RAM, 1VCPUs, 2 days"
        description: "JupyterLab will run for max 2 days with 4GB RAM and 1VCPUs."
        runtime:
          days: 2
        resources:
          cpu_guarantee: 0.1
          cpu_limit: 1
          mem_guarantee: "512M"
          mem_limit: "4096M"
      l2:
        max: 5
        weight: 4
        display_name: "8GB RAM, 2VCPUs, 10 hours"
        description: "JupyterLab will run for max 10 hours with 8GB RAM and 2VCPUs."
        runtime:
          hours: 10
        resources:
          cpu_guarantee: 0.1
          cpu_limit: 2
          mem_guarantee: "512M"
          mem_limit: "8192M"
      workshop:
        max: 10
        weight: 1
        display_name: "Summer School - 8GB RAM, 2VCPU, 10 hours"
        description: "Summer School - JupyterLab will run for max 10 hours with 8GB RAM and 2VCPU."
        runtime:
          hours: 10
        resources:
          cpu_guarantee: 0.1
          cpu_limit: 2
          mem_guarantee: "512M"
          mem_limit: "8192M"
    hubs:
      default:
        jupyterhubs: ["coec", "coeraise", "euroccgcs", "portalgauss", "dev1", "dev2"]
        weight: 10
        flavors: ["m1", "l1"]
      defaultPlusL2:
        jupyterhubs: ["jupyterjsc", "nfdigeneral"]
        weight: 11
        flavors: ["m1", "l1", "l2"]
      juniq:
        jupyterhubs: ["juniq"]
        weight: 6
        flavors: ["m1", "l1", "l2"]
    # users:
    #   nfdifzjstaff:
    #     hubs: ["nfdigeneral"]
    #     usernames_unused: []
    #     groups: ["staff@fz-juelich.de"]
    #     weight: 10
    #     flavors: ["m1", "l1", "l2"]
    #     flavorsOverride:
    #       l2:
    #         max: 10
    #     disable: True
    #   nfdidefault:
    #     hubs: ["nfdigeneral"]
    #     usernames_unused: []
    #     groups: ["default"]
    #     weight: 1
    #     flavors: ["m1"]
    #     disable: True
