apiVersion: v1
kind: ConfigMap
metadata:
  name: outpost-kube-flavors-external
  namespace: outpost
data:
  flavors.yaml: |
    flavors:
      m1:
        max: -1
        weight: 10
        display_name: "2GB RAM, 1VCPU, 5 days"
        description: "JupyterLab will run for max 5 days with 2GB RAM and 1VCPU."
        runtime:
          days: 5
        resources:
          cpu_guarantee: 0.2
          cpu_limit: 1
          mem_guarantee: "1536M"
          mem_limit: "2048M"
      l1:
        max: 10
        weight: 7
        display_name: "4GB RAM, 1VCPUs, 2 days"
        description: "JupyterLab will run for max 2 days with 4GB RAM and 1VCPUs."
        runtime:
          days: 2
        resources:
          cpu_guarantee: 0.2
          cpu_limit: 1
          mem_guarantee: "3584M"
          mem_limit: "4096M"
      l2:
        max: 5
        weight: 4
        display_name: "8GB RAM, 2VCPUs, 10 hours"
        description: "JupyterLab will run for max 10 hours with 8GB RAM and 2VCPUs."
        runtime:
          hours: 10
        resources:
          cpu_guarantee: 0.2
          cpu_limit: 2
          mem_guarantee: "7680M"
          mem_limit: "8192M"
      workshop:
        max: 25
        weight: 11
        display_name: "Course - 4GB RAM, 1VCPU, 10 hours"
        description: "Course - JupyterLab will run for max 10 hours with 4GB RAM and 1VCPU."
        runtime:
          hours: 10
        resources:
          cpu_guarantee: 0.2
          cpu_limit: 1
          mem_guarantee: "3584M"
          mem_limit: "4096M"
    hubs:
      default:
        jupyterhubs: ["coec", "coeraise", "euroccgcs", "portalgauss", "dev1", "dev2"]
        weight: 10
        flavors: ["m1", "l1"]
      defaultPlusL2:
        jupyterhubs: ["jupyterjsc"]
        weight: 5
        flavors: ["m1", "l1", "l2"]
      juniq:
        jupyterhubs: ["juniq"]
        weight: 6
        flavors: ["m1", "workshop", "l1", "l2"]
    users:
      example1:
        usernames: ["t.kreuzer_at_fz.juelich.de"]
        groups: []
        weight: 10
        disable: False
      HIFIS:
        disable: True
        groups: ["HIFIS"]
        weight: 5
        flavors:
          m1:
            max: -1
          l1:
            max: 2
          l2:
            max: 2