apiVersion: v1
kind: ConfigMap
metadata:
  name: modules-defaulthub-3-2
  namespace: outpost
data:
  load_jupyter_version.sh: |
    #!/bin/bash

    module purge
    module use $OTHERSTAGES
    module load Stages/2020 GCCcore/.10.3.0 JupyterCollection/2021.3.2
