apiVersion: v1
kind: ConfigMap
metadata:
  name: modules-defaulthub-4-1-5
  namespace: outpost
data:
  load_jupyter_version.sh: |
    #!/bin/bash

    module purge
    module use ${OTHERSTAGES}
    module load Stages/2024
    module load GCCcore/.12.3.0
    module load Jupyter-bundle/20240300
