apiVersion: v1
kind: ConfigMap
metadata:
  name: modules-user-juniq-4-2
  namespace: outpost
data:
  load_jupyter_modules.sh: |
    #!/bin/bash

    ## Kernels
    if [[ $JUPYTER_MODULE_BASH_ENABLED -eq 1 ]]; then
      module load JupyterKernel-Bash/.0.9.3-4.2.1
    fi
    if [[ $JUPYTER_MODULE_OCTAVE_ENABLED  -eq 1 ]]; then
      module load JupyterKernel-Octave/.8.4.0-4.2.1
    fi
    if [[ $JUPYTER_MODULE_PYQUANTUM_ENABLED -eq 1 ]]; then
      module load JupyterKernel-PyQuantum/.2024.5-4.2.1
    fi
    if [[ $JUPYTER_MODULE_R_ENABLED -eq 1 ]]; then
      module load JupyterKernel-R/.4.3.2-4.2.1
    fi
    ## Proxies
    if [[ $JUPYTER_MODULE_XPRAHTML5_ENABLED -eq 1 ]]; then
      module load JupyterProxy-XpraHTML5/.0.4.0-4.2.1
    fi