apiVersion: v1
kind: ConfigMap
metadata:
  name: modules-juniq-4-2
  namespace: outpost
data:
  load_jupyter_version.sh: |
    #!/bin/bash

    module purge
    module use ${OTHERSTAGES}
    module load Stages/2024
    module load GCCcore/.12.3.0
    module load Jupyter-bundle/20240520
    # module load Cartopy/0.21.0 Cirq/1.0.0 DWave/6.3.0 PyQuil/3.3.3 Qiskit/0.41.0 pulser/0.12.0 myqlm/1.7.3 Qiskit-juqcs/0.8.0
