apiVersion: v1
kind: ConfigMap
metadata:
  name: modules-user-defaulthub-4-2
  namespace: outpost
data:
  load_jupyter_modules.sh: |
    #!/bin/bash

    ## Kernels
    if [[ $JUPYTER_MODULE_BASH_ENABLED -eq 1 ]]; then
      module load JupyterKernel-Bash/.0.9.3-4.2.1
    fi
    if [[ $JUPYTER_MODULE_CLING_ENABLED -eq 1 ]]; then
      module load JupyterKernel-Cling/.20231018-4.2.1
    fi
    if [[ $JUPYTER_MODULE_JULIA_ENABLED -eq 1 ]]; then
      module load JupyterKernel-Julia/.1.9.3
    fi
    if [[ $JUPYTER_MODULE_LFORTRAN_ENABLED -eq 1 ]]; then
      module load JupyterKernel-LFortran/.0.30.0
    fi
    if [[ $JUPYTER_MODULE_OCTAVE_ENABLED  -eq 1 ]]; then
      module load JupyterKernel-Octave/.8.4.0-4.2.1
    fi
    if [[ $JUPYTER_MODULE_R_ENABLED -eq 1 ]]; then
      module load JupyterKernel-R/.4.3.2-4.2.1
    fi
    if [[ $JUPYTER_MODULE_RUBY_ENABLED -eq 1 ]]; then
      module load JupyterKernel-Ruby/.3.2.2
    fi
    if [[ $JUPYTER_MODULE_PYDEEPLEARNING_ENABLED -eq 1 ]]; then
      module load JupyterKernel-PyDeepLearning/.2024.3-4.2.1
    fi
    if [[ $JUPYTER_MODULE_PYEARTHSYSTEM_ENABLED -eq 1 ]]; then
      module load JupyterKernel-PyEarthSystem/.2024.3-4.2.1
    fi
    if [[ $JUPYTER_MODULE_PYHPC_ENABLED -eq 1 ]]; then
      module load JupyterKernel-PyHPC/.2024-4.2.1
    fi
    if [[ $JUPYTER_MODULE_PYQUANTUM_ENABLED -eq 1 ]]; then
      module load JupyterKernel-PyQuantum/.2024.5-4.2.1
    fi
    if [[ $JUPYTER_MODULE_PYVISUALIZATION_ENABLED -eq 1 ]]; then
      module load JupyterKernel-PyVisualization/.2024.3-4.2.1
    fi
    ## Proxies
    if [[ $JUPYTER_MODULE_XPRAHTML5_ENABLED -eq 1 ]]; then
      module load JupyterProxy-XpraHTML5/.0.4.0-4.2.1
    fi
    if [[ $JUPYTER_MODULE_NEST_ENABLED -eq 1 ]]; then
      module load JupyterProxy-NESTDesktop
    fi
    if [[ $JUPYTER_MODULE_RSTUDIO_ENABLED -eq 1 ]]; then
      module load JupyterProxy-RStudio/.2023.09.1-4.2.1
    fi
    ## Extensions
    if [[ $JUPYTER_MODULE_NBDEV_ENABLED -eq 1 ]]; then
      module load nbdev/2.3.25
    fi
    if [[ $JUPYTER_MODULE_VOILA_ENABLED -eq 1 ]]; then
      module load voila/0.5.7
    fi
    if [[ $JUPYTER_MODULE_NGLVIEW_ENABLED -eq 1 ]]; then
      module load nglview/.3.1.2
    fi
    if [[ $JUPYTER_MODULE_JUPYTERAI_ENABLED -eq 1 ]]; then
      module load jupyterai/.2.12.0
    fi
