---
apiVersion: v1
kind: ConfigMap
metadata:
  name: modules-4-3
  namespace: outpost
data:
  config.py: |
    c = get_config()
    c.ServerApp.root_dir = "/"
    c.ContentsManager.allow_hidden = True
    c.ServerApp.terminado_settings = {"shell_command": ["/bin/bash"]}
    c.ServerApp.default_url = "/lab/workspaces/_servername_/tree/home/jovyan"
    c.ServerApp.tornado_settings = {"websocket_max_message_size": 1024 * 1024 * 1024}
    c.ServerApp.max_buffer_size = 1024 * 1024 * 1024
    c.ServerApp.max_body_size = 1024 * 1024 * 1024
    c.ServerApp.quit_button = False
  load_jupyter_version.sh: |
    #!/bin/bash

    module purge --force
    module use ${OTHERSTAGES}
    module load Stages/2025
    module load GCCcore/.13.3.0
    module load Jupyter-bundle/20250114
    modules=()

    modules+=("pyunicore/.1.3.5")
    modules+=("jupyterlab-data-mount/1.1.0")
    modules+=("jupyterlab-hub-credit-extension/0.2.1")
    ## Kernels
    if [[ $JUPYTER_MODULE_BASH_ENABLED -eq 1 ]]; then
      modules+=("JupyterKernel-Bash/.0.9.3-4.3.4")
    fi
    if [[ $JUPYTER_MODULE_CLING_ENABLED -eq 1 ]]; then
      modules+=("JupyterKernel-Cling/.1.2-4.3.4")
    fi
    if [[ $JUPYTER_MODULE_JAVA_ENABLED -eq 1 ]]; then
      modules+=("JupyterKernel-Java/2.2.0")
    fi
    if [[ $JUPYTER_MODULE_JULIA_ENABLED -eq 1 ]]; then
      modules+=("JupyterKernel-Julia/.1.11.2")
    fi
    if [[ $JUPYTER_MODULE_LFORTRAN_ENABLED -eq 1 ]]; then
      modules+=("JupyterKernel-LFortran/.0.42.0")
    fi
    if [[ $JUPYTER_MODULE_OCTAVE_ENABLED  -eq 1 ]]; then
      modules+=("JupyterKernel-Octave/.9.3.0-4.3.4")
    fi
    if [[ $JUPYTER_MODULE_R_ENABLED -eq 1 ]]; then
      modules+=("JupyterKernel-R/.4.4.2-4.3.4")
    fi
    if [[ $JUPYTER_MODULE_RUBY_ENABLED -eq 1 ]]; then
      modules+=("JupyterKernel-Ruby/.3.4.1")
    fi
    if [[ $JUPYTER_MODULE_PYDEEPLEARNING_ENABLED -eq 1 ]]; then
      modules+=("JupyterKernel-PyDeepLearning/.2025.1-4.3.4")
    fi
    if [[ $JUPYTER_MODULE_PYEARTHSYSTEM_ENABLED -eq 1 ]]; then
      modules+=("JupyterKernel-PyEarthSystem/.2025.1-4.3.4")
    fi
    if [[ $JUPYTER_MODULE_PYHPC_ENABLED -eq 1 ]]; then
      modules+=("JupyterKernel-PyHPC/2025-4.3.4")
    fi
    if [[ $JUPYTER_MODULE_PYNEUROSCIENCE_ENABLED -eq 1 ]]; then
      modules+=("JupyterBundle-PyNeuroscience")
    fi
    if [[ $JUPYTER_MODULE_PYQUANTUM_ENABLED -eq 1 ]]; then
      modules+=("JupyterKernel-PyQuantum/.2025.6-4.3.4")
    fi
    if [[ $JUPYTER_MODULE_PYVISUALIZATION_ENABLED -eq 1 ]]; then
      modules+=("JupyterKernel-PyVisualization/.2025.2-4.3.4")
    fi
    if [[ $JUPYTER_MODULE_CUBEWEBSERVICE_ENABLED -eq 1 ]]; then
      # USERINSTALLATION=/p/usersoftware/swmanage/goebbert1/stage2025/cubewebservice
      modules+=("JupyterProxy-CubeWebservice")
    fi
    ## Proxies
    if [[ $JUPYTER_MODULE_VSCODE_ENABLED -eq 1 ]]; then
      modules+=("JupyterProxy-VSCode/0.9.3")
    fi
    if [[ $JUPYTER_MODULE_RSTUDIO_ENABLED -eq 1 ]]; then
      modules+=("JupyterProxy-RStudio/.2024.12.0")
    fi
    if [[ $JUPYTER_MODULE_XPRAHTML5_ENABLED -eq 1 ]]; then
      modules+=("JupyterProxy-XpraHTML5/.0.4.3")
    fi
    if [[ $JUPYTER_MODULE_NEST_ENABLED -eq 1 ]]; then
      modules+=("JupyterProxy-NESTDesktop/.0.4.0")
    fi
    ## Extensions
    #if [[ $JUPYTER_MODULE_COLLABORATION_ENABLED -eq 1 ]]; then
    #  modules+=("jupyter-collaboration/.3.1.0")
    #fi
    if [[ $JUPYTER_MODULE_UNICORESHELL_ENABLED -eq 1 ]]; then
      modules+=("jupyterlab-unicore-shell/0.4.3")
    fi
    if [[ $JUPYTER_MODULE_IPYVUE_ENABLED -eq 1 ]]; then
      modules+=("ipyvue/1.11.2")
    fi
    if [[ $JUPYTER_MODULE_JUPYTERAI_ENABLED -eq 1 ]]; then
      # USERINSTALLATION=/p/usersoftware/swmanage/goebbert1/stage2025/jupyter-ai
      modules+=("jupyter-ai-bundle")
    fi
    if [[ $JUPYTER_MODULE_JUPYTERVIEW_ENABLED -eq 1 ]]; then
      modules+=("jupyterview/0.7.0")
    fi
    if [[ $JUPYTER_MODULE_KERNELGATEWAY_ENABLED -eq 1 ]]; then
      modules+=("jupyter-kernel-gateway/3.0.1")
    fi
    if [[ $JUPYTER_MODULE_NBDEV_ENABLED -eq 1 ]]; then
      modules+=("nbdev/2.3.34")
    fi
    if [[ $JUPYTER_MODULE_NGLVIEW_ENABLED -eq 1 ]]; then
      modules+=("nglview/.3.1.4")
    fi
    if [[ $JUPYTER_MODULE_SPELLCHECKER_ENABLED -eq 1 ]]; then
      modules+=("jupyterlab-spellchecker/.0.8.4")
    fi
    if [[ $JUPYTER_MODULE_VOILA_ENABLED -eq 1 ]]; then
      modules+=("voila/.0.5.8")
    fi
    #if [[ $JUPYTER_MODULE_VARIABLEINSPECTOR_ENABLED -eq 1 ]]; then
    #  modules+=("jupyterlab-variableinspector/.3.2.1")
    #fi

    module load ${modules[@]}
