apiVersion: v1
kind: ConfigMap
metadata:
  name: modules-user-defaulthub-3-2
  namespace: outpost
data:
  load_jupyter_modules.sh: |
    #!/bin/bash

    echo "$(date) - No user modules for version 3.2"