apiVersion: v1
kind: ConfigMap
metadata:
  name: modules-user-juniq-3-4
  namespace: outpost
data:
  load_jupyter_modules.sh: |
    #!/bin/bash

    if [[ $JUPYTER_MODULE_BASH_ENABLED -eq 1 ]]; then
      module load JupyterKernel-Bash/.0.7.2-2022.3.4
    fi
    if [[ $JUPYTER_MODULE_OCTAVE_ENABLED  -eq 1 ]]; then
      module load JupyterKernel-Octave/.6.4.0-2022.3.4
    fi
    if [[ $JUPYTER_MODULE_PYQUANTUM_ENABLED -eq 1 ]]; then
      module load JupyterKernel-PyQuantum/.3.0-2022.3.4
    fi
    if [[ $JUPYTER_MODULE_R_ENABLED -eq 1 ]]; then
      module load JupyterKernel-R/.4.1.2-2022.3.4
    fi
    if [[ $JUPYTER_MODULE_XPRAHTML5_ENABLED -eq 1 ]]; then
      module load JupyterProxy-XpraHTML5/.0.3.5-2022.3.4
    fi