apiVersion: v1
kind: ConfigMap
metadata:
  name: modules-juniq-3-4
  namespace: outpost
data:
  load_jupyter_version.sh: |
    #!/bin/bash

    module purge
    module load Stages/2022 GCC/11.2.0 ParaStationMPI Jupyter/2022.3.4
    module load Cartopy/0.20.0 Cirq/0.14.1 DWave/4.2.0 PyQuil/3.0.1 Qiskit/0.36.2 Qiskit-juqcs/0.5.0