apiVersion: v1
kind: ConfigMap
metadata:
  name: modules-defaulthub-3-6
  namespace: outpost
data:
  load_jupyter_version.sh: |
    #!/bin/bash

    module purge
    module use ${OTHERSTAGES}
    module load Stages/2023 
    moduel load GCCcore/.11.3.0 Python JupyterLab/2023.3.6
