apiVersion: v1
kind: ConfigMap
metadata:
  name: modules-defaulthub-3-4
  namespace: outpost
data:
  load_jupyter_version.sh: |
    #!/bin/bash

    module purge
    module use ${OTHERSTAGES}
    module load Stages/2022 
    module load GCCcore/.11.2.0 Python Jupyter/2022.3.4
