apiVersion: v1
kind: ConfigMap
metadata:
  name: modules-4-2-juniq
  namespace: outpost
data:
  config.py: |
    c = get_config()
    c.ServerApp.root_dir = "/"
    c.ContentsManager.allow_hidden = True
    c.ServerApp.terminado_settings = {"shell_command": ["/bin/bash"]}
    c.ServerApp.default_url = "/lab/workspaces/_servername_/tree/home/jovyan"
    c.ServerApp.tornado_settings = {"websocket_max_message_size": 1024 * 1024 * 1024}
    c.ServerApp.max_buffer_size = 1024 * 1024 * 1024
    c.ServerApp.max_body_size = 1024 * 1024 * 1024
    c.ServerApp.quit_button = False
  load_jupyter_version.sh: |
    #!/bin/bash

    module purge
    module use ${OTHERSTAGES}
    module load Stages/2024 GCC/12.3.0 ParaStationMPI
    module load Jupyter-bundle/20240520
    module load Cartopy/0.22.0 Cirq/1.4.0 DWave/6.8.0 PyQuil/4.8.0 CUDA/12 cuQuantum-Python/23.10.0-CUDA-12 Qiskit/0.45.1 pulser/0.18.0 qoqo-quest/0.14.4a3-CUDA-12-Rust-1.70.0 myqlm/1.10.4 ParityOS/2.3.0
