# This scheduler fills one "usernode" VM before attaching pods to
# other VMs. This allows us to remove usernode VMs, when there's
# less activity on the cluster.
#
# Best used with pod.spec.resources.requests == pod.spec.resources.limits
# to avoid overcommiting nodes
apiVersion: kubescheduler.config.k8s.io/v1beta3
kind: KubeSchedulerConfiguration

profiles:
  - schedulerName: default-scheduler
  - schedulerName: usernode-scheduler
    pluginConfig:
      - name: NodeAffinity
        args:
          addedAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 50
                preference:
                  matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - usernode-1
              - weight: 49
                preference:
                  matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - usernode-2
              - weight: 48
                preference:
                  matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - usernode-3
              - weight: 47
                preference:
                  matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - usernode-4
              - weight: 46
                preference:
                  matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - usernode-5
              - weight: 45
                preference:
                  matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - usernode-6
              - weight: 44
                preference:
                  matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - usernode-7
              - weight: 43
                preference:
                  matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - usernode-8
              - weight: 42
                preference:
                  matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - usernode-9
              - weight: 41
                preference:
                  matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - usernode-10