nameOverride: ""
fullnameOverride: ""

enabled: false

jobs:
  # first cron
  - name: 7days-metric
    image:
      repository: alpine
      tag: 3.14
      imagePullPolicy: Always
    #schedule: "0 2 * * MON"
    schedule: "*/2 * * * *"
    podAnnotations:
      proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Replace
    restartPolicy: Never
    command: ["/bin/sh"]
    args:
      - -c
      - >-
          apk add bash git && /bin/bash /mnt/volumes/..data/metrics7dayhifis.sh
    resources:
      limits:
        cpu: 50m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi
    env:
    - name: GIT_REPO
      value: "gitlab.jsc.fz-juelich.de/kreuzer1/tmp.git"
      #value: "gitlab.hzdr.de/hifis/overall/kpi/FZJ-Jupyter.git"
    - name: GIT_BRANCH
      value: "main"
    - name: GIT_DIR
      value: tmp
      #value: "FZJ-Jupyter/stats"
    envFrom:
    - secretRef:
        name: cronjobs
    nodeSelector:
      worker: "true"
    volumes:
      - name: persistent
        nfs:
          path: /mnt/storage/jupyterhub
          server: "10.0.20.30"
      - name: cronjobs-cm
        configMap:
          defaultMode: 400
          name: cronjobs
    volumeMounts:
      - name: persistent
        mountPath: /mnt/persistent
      - name: cronjobs-cm
        mountPath: /mnt/volumes