# Default values for drf-tunnel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "drf-tunnel"

# Allows interactive start via VSCode to debug code
devel: False

# passed on to Django as DEBUG env variable
debug: True

# Public Keys from external sources (like hpc systems)
authorized_keys: []

ssh_config_hosts_defaults:
  serverAliveInterval: 60
  serverAliveCountMax: 5
  strictHostKeyChecking: "no"
  usersKnownHostsFile: "/dev/null"
  controlMaster: "auto"
  controlPersist: 0

ssh_config_hosts:
  - name: "demo_site"
    user: "ljupyter"
    hostname: "unicore-abc.devel.svc"
  - name: "k8smgr_hdfcloud"
    user: "k8smgr"
    port: 2222
    hostname: "drf-k8smgr.userlabs.svc"

image:
  repository: registry.jsc.fz-juelich.de/jupyterjsc/k8s/images/tunneling-relaunch
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.3-9"


secrets:
  keypairs: "drf-tunnel-keypairs"
  passwds: "drf-tunnel-passwds"
  databaseGeneral: "postgresql-general"
  databaseUsers: "postgresql-users-jupyterjsc"

imagePullSecrets: 
  - name: "gitlab-registry"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  annotations: {}
  labels: {}
  clusterIP: ""
  ## List of IP addresses at which the tunneling  service is available
  ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
  ##
  externalIPs: []

  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  servicePort: 443
  targetPort: 8443
  # nodePort: 30000
  type: ClusterIP

servicessh:
  annotations: {}
  labels: {}
  clusterIP: ""
  ## List of IP addresses at which the tunneling  service is available
  ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
  ##
  externalIPs: []

  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  servicePort: 7002
  type: "LoadBalancer"


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
