apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.size }}
  accessModes:
    - ReadWriteOnce
