# Default values for helper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "jhub-helper"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  hosts:
    - host: jupyterhub.local
      paths:
        - path: /
          pathType: Prefix
  tls: 
    - secretName: jupyterhub-local
      hosts:
        - jupyterhub.local

labels: {}
