apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cronjobs.name" . }}
  labels:
    app: {{ template "cronjobs.name" . }}
    chart: {{ template "cronjobs.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  usermetric.sh: |
    #!/bin/bash
    git config --global user.email "cronjob@fz-juelich.de"
    git config --global user.name "CronJob"
    git clone --single-branch --branch ${GIT_BRANCH} https://${METRICS_TOKEN_NAME}:${METRICS_TOKEN}@${GIT_REPO}
    if [[ ! -d ${GIT_SUBDIR} ]]; then
      mkdir -p ${GIT_SUBDIR}
    fi
    cd ${GIT_SUBDIR}
    git add .
    YESTERDAY=$(date -d "1 days ago" +'%Y-%m-%d')
    ACTIVE_USER=$(psql -t --csv --command "SELECT COUNT(id) FROM users WHERE last_activity >= '${YESTERDAY} 00:00:00.000000';"  postgresql://${SQL_USER}:${SQL_PASSWORD}@${SQL_HOST}:${SQL_PORT}/${SQL_DATABASE})
    echo "${YESTERDAY},${ACTIVE_USER}" >> user_metrics_last_1_days.csv
    git add user_metrics_last_1_days.csv

    DAYS7=$(date -d "7 days ago" +'%Y-%m-%d')
    ACTIVE_USER=$(psql -t --csv --command "SELECT COUNT(id) FROM users WHERE last_activity >= '${DAYS7} 00:00:00.000000';"  postgresql://${SQL_USER}:${SQL_PASSWORD}@${SQL_HOST}:${SQL_PORT}/${SQL_DATABASE})
    echo "${YESTERDAY},${ACTIVE_USER}" >> user_metrics_last_7_days.csv
    git add user_metrics_last_7_days.csv

    DAYS30=$(date -d "30 days ago" +'%Y-%m-%d')
    ACTIVE_USER=$(psql -t --csv --command "SELECT COUNT(id) FROM users WHERE last_activity >= '${DAYS30} 00:00:00.000000';"  postgresql://${SQL_USER}:${SQL_PASSWORD}@${SQL_HOST}:${SQL_PORT}/${SQL_DATABASE})
    echo "${YESTERDAY},${ACTIVE_USER}" >> user_metrics_last_30_days.csv
    git add user_metrics_last_30_days.csv

    git commit -m "update metrics"
    git push origin ${GIT_BRANCH}

  metrics7dayhifis.sh: |
    #!/bin/bash
    git config --global user.email "cronjob@fz-juelich.de"
    git config --global user.name "CronJob"
    git clone --single-branch --branch ${GIT_BRANCH} https://${METRICS_7DAY_HIFIS_TOKEN_NAME}:${METRICS_7DAY_HIFIS_TOKEN}@${GIT_REPO}
    cd ${GIT_SUBDIR}

    d_1=$(date -d 'today - 1 days' +%Y_%m_%d)
    d_2=$(date -d 'today - 2 days' +%Y_%m_%d)
    d_3=$(date -d 'today - 3 days' +%Y_%m_%d)
    d_4=$(date -d 'today - 4 days' +%Y_%m_%d)
    d_5=$(date -d 'today - 5 days' +%Y_%m_%d)
    d_6=$(date -d 'today - 6 days' +%Y_%m_%d)
    d_7=$(date -d 'today - 7 days' +%Y_%m_%d)

    declare -a days=("${d_7}" "${d_6}" "${d_5}" "${d_4}" "${d_3}" "${d_2}" "${d_1}")

    successful_total=$(grep -r -E "${d_1}|${d_2}|${d_3}|${d_4}|${d_5}|${d_6}|${d_7}" /mnt/persistent/metrics.log* | grep "action=successful" | wc -l)
    successful_systems=$(awk -v OFS=";" '{print $2,$1}' <(grep -r -E "${d_1}|${d_2}|${d_3}|${d_4}|${d_5}|${d_6}|${d_7}" /mnt/persistent/metrics.log* | grep "action=successful" | sed -e 's/.*system=\([^;]*\);.*/\1/' | sort | uniq -c))

    user_total=$(grep -r -E "${d_1}|${d_2}|${d_3}|${d_4}|${d_5}|${d_6}|${d_7}" /mnt/persistent/metrics.log* | sed -e 's/.*userid=\([^;]*\);.*/\1/' | sort | uniq | wc -l)
    authenticators=$(awk -v OFS=";" '{print $2,$1}' <( grep -r -E "${d_1}|${d_2}|${d_3}|${d_4}|${d_5}|${d_6}|${d_7}" /mnt/persistent/metrics.log* | grep "action=login" | sed -e 's/.*authenticator=\([^;]*\).*/\1/' | sort | uniq -c))

    used_nodes=$(grep -r -E "${d_1}|${d_2}|${d_3}|${d_4}|${d_5}|${d_6}|${d_7}" /mnt/persistent/metrics.log* | grep "action=successful" | grep "nodes=" | sed -e 's/.*nodes=\([^;]*\).*/\1/' | sort | uniq -c | awk '{s+=$1*$2} END {print s}')

    used_gpus=$(grep -r -E "${d_1}|${d_2}|${d_3}|${d_4}|${d_5}|${d_6}|${d_7}" /mnt/persistent/metrics.log* | grep "action=successful" | grep "gpus=" | sed -e 's/.*gpus=\([^;]*\).*/\1/' | sort | uniq -c | awk '{s+=$1*$2} END {print s}')

    datetime=`date --rfc-3339=seconds -d 'today - 7 days'`
    echo "$datetime,$successful_total,$user_total,$used_nodes,$used_gpus" >> usage-stats-jupyter-jsc-weekly.csv
    
    git add usage-stats-jupyter-jsc-weekly.csv
    git commit -m "update Jupyter-JSC metrics"
    git push origin ${GIT_BRANCH}
    
    find /mnt/persistent/ -type f -name "metrics.log*" -mtime +30 -delete
  hpcupdatecheck.py: |
    import psycopg2
    import os
    import sys
    import smtplib

    from email.mime.text import MIMEText
    from email.mime.multipart import MIMEMultipart
    from datetime import datetime, timedelta

    sql_host = os.environ.get("SQL_HOST")
    sql_db = os.environ.get("SQL_DATABASE")
    sql_user = os.environ.get("SQL_USER")
    sql_password = os.environ.get("SQL_PASSWORD")
    sql_port = int(os.environ.get("SQL_PORT", "5432"))

    def send_mail(hours):
      to = ["t.kreuzer@fz-juelich.de", "a.grosch@fz-juelich.de"]
      from_ = "jupyter-jsc-admin@fz-juelich.de"
      msg = MIMEMultipart()

      msg['Subject'] = 'Update HPC account cronjob may have crashed'
      msg['From'] = from_
      msg['To'] = ', '.join(to)
      body = MIMEText(f"No update for at least {hours} hours. Please check the cronjob at zam2135:/home/unicore/update_unity")
      msg.attach(body)

      # Send the email via our own SMTP server.
      s = smtplib.SMTP()
      s.connect('mail.fz-juelich.de')
      s.sendmail(from_, to, msg.as_string())
      s.quit()

    try:
      con = psycopg2.connect(user=sql_user, password=sql_password, host=sql_host, port=sql_port, database=sql_db)
      cursor = con.cursor()
      cursor.execute("SELECT last_update FROM hpc_account_updates")
      last_update = cursor.fetchone()
      cursor.close()
      con.close()
      if last_update:
        last_update = last_update[0]
      else:
        sys.exit(0)
      days = (datetime.now() - last_update).days
      if days > 3:
        send_mail(72)
      elif days > 0 and last_update.weekday not in [0, 6]:
        # we're more friendly on monday + sunday, because it's
        # usual that nothing has happened in the past 24 hours
        send_mail(24)
    except:
      import traceback
      print(traceback.format_exc())
      sys.exit(1)

