apiVersion: v1
kind: ServiceAccount
metadata:
  name: cleanup-services-jupyter-svc-acc
  namespace: jupyter
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cleanup-services-jupyter-cluster-role
  namespace: jupyter
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cleanup-services-jupyter-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: cleanup-services-jupyter-svc-acc
  namespace: jupyter
roleRef:
  kind: ClusterRole
  name: cleanup-services-jupyter-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cleanup-services-userlabs-svc-acc
  namespace: userlabs
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cleanup-services-userlabs-cluster-role
  namespace: userlabs
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cleanup-services-userlabs-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: cleanup-services-userlabs-svc-acc
  namespace: userlabs
roleRef:
  kind: ClusterRole
  name: cleanup-services-userlabs-cluster-role
  apiGroup: rbac.authorization.k8s.io
