hub:
  extraVolumes:
    - name: internal-ssl
      secret:
        defaultMode: 420
        secretName: override
    - name: shared-data
      emptyDir: {}
    - name: init-script
      configMap:
        defaultMode: 400
        name: hub-all-init-script
    - name: mount-watch
      configMap:
        defaultMode: 400
        name: hub-all-mountwatch
    - name: cleanup-sql
      configMap:
        defaultMode: 400
        name: hub-all-cleanup-sql
    - name: incident-check
      configMap:
        defaultMode: 400
        name: hub-all-incident-check
    - name: reservation-check
      configMap:
        defaultMode: 400
        name: hub-all-reservation-check
    - name: nginx-config
      configMap:
        defaultMode: 400
        name: hub-all-static-files-nginx-config
    - name: reservation-keypair
      secret:
        secretName: reservation-keypair
    - name: unity-jsc-certs
      secret:
        secretName: unity-jsc-certs
    - name: drf-tunnel-certs-public
      secret:
        secretName: drf-tunnel-certs-public
        items:
          - key: tls.ca
            path: ca.pem
    - name: drf-unicoremgr-certs-public
      secret:
        secretName: drf-unicoremgr-certs-public
        items:
          - key: tls.ca
            path: ca.pem
    - name: drf-k8smgr-certs-public
      secret:
        secretName: drf-k8smgr-certs-public
        items:
          - key: tls.ca
            path: ca.pem
    - name: tz-config
      hostPath:
        path: /usr/share/zoneinfo/Europe/Berlin