hub:
  extraEnv:
    # 4 envs already defined, index for patch starts at 4
    # patch index 4:
    - name: JUPYTERHUB_STAGE
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['stage']
    - name: JUPYTERHUB_VERSION
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['jhub_version']
    - name: JUPYTERHUB_APP
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['app']
    - name: JUPYTERHUB_HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['hostname']
    - name: LOGGER_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['logger_name']
    - name: LOGGING_CONFIG_FILE
      value: "/mnt/shared-data/git_config/logging.json"
    # patch index 10:
    - name: LOGGING_METRICS_ENABLED
      value: "true"
    - name: LOGGING_METRICS_LOGFILE
      value: "/mnt/persistent/metrics.log"
    - name: SHOW_DRF_LOGS
      value: "true"
    - name: INCIDENTS_PATH
      value: "/mnt/shared-data/incident-check"
    - name: INCIDENTS_FILE
      value: "/mnt/shared-data/incident-check/active_incidents.json"
    - name: RESERVATIONS_FILE
      value: "/mnt/shared-data/reservation-check/reservation.json"
    - name: TUNNEL_DEPLOYMENT_NAMESPACE
      value: "jupyter"
    - name: OAUTH_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: hub-custom
          key: oauth_client_id
    - name: OAUTH_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: hub-custom
          key: oauth_client_secret
    - name: DEPLOYMENT_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    # patch index 20:
    - name: K8SMGRHDFCLOUD_JUPYTERHUB_USERNAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['drf_username']
    - name: UNICOREMGR_JUPYTERHUB_USERNAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['drf_username']
    - name: TUNNEL_JUPYTERHUB_USERNAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['drf_username']
    - name: TUNNEL_JUPYTERHUB_USER_PASS
      valueFrom:
        secretKeyRef:
          name: hub-jupyterjsc-generics
          key: TUNNEL_JUPYTERHUB_USER_PASS
    - name: UNICOREMGR_JUPYTERHUB_USER_PASS
      valueFrom:
        secretKeyRef:
          name: hub-jupyterjsc-generics
          key: UNICOREMGR_JUPYTERHUB_USER_PASS
    - name: K8SMGRHDFCLOUD_JUPYTERHUB_USER_PASS
      valueFrom:
        secretKeyRef:
          name: hub-jupyterjsc-generics
          key: K8SMGRHDFCLOUD_JUPYTERHUB_USER_PASS
    - name: SQL_DATABASE
      valueFrom:
        secretKeyRef:
          name: hub-jupyterjsc-generics
          key: SQL_DATABASE
    - name: SQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: hub-jupyterjsc-generics
          key: SQL_PASSWORD
    - name: SQL_USER
      valueFrom:
        secretKeyRef:
          name: hub-jupyterjsc-generics
          key: SQL_USER
    - name: SQL_HOST
      valueFrom:
        secretKeyRef:
          name: hub-jupyterjsc-generics
          key: SQL_HOST
    # patch index 30:
    - name: SQL_PORT
      valueFrom:
        secretKeyRef:
          name: hub-jupyterjsc-generics
          key: SQL_PORT
    - name: CUSTOM_CONFIG_PATH
      value: "/mnt/shared-data/git_config/jupyterhub_custom_config.json"
