---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: juniq
spec:
  encryptedData:
    client_id: AgCDSa1fioGDaxeV7OF6eNwCkLt3K96OrET6k9T97aoAzl9fWdxhZA1roy4PkTRGJuYMkT2DxaLrK/l+Jsa7Uy1x66LOpP5yVlISVlqDSIMCDbEAZtXZ5JmWKLr6MoYRjVIoF7eZxu+Yech4tNdpXrFfwnqbY7YuRUKqmL+d4AvxBXJZ0sxnovi3Xm5JqFzHF0ruI6Cf9Vp802bDrrfms/YNljWbXvtXL4aSOGWqD+zeMtTj0kQ7yHarNVhPC9kDvwT4Xkc+ObH01oH/7JmFb4QtObgZD7EgdDUYYbbgwBjmEd7uuMqWs6UnkFm5PdpUNzBMJow+n+F+SukFm+Ap3l+9fUL5uvltjoKxbXogq1dl9z/qyi9uihqV050fPtYs4w6N8k8uwkaYBF6IMQ1X5TUnJzBZGUBOVYbPqDBgFJudTVt4BhitW996yHSNfzUJscNYNZ3Kc+Ug+DDxnzulXkFxBDWGul32+na0Ng156bh7UMmdhuWOl0jKRhYUaBuA0OGIq4tYkjZYeh3Ri1Bse4AJLGm8BV87ABuPQ9uVSeDgOoh9MfwO1Sh9OHg3FjM4E8BrG7sLpsDxg2FN5Hhkv1rhYtj/Jz6mBV4m9F/T51UqlwwPAQqQUO/qv0h5aYoqk03UVi1k28ZpLXDp8slAEORtHoSPwrBz6wTTGp+aWgs0tVOVLcBheu17cdeqG/Hek+uBi+h0ZCUNbg9cPKs3
    client_secret: AgBFXGtDED+O7prqKMGnEZKBNe1t6UkfkIJYWPsIRTj6mAE5AM8xSc7dHw042aACw4eAqDUjw0gud7T9l8FiI4nDDWWHR8f4ZZQVgjDsCe4kufvDA7mdqJ1Uobc9GXEeUlY+6ORiZlE161fRfiQMX2hbn4vNDfW1QDJVIh512I052W6API7Iu9US3HU+u/2ZSQKA1EhoksV/dpN/eRrmwT7g6ear3xHa35DoVat1i1rbb9LYbwz4OfaxIajiX3PyLDnnA5SSsI1sUfpUSVBYNnGLra9Zq7a04NGvf4nDcnSPAxJj8xgS/CiJvZsdDMne6m5AC4XJrtxR/AwE9JSpo/9qpxjTvSznZwKFkFlf3+gNJG1+mzUi34SwfXVaeyUp4psRf7B3CHT5C4BzDfhT7TatEA9K+Cjc7ORvO8cv90kMAKcBBRlYcBDZ9OlL5NZcwjHHTUW6d0mflU8D4wP2ZKh7iPO3OZW5+zmTdjC0pN+7mCC1OsYz+CCUn28ea3vLmDYl9m1TFgav0cphX1N6PBLSpaf55EOXGrBZy5DIIBhQb5NlDuSbpkV2HfV5dp45XjEUtMdCezhZU3JHWMx3fFO/LVk/N19IKgN23n9psKoaLYGqtE9SZQL5GcggH6L8Fl/cJRr8QiebwizrgR6xkK2mhAHiKNBlwwutDCv41aSzCx4c0nHcmULM50ZOSmTDrEIPDzlHSwCR9TCMrBBw/pZzgM4BNhPgiq68Qdx2M4V5pA==
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: juniq
    type: Opaque
