resources:
- monitor.yaml

# https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/1.2.0/jupyterhub/templates/ingress.yaml#L28
# No support for JupyterHub with ssl :(
patches:
- target:
    kind: Ingress
    name: juniq
    group: networking.k8s.io
    version: v1
  path: ingress-patch.json
