{{ if .Values.buildkitPruner.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: build-cache-prune
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: build-cache-prune
  template:
    metadata:
      labels:
        name: build-cache-prune
    spec:
      nodeSelector:
        binder: "true"
      volumes:
      - name: dind-socket
        hostPath:
          path: /var/run/dind/docker.sock
      tolerations:
        - key: "node.kubernetes.io/disk-pressure"
          operator: "Exists"
          effect: "NoExecute"
      containers:
      - name: pruner
        image: {{ .Values.buildkitPruner.image }}
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
        env:
          - name: DOCKER_HOST
            value: "unix:///var/run/dind/docker.sock"
        command:
          - /bin/sh
          - -c
          - |
            while true; do
              echo "[INFO] Pruning old Docker images..."
              docker image prune --force --all --filter "until={{ .Values.buildkitPruner.olderThanMinutes }}m"

              echo "[INFO] Pruning BuildKit builder cache..."
              docker builder prune --force --all --max-storage={{ .Values.buildkitPruner.buildkitCacheSize }}

              echo "[INFO] Disk usage summary:"
              docker system df

              echo "[INFO] Sleeping for 5 minutes..."
              sleep 300
            done
        volumeMounts:
        - name: dind-socket
          mountPath: /var/run/dind/docker.sock
{{- end }}
