cull:
  enabled: false
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-body-size: "2g"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippet: |
      # Managing requests to the users JupyterLab
      location ~* "^/user/([^/]+)/([^/]+)/" {
          proxy_pass                              http://jhub-maintenance.jupyterjsc.svc;
          proxy_pass                              https://juniq-retries;
          #allow                                   134.94.0.0/16;
          #deny                                    all;
          
          proxy_set_header X-Real-IP              $remote_addr;
          proxy_set_header Host                   $host;
          proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;

          # websocket headers
          proxy_set_header Upgrade                $http_upgrade;
          proxy_set_header Connection             $connection_upgrade;
          proxy_set_header X-Scheme               $scheme;

          # mitigate HTTPoxy Vulnerability
          # https://www.nginx.com/blog/mitigating-the-httpoxy-vulnerability-with-nginx/
          proxy_set_header Proxy                  "";

          # Custom headers to proxied server
          client_max_body_size                    "2g";
          proxy_connect_timeout                   "3600s";
          proxy_send_timeout                      "3600s";
          proxy_read_timeout                      "86400s";
          
          proxy_buffering                         off;
          proxy_buffer_size                       4k;
          proxy_buffers                           4 4k;
          
          proxy_max_temp_file_size                "1024m";
          
          proxy_request_buffering                 on;
          proxy_http_version                      1.1;
          
          proxy_cookie_domain                     off;
          proxy_cookie_path                       off;
          
          # In case of errors try the next upstream server before returning an error
          proxy_next_upstream                     error timeout http_502 http_503;
          proxy_next_upstream_timeout             0;
          proxy_next_upstream_tries               5;
          
          proxy_redirect                          off;
      }
      location ~* "^/((hub/static)|(2FA)|(2fa)|(2fadetails)|(jusufcloud)|(hdfaai))" {
          #proxy_pass                              http://jhub-maintenance.jupyterjsc.svc;
          proxy_pass                              http://hub-static-files.jupyterjsc.svc:8070;
          
          #allow                                   {{ $jhubInstance.allowCidr }};
          #deny                                    all;
          
          proxy_set_header X-Real-IP              $remote_addr;
          proxy_set_header Host                   $host;
          proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;

          # websocket headers
          proxy_set_header Upgrade                $http_upgrade;
          proxy_set_header Connection             $connection_upgrade;
          proxy_set_header X-Scheme               $scheme;

          # mitigate HTTPoxy Vulnerability
          # https://www.nginx.com/blog/mitigating-the-httpoxy-vulnerability-with-nginx/
          proxy_set_header Proxy                  "";

          # Custom headers to proxied server
          client_max_body_size                    "2g";
          proxy_connect_timeout                   "3600s";
          proxy_send_timeout                      "3600s";
          proxy_read_timeout                      "86400s";
          
          proxy_buffering                         off;
          proxy_buffer_size                       4k;
          proxy_buffers                           4 4k;
          
          proxy_max_temp_file_size                "1024m";
          
          proxy_request_buffering                 on;
          proxy_http_version                      1.1;
          
          proxy_cookie_domain                     off;
          proxy_cookie_path                       off;
          
          # In case of errors try the next upstream server before returning an error
          proxy_next_upstream                     error timeout;
          proxy_next_upstream_timeout             0;
          proxy_next_upstream_tries               3;
          
          proxy_redirect                          off;
      }
  
  # will be supported in 2.0.0 ...
  #ingressClassName: "nginx"
  hosts:
  - juniq-staging.fz-juelich.de
  tls:
  - hosts:
    - juniq-staging.fz-juelich.de
    secretName: juniq-certs

prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false
scheduling:
  userScheduler:
    enabled: false
nameOverride: "juniq"
fullnameOverride: "juniq"