---
stages:
  - lint

yamllint:
  image: cytopia/yamllint:latest
  stage: lint
  script:
    - >
      yamllint -d '{extends: default, rules: {line-length: disable}, ignore: "**/specific-secrets/**"}'
      .
