resources:
  - monitor.yaml


# Can be removed, once Unity was updated and has it's own two fa setup
secretGenerator:
- name: hub-jupyterjsc-twofa
  literals:
  - SEND2FA_CONFIG_PATH=/mnt/shared-data/git_config/send_mail_config.json
  - TWOFA_SSH_KEY=/mnt/shared-data/twofa/twofa
  - TWOFA_SSH_USER=unity
  - TWOFA_SSH_HOST=zam2041.zam.kfa-juelich.de
  - TWOFA_REMOVE_SSH_KEY=/mnt/shared-data/twofa/twofaremove
  - TWOFA_REMOVE_SSH_USER=unity
  - TWOFA_REMOVE_SSH_HOST=zam2041.zam.kfa-juelich.de
  options:
    disableNameSuffixHash: true
    labels:
      app: jupyterjsc

# InitContainer list in hub component:
# 0 - prepare-shared-data
# Container list in hub component:
# 0 - check-incidents
# 1 - check-reservations
# 2 - check-frontend-files
# 3 - sidecar-nginx
# 4 - hub
patches:
- target:
    kind: Deployment
    labelSelector: app=jupyterjsc,component=hub
  patch: |-
    - op: add
      path: /spec/template/spec/initContainers/0/envFrom
      value:
        - secretRef:
            name: hub-jupyterjsc-frontend-git
    - op: add
      path: /spec/template/spec/containers/3/envFrom
      value:
        - secretRef:
            name: hub-jupyterjsc-frontend-git
    - op: add
      path: /spec/template/spec/containers/4/envFrom
      value:
        - secretRef:
            name: hub-jupyterjsc-generics
        - secretRef:
            name: hub-jupyterjsc-twofa
    - op: add
      path: /spec/template/spec/volumes
      value:
        - name: internal-ssl
          secret:
            defaultMode: 420
            secretName: internal-ssl-jupyterjsc
        - name: persistent
          nfs:
            path: /mnt/storage/jupyterhub_jupyterjsc
            server: 10.0.20.30
- target:
    kind: Ingress
    name: jupyterjsc
    group: networking.k8s.io
    version: v1
  patch: |-
    - op: replace
      path: "/spec/rules/0/http/paths/0/backend/service/port/name"
      value: https
