apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jupyterjsc-servicemonitor
  namespace: jupyter
  labels:
    app: jupyterjsc
    release: jupyterhub
    component: proxy
spec:
  jobLabel: jupyterhub
  namespaceSelector:
    matchNames:
      - jupyter
  selector:
    matchLabels:
      app: jupyterjsc
  endpoints:
    - port: https # internal name of the port service exposes
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      path: /hub/metrics
      interval: 5s
      bearerTokenSecret:
        name: jupyterjsc-hub
        key: hub.services.metrics.apiToken
