---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    etcd-volume: "true"
  name: etcd-0
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: cinder.csi.openstack.org
    volumeHandle: 97ea50a9-eb4a-42b2-832f-b26de890639f
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.cinder.csi.openstack.org/zone
              operator: In
              values:
                - nova
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-cinder-sc-retain
  volumeMode: Filesystem
