- op: replace
  path: "/spec/template/spec/containers/1/env/0/valueFrom/secretKeyRef"
  value:
    name: hub-coec-generics
    key: SQL_HOST
- op: replace
  path: "/spec/template/spec/containers/1/env/1/valueFrom/secretKeyRef"
  value:
    name: hub-coec-generics
    key: SQL_PASSWORD
- op: replace
  path: "/spec/template/spec/containers/1/env/2/valueFrom/secretKeyRef"
  value:
    name: hub-coec-generics
    key: UNICOREMGR_JUPYTERHUB_USER_PASS
    optional: false
- op: replace
  path: "/spec/template/spec/containers/1/env/3/valueFrom/secretKeyRef"
  value:
    name: hub-coec-generics
    key: K8SMGRHDFCLOUD_JUPYTERHUB_USER_PASS
    optional: false
- op: replace
  path: "/spec/template/spec/containers/1/env/4/valueFrom/secretKeyRef"
  value:
    name: hub-coec-generics
    key: TUNNEL_JUPYTERHUB_USER_PASS
    optional: false
- op: add
  path: "/spec/template/spec/containers/2/env/-"
  value:
    name: TEMPLATE_GIT_REPO
    valueFrom:
      secretKeyRef:
        name: coec-share-repository
        key: REPOSITORY
- op: add
  path: "/spec/template/spec/containers/2/env/-"
  value:
    name: TEMPLATE_GIT_USERNAME
    valueFrom:
      secretKeyRef:
        name: coec-share-repository
        key: USERNAME
- op: add
  path: "/spec/template/spec/containers/2/env/-"
  value:
    name: TEMPLATE_GIT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: coec-share-repository
        key: PASSWORD