---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: coeraise
spec:
  encryptedData:
    client_id: AgAYeqPAOvJL66E6/kat0m0enK1HQzVxYjvm2bMtFMNttcsu7RXqNrZaNiO1Sdm2XGQsvbLTdikFU4rmRNa45IyY5i60uNxEZS8tiqTUiOXl6kY0m81DA13JjQr9aO9+Aw+xF7CYEbgFuXptf4NlGG8sjG1JBkycnU8vX09O1jglOAjQdqF+xRW2n4VZx9fTKEUzHm0ZQ1N2f4/XVmXUwf/GyCc0UB7+nD3tiSDLcPOT4KHaVqD/XNVkex+AJl72ifvvCqAJ8HtNmMKw0fHOORsZXK9+eiqPXeN2/IqcvjSVFo5/QbaLvOhj+BSNXJcCu+/tqmIsHsv1Dt2Z0aF/Vom3DobBlKsbU7ZFrSNS3xxr8RJY7D5n1jrP29DZ1LRhi62BvynxBwsv3wujihfN1dtMNT9qNBimDGQ1RgZLNFMlOLWvxxH1mLl9W3pUJ6mVwWXonv1wSJ2N4Cuu5aFjC3ilg1flgU5+Qzf3yFO1wYowmST8iNS54LG68ZV3w/gxx/YLVWx2yvhfdcscLt+fatfy5oBFngzgMu9a8LRCJZ1Iwy6SmTmKBDKHBsdzW+qPV0JW4SiJSuqfsDLqRZcdUcUpzYfxXqETO6XSnuVmgEp66bwdjuUZrqlPr+v/yvLqizXaluZh8JrYK3V41bmTl98w59s1/sg5XDdQt70jylyKnieXnz/KdeExwtCBPVp9OJOgftzrBqsmzyFWL1FYG20Pbk0H
    client_secret: AgAWlDFcYq5p6KhCsQ+Q5eKMgRv6Hu7AK6qPqospUWM9gI0NNhDLvgFcEtxyLSyb27iqKN5LlHllD1E92s7FybjdWCfqHjHE59FUBFgtpj8IfckJKN9Jt7I8T06yojqhOJMpJ5T8UzCAgW+U6RKBajro5biLx98CXSw5s8iitbw0o1aYqQWwpJaUmUAiYFD557/0qRseMOeCe7DYcclrDHEoJ0bc1PgcolIpFWfDmBv8/L+XHetmskQtDuruOx/7NToCIT7gjd0UtM03176hj4hdKbEVxRtGkMsYe5usA0SIhr8ajGd5FepYit9uLm3M/8OsAfZBnS2tU3dMlefwfqWY0yK7vsCblFL6ZdssoEwrFtKopH4J9BgbvS8q1oRRSpels1tbU0859gsxmZTlEU2osSCz6AL52hkLbUhmEZdmdg5K7PKp8BaRsEtWiOVrU12Ks6zrxtqVa5HOhRZvSK2TXb1E/B8UmBYLi0yRuM35SqIgVWxNyqhDXQjv4cb2YUCZR53l09qNT15nGn2mZ/yb1nqt5kXTIo05bC3D5Pb5xvu1pXgNLZ2bOArG6is/ltl9j8MeWAfdR1smLbOMdZWEic+G9g1XxOrWxaoE0W0dAaPsmCS2wVHKJGw+Fas/VvDLJBNuiPxUV8DyYduXAtlTz7rtvyYEm0jXFWOYskIBmnFKcuulKln20MpLCQfgtZCBvI0ovBHa7dZYRpPSOw0G4Uc1DXpU7Wb49P21ybRrPw==
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: coeraise
    type: Opaque
