---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: coeraise
spec:
  encryptedData:
    client_id: AgBajRTwpSylUPujH7teBC6+/y8vewBs8F4QX16Un54W+OPKapYtZYOyufnFP60gSl+TSWrgWwt9RiiKT0B69Z0y4KNkgv4dxjjLv7VE5mExbHYSO2vChzgdgP3+/HDdiwRN2JlxlT1u8m+7ogr6WxF8peHppV/3KwpFYFrLyBdMfEyWH72+8FIhps333QQ8Zq9/YfRC3MU8DB911FNb6zD74qsciz2g8Tu4kxtUtfcn6sd/HY0NCv+l43KW2Uk5r3zyxRDZzvp/BZLtL2mExCK/QuFUsuc+6APsPLE/7M7ou4Fng8IM0Kj+jiALA+NjxmF4B9apE8iQYXuskVj1sXnC0enhEU13WMEAyiERcX8z9Vw3OC1Hu9DMndC6l1c5vulyCnN4MuHWXHDMjTxdHAGaoCaBSefEHkp2IaFuy+g1Vk7yUZ2HcOQoK3qDC6vdnUKaacRQSVALQZf7uqP4bkMlXRJy9c9io+9Ax8DhOhOTbVlsi5aZLJ9mBpXVFqbD04OoqCyuyhz1LrrD137tyrkif/F6j4nwgwEHzgNEppT1BjbEKjMC0h28nb89mhwxcwdYGz704izdDcVYafjZpvE53TtVZ7MvnYwgKUcI1UyPPiUYsA0vBIuhW3s3MquVXu221QlVfF22ZLEFQeMWgvsjj3sdVA60FzzXeYO3amvrvxGqHQVSME/1GdBZmZ7FTzacRvTBNFUu0t3epNmotEfHXPrsCkEmEfPu
    client_secret: AgBzkhgi0jdXHsbNqe41wEZ+ZUdoOcSC2oB6fXccOuxIZjSMbb5rnsGS8sR7TxcQE7z5MZg4WuYQtf4Zht/fOPRBTgK4m/Mp4LawQuMpCGTagIzBCL00Mu5t25uVEHXPUXjjRE0eFbC+O9yW/OgZpFeznJK9pVNO1ADyPPUGRv4ZY3oqDJd0OEC95tilI/g27UgVvode83JPX2VtgS+8rZ2ZPSZ+Xrd9gWc7JMc8jnhxUvDoXb/07T4nPoHF5zfYfqZcKDIB1U3GXK6e8zPjrBhJyGfze7JuBa6MDUg6Gf0qFvpkTHrNGV/2KxqJqVC8HZuacwClHkkzf75Y+RMX9mXhdt+kMvcC7fkc9Lso7/Hy5+zeGD+G5GKsTaDn48X0XhATPg9PkTsQ12/A4IIZ7Kw3t6FkrWgIzTP9dSUTPauGcKeInHEhtZanzg74fYmmy0KQKfgfukS3qsgsRzvlQc4Tqptv5zEkmNBv5rcVM8SzvQ5emBQbUspDrB0fQwExdaAogid88v18apRc/p3ePLZY83ljJxDIOmQR/sZSn0QP4Wvc4saO0rf4ADvpiM14iuYMcQHNEDct6AD50Q+MacNsIXXy9nE7YDobIsqf6AxMwhxdUqSI0e3w4/qd6QxOja7S0i4fOgtlS74CBEGRaJrvkJe4vtJrUsqaBIW1cSHKv1E273qvxffZQ5dF3eOheLhQnH7khIx4IlFiKFJ34iMHikB2zYDrNpQQf8jaURoLLw==
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: coeraise
    type: Opaque
