---
# InitContainer list in hub component:
# 0 - prepare-shared-data
# Container list in hub component:
# 0 - hub
# 1 - check-frontend-files
# 2 - sidecar-nginx
patches:
  - target:
      kind: Deployment
      labelSelector: component=hub
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - secretRef:
              name: generics
  - target:
      kind: Service
      labelSelector: component=hub
    patch: |-
      - op: replace
        path: /spec/selector/component
        value: maintenance
patchesStrategicMerge:
  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: proxy
    $patch: delete
  - |
    apiVersion: v1
    kind: Service
    metadata:
      name: proxy-public
    $patch: delete
  - |-
    apiVersion: v1
    kind: Service
    metadata:
      name: proxy-api
    $patch: delete
