{
 "title": "Cluster Information",
 "tags": [
  "jupyterhub",
  "kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Node Stats", "type": "row" },
  {
   "title": "Node CPU Utilization %",
   "type": "graph",
   "description": "% of available CPUs currently in use\n",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) \n  * on(pod) group_left(node) kube_pod_info{node!~\".+airflow.*\"}\n) by (node)\n/\nsum(kube_node_status_capacity{resource=\"cpu\", node!~\".+airflow.*\"}) by (node)\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Node Memory Utilization %",
   "type": "graph",
   "description": "% of available Memory currently in use\n",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (\n  sum (\n    (\n      # Memory that can be allocated to processes when they need\n      node_memory_MemFree_bytes + # Unused bytes\n      node_memory_Cached_bytes + # Shared memory + temporary disk cache\n      node_memory_Buffers_bytes # Very temporary buffer memory cache for disk i/o\n    )\n    * on(pod) group_left(node) kube_pod_info{node!~\".+airflow.*\"}\n  ) by (node)\n  /\n  sum (\n    node_memory_MemTotal_bytes\n    * on(pod) group_left(node) kube_pod_info{node!~\".+airflow.*\"}\n  ) by (node)\n)\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node CPU Commit %",
   "type": "graph",
   "description": "% of each node guaranteed to pods on it\n",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  # Get individual container CPU limits\n  kube_pod_container_resource_requests{resource=\"cpu\"}\n  # Ignore containers from pods that aren't currently running or scheduled\n  # FIXME: This isn't the best metric here, evaluate what is.\n  and on (pod) kube_pod_status_scheduled{condition='true'}\n  # Ignore user and node placeholder pods\n  and on (pod) kube_pod_labels{label_component!~'user-placeholder|node-placeholder'}\n) by (node)\n/\nsum(\n  # Get individual container CPU requests\n  kube_node_status_allocatable{resource=\"cpu\", node!~\".+airflow.*\"}\n) by (node)\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Memory Commit %",
   "type": "graph",
   "description": "% of each node guaranteed to pods on it\n",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  # Get individual container memory limits\n  kube_pod_container_resource_requests{resource=\"memory\"}\n  # Ignore containers from pods that aren't currently running or scheduled\n  # FIXME: This isn't the best metric here, evaluate what is.\n  and on (pod) kube_pod_status_scheduled{condition='true'}\n  # Ignore user and node placeholder pods\n  and on (pod) kube_pod_labels{label_component!~'user-placeholder|node-placeholder'}\n) by (node)\n/\nsum(\n  # Get individual container memory requests\n  kube_node_status_allocatable{resource=\"memory\", node!~\".+airflow.*\"}\n) by (node)\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Out of Memory kill count",
   "type": "graph",
   "description": "Number of Out of Memory (OOM) kills in a given node.\n\nWhen users use up more memory than they are allowed, the notebook kernel they\nwere running usually gets killed and restarted. This graph shows the number of times\nthat happens on any given node, and helps validate that a notebook kernel restart was\ninfact caused by an OOM\n",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "# We use [2m] here, as node_exporter usually scrapes things at 1min intervals\n# And oom kills are distinct events, so we want to see 'how many have just happened',\n# rather than average over time.\nincrease(node_vmstat_oom_kill{namespace=~\"jupyter|userlabs\"}[2m])\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  { "title": "Cluster Stats", "type": "row" },
  {
   "title": "Memory commitment %",
   "type": "graph",
   "description": "% of total memory in the cluster currently requested by to non-placeholder pods.\n\nIf autoscaling is efficient, this should be a fairly constant, high number (>70%).\n",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  # Get individual container memory requests\n  kube_pod_container_resource_requests{resource=\"memory\"}\n  # Add node pool name as label\n  * on(node) group_left(label_nodepool)\n  # group aggregator ensures that node names are unique per\n  # pool.\n  group(\n    kube_node_labels{label_nodepool!~\".*airflow.*\"}\n  ) by (node, label_nodepool)\n  # Ignore containers from pods that aren't currently running or scheduled\n  # FIXME: This isn't the best metric here, evaluate what is.\n  and on (pod) kube_pod_status_scheduled{condition='true'}\n  # Ignore user and node placeholder pods\n  and on (pod) kube_pod_labels{label_component!~'user-placeholder|node-placeholder'}\n) by (label_nodepool)\n/\nsum(\n  # Total allocatable memory on a node\n  kube_node_status_allocatable{resource=\"memory\"}\n  # Add nodepool name as label\n  * on(node) group_left(label_nodepool)\n  # group aggregator ensures that node names are unique per\n  # pool.\n  group(\n    kube_node_labels{label_nodepool!~\".*airflow.*\"}\n  ) by (node, label_nodepool)\n) by (label_nodepool)\n",
     "legendFormat": "{{label_nodepool}}"
    }
   ]
  },
  {
   "title": "CPU commitment %",
   "type": "graph",
   "description": "% of total CPU in the cluster currently requested by to non-placeholder pods.\n\nJupyterHub users mostly are capped by memory, so this is not super useful.\n",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  # Get individual container memory requests\n  kube_pod_container_resource_requests{resource=\"cpu\"}\n  # Add node pool name as label\n  * on(node) group_left(label_nodepool)\n  # group aggregator ensures that node names are unique per\n  # pool.\n  group(\n    kube_node_labels{label_nodepool!~\".*airflow.*\"}\n  ) by (node, label_nodepool)\n  # Ignore containers from pods that aren't currently running or scheduled\n  # FIXME: This isn't the best metric here, evaluate what is.\n  and on (pod) kube_pod_status_scheduled{condition='true'}\n  # Ignore user and node placeholder pods\n  and on (pod) kube_pod_labels{label_component!~'user-placeholder|node-placeholder'}\n) by (label_nodepool)\n/\nsum(\n  # Total allocatable CPU on a node\n  kube_node_status_allocatable{resource=\"cpu\"}\n  # Add nodepool name as label\n  * on(node) group_left(label_nodepool)\n  # group aggregator ensures that node names are unique per\n  # pool.\n  group(\n    kube_node_labels{label_nodepool!~\".*airflow.*\"}\n  ) by (node, label_nodepool)\n) by (label_nodepool)\n",
     "legendFormat": "{{label_nodepool}}"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "graph",
   "description": "Number of nodes for each node pool\n",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_labels{label_nodepool!~\".*airflow.*\"}) by (label_nodepool)",
     "legendFormat": "{{label_nodepool}}"
    }
   ]
  },
  {
   "title": "Non Running Pods",
   "type": "graph",
   "description": "Pods in states other than 'Running'.\n\nIn a functional clusters, pods should not be in non-Running states for long.\n",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase!=\"Running\", namespace=~\"jupyter|userlabs\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  }
 ]
}