apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "drf-tunnel.name" . }}
  labels:
    {{- include "drf-tunnel.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "drf-tunnel.name" . }}
      {{- include "drf-tunnel.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "drf-tunnel.name" . }}
        {{- include "drf-tunnel.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "drf-tunnel.name" . }}-svc-acc
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: prepare-shared-data
          image: alpine:3.14
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
          - -c
          - >-
              mkdir -p /mnt/shared-data/certs && mkdir -p /mnt/shared-data/files && mkdir -p /mnt/shared-data/keypairs && cp -rp /mnt/volumes_certs/certs/..data/tls.key /mnt/shared-data/certs/tunnel.key && cp -rp /mnt/volumes_certs/certs/..data/tls.crt /mnt/shared-data/certs/tunnel.crt && cp -rp /mnt/volumes_files/files/..data/* /mnt/shared-data/files/. && cp -rp /mnt/volumes_keypairs/keypairs/..data/* /mnt/shared-data/keypairs/. && chmod 400 /mnt/shared-data/certs/* && chmod 400 /mnt/shared-data/files/* && chmod 400 /mnt/shared-data/keypairs/* && chown -R 1000:100 /mnt/shared-data/certs && chown -R 1000:100 /mnt/shared-data/files && chown -R 1000:100 /mnt/shared-data/keypairs
          volumeMounts:
            - name: certs
              mountPath: /mnt/volumes_certs/certs
            - name: files
              mountPath: /mnt/volumes_files/files
            - name: keypairs
              mountPath: /mnt/volumes_keypairs/keypairs
            - name: shared-data
              mountPath: /mnt/shared-data
            {{- if .Values.cluster_internal_publickeys }}
            {{- range $secretname := .Values.cluster_internal_publickeys }}
            - name: {{ $secretname }}
              mountPath: /mnt/volumes_{{ $secretname }}/{{ $secretname }}
            {{- end }}
            {{- end }}
      containers:
        - name: main
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.devel }}
          image: "{{ .Values.image.repository }}:devel"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: "{{ .Values.secrets.passwds }}"
            - secretRef:
                name: "{{ .Values.secrets.databaseGeneral }}"
          env:
            {{- if .Values.debug }}
            - name: DEBUG
              value: "true"
            {{- end }}
            - name: AUTHORIZED_KEYS_PATH
              value: "/mnt/shared-data/files"
            - name: SSHCONFIGFILE
              value: "/mnt/shared-data/files/config"
            - name: GUNICORN_SSL_CRT
              value: "/mnt/shared-data/certs/tunnel.crt"
            - name: GUNICORN_SSL_KEY
              value: "/mnt/shared-data/certs/tunnel.key"
            - name: GUNICORN_PROCESSES
              value: "4"
            - name: GUNICORN_THREADS
              value: "1"
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secrets.databaseUsers }}"
                  key: TUNNEL_USER
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secrets.databaseUsers }}"
                  key: TUNNEL_PASSWORD
            - name: SQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secrets.databaseUsers }}"
                  key: TUNNEL_DATABASE
            - name: DEPLOYMENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: DEPLOYMENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
            - name: ssh
              containerPort: 2222
              protocol: TCP
          #livenessProbe:
          #  failureThreshold: 3
          #  httpGet:
          #    path: /api/health
          #    port: https
          #    scheme: HTTPS
          #  periodSeconds: 10
          #  successThreshold: 1
          #  timeoutSeconds: 10
          #readinessProbe:
          #  failureThreshold: 3
          #  httpGet:
          #    path: /api/health/
          #    port: https
          #    scheme: HTTPS
          #  periodSeconds: 10
          #  successThreshold: 1
          #  timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: shared-data
              mountPath: /mnt/shared-data
        - name: remote-check
          image: alpine:3.14
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
          - -c
          - >-
              apk add curl &&
              export REMOTECHECK_TOKEN=$(echo -n "remotecheck:${REMOTECHECK_USER_PASS}" | base64 -w 0) ; while true; do sleep 60; curl -s -X "GET" -H "Authorization: Basic ${REMOTECHECK_TOKEN}" -H "uuidcode: tunnel-side-remote-check-cronjob" --cacert /mnt/shared-data/certs/tunnel.crt https://${DEPLOYMENT_NAME}.${DEPLOYMENT_NAMESPACE}.svc/api/remotecheck/ ; done
          env:
            - name: REMOTECHECK_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secrets.passwds }}"
                  key: REMOTECHECK_USER_PASS
            - name: DEPLOYMENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: DEPLOYMENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: shared-data
              mountPath: /mnt/shared-data
        - name: mount-watch
          image: alpine:3.14
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
          - -c
          - >-
              apk add bash && /bin/bash /mnt/volumes_mw/mount_watch/..data/run.sh
          volumeMounts:
            - name: mount-watch
              mountPath: /mnt/volumes_mw/mount_watch
            - name: certs
              mountPath: /mnt/volumes_certs/certs
            - name: files
              mountPath: /mnt/volumes_files/files
            - name: keypairs
              mountPath: /mnt/volumes_keypairs/keypairs
            - name: shared-data
              mountPath: /mnt/shared-data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: mount-watch
        configMap:
          defaultMode: 400
          name: {{ include "drf-tunnel.name" . }}-mw
      - name: files
        configMap:
          defaultMode: 400
          name: {{ include "drf-tunnel.name" . }}-files
      - name: certs
        secret:
          defaultMode: 400
          secretName: {{ include "drf-tunnel.name" . }}-certs
      - name: keypairs
        secret:
          defaultMode: 400
          secretName: "{{ .Values.secrets.keypairs }}"
      {{- if .Values.cluster_internal_publickeys }}
      {{- range $secretname := .Values.cluster_internal_publickeys }}
      - name: {{ $secretname }}
        secret:
          defaultMode: 400
          secretName: "{{ $secretname }}"
      {{- end }}
      {{- end }}
