---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: euroccgcs
spec:
  encryptedData:
    client_id: AgBXyX3N15MFUU906TLUUhKyZUod51jhxTJt+09sDihqgaWSoKeiPac2TpP8s8GysuQ41EL6+V4aw1d9PvCcuXsqidDR5oL6Wukim/wKzKKtkX8anQwXZCaxO4uSXYhr3aXOD02UOK21pBvd/GQNggaAE758nbI/qzSg07roboWlm/oESkn5EKdkYQ0mbSMWdYFjTBHriXfMctjRN/DwiJbAOn4riZoH0HiKvKZaAz1CJix5DWI00Q1RRmNlaL3B3qwlTwEZh1PrDFXS7fw5ZW+df5aK4v5q0eVE/n3q6lNlYH1RFfEkujf7c0n6mgAv61JJtaSa0zQKdyMDyKMcGoJzjT/DeBvtmvBbjWDl/IyVUi7bMawhE2oI/Mw9zfY+smvZnsfTKQGsqHY4b3w1Upi3pZmzTkv3WPO8NGuNz0i+lSpdSxlLBRqrH1XP+TUDyf2Zr+LDOyJe82WUJeCHcuiczS18Z3Gu1WGbxRflVyLIHT0MuswGhpTVvCd34drEiYI6BSI/a6OK7pVJy4p3AHOC6mU1CN4iyJ/r16f4LjdyF4xr8qZrF6ZAOjSUC0P4Djyt1+td8/v0c/Mb0Iy99M9rSNBR86EnOkw/iiUm0yqV4/UhURJBub0SwLWfPxzoYpAp+2hU+2DfDtx+uv2vrMwItTEdMalW7HUUpITYt3NsiR5UMuTuWUE5mDLvmo7BPIWiSvGPu3bnoEreXQSBr/Okfg==
    client_secret: AgBnPn/VEUVSD01x65rgGWlNLlBVbWIgl/eaz/ZpvZ+S/M0NXfKhrTFbZJ0I4QWq3xytFQL2UWI4tEH1c/R0kneQmqjnee6O2lZNwP6s3hB2bz8ZG0gGkF9bQJXVfbpKx+EMU2wNh4wFHfH3J4CbBo9SScWp6nlG9DdDBouMxMSqXpnCQ1xRO8Bkd53elriNEne7tLW6dAhaQwddBCZXY4rn0Cf/iqlZxmoIgfuh/F9j9DByK3cF43RoXSTDWY8xIqt2KTafZuDkoSyy57p9KC65+AEV/xQ30Ug8Z01fwY0zLjc0hx1GqMtlHQ+bbw7aArsT9+zd2h/LS3CD2c3UF5CFLfv2C45pXnZm2SGzabYqbh0AdcE5BSCnYkhcd6yXAVYZDBCB/hgEIhV8Nn118E2xXpuEc2jOpx45tbR9b+DuB8Z3iGs/ym89GMVhZl9ZUtwVKAaVR44ZGtGju3JglIuZMoCAaTne7O6SNceErlnr4ao9guPrHAVfHbANtq+C0jfcG54RGqgQCBUQH17hSNh8qXGkRo1aC5rgkXbp5S/4InrSL0Jk5F50X2sY0PsFKiDEs4R65zidMVFmxMysNdEgL0DeYO2qr5eas6CszorS5bzv5wOvcqVRzh3lMpC7VAKaZYkaEj3h4ShNR9rPG5biboaGcXKX5ArF9DOiN3tbL/NLtouflirBcRpZUTHw3VNxZq4VK0d6708ObNt0PmTSzV5krZxEpRSRN7cGgoPqSg==
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: euroccgcs
    type: Opaque
