---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-registry
  namespace: jupyter
spec:
  encryptedData:
    .dockerconfigjson: AgBlwrTaGFym2p6Tn5MJLMdNgHyiFJZWVSC4+70ZgKELa1/N//3Nz57gp+tQ0UPW1a4gt/YksKoOflwdLLr4Zbcw0llnG45gBBpCajbqXu/47mkc78txxqrxH5KOqpOZsmxa/NiBkzTgSfIYZSB4Om9SnguKjDPwIjYa6Rfil13hjGCdqjyo9J/8phGWll7vDkNETVYuZvwroaVJ0zfYtH/W3izFT/XuSTRAM1/YP9x6fDbu186cC4ey1pxLDMaOoxkj8wC8kCxniZl49VJD87vGDLdFrPJJcHqEYaHXz4/2utzqC8IsmWYHn8q9gh8zX5CIabjU1iFbNUdZpHlufk4C5n4bAicRwiu1ZDD9fcb0GOPuw1brPIAFFvHOpzqznzAXX8U2P2mCXhWtS2g66OCXNW0ka4Y0jpEbmO8/FGZ4jgec+9bnJzJ7vMd8olkUh8gagbsJE67feGQO+gq1Tp5tdowwLaJ13bL0+l8db+n3qMpQ7G5hAWhezbTyQjOzYGEa1hH5+A4EU+JfFJ96nUsSPSDG5i4q3E9TrzgBlW6YCJGSAuoLHkHVqrl1kph51XInLj8mYhnl4ZC0IlbjD+a+jrHmMAvRlYIRceXXIrouj65r3Hq8zKYPB+pX3x9z66uTYg2yTnMzwMwBflicrasa08E8/Fgu3QCrbfS7JhTzfoQv6z7utQ3eEiu/xmGlXAqzHqWjOSu9N8NM9hlTcMWOWWpxsz7rChbisGkg8/Q1ZmN/vdPSZX9dNHGhNoWTyT9fRWt/J+qEOqFLiXEJDBtQ4GVOl1PQLG5k6NzrhtEvm90XkNl6nvIgtq4zE83VqVtSRgJF
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-registry
      namespace: jupyter
    type: kubernetes.io/dockerconfigjson
