---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nbviewer-secret
  namespace: jupyter
spec:
  encryptedData:
    GITHUB_API_TOKEN: AgBBzS+tHrr+S+fY3MFCWxKB1ai3ZanzSEjEYG2ZsbV0Q1cYCbLKv1wtkpQUYk28VKoqAP/upLm+TLWf5+d/V2/FcKBPlMj24nUNxQDNhdbjuXHD+jHkZIbncoRQAOFMK4VCFmChFYKjLC7G4vwE939HdIa/eq7YfMav/9FR+5Qq3ESVo4n2ib7SbEJ5x6J1twk5DqH4X615LisxJ/tCX2VwjsW8c5wST8+1PPz3XGuCkKg/dcZe3FupLd1t2D7VIp9HGsAPRoF2LTCNO6R+utjyd+KM/jrrfEOyAa+282Xh0TTpOi0ocleTHKEDbHN+FIPuc4aixHjQ/GWDs569lX+IK1iexmkNpzCxJzPbF1yeSfYgsM5nclQCMScYgeNloKZDOdaoeSmIlSiK9cPt7LTDs934LJEud13RTa9yAsBPmE2I8AuYVDDqPV10ORKC8eVDPI9I/Ym7v2EkE9h6c9n8o0rWuAVaB7g9A55dq8/UE6K6cCQcPnVoyWUryWKOAjBlaaNiV//tq54hvCJgOSw6BMjO0IFF8VuktEZ6Pi7Zu5M44K20fjnO/csSqCnB4y171j4Le9CBBcVhBKoMZbiucdsOZ4f4vfhtdl0LbEaQ0ebIWRGKHTfBeRsgHVS613Xmvzs0c5U4whFfyUsjRUc1DYMtBUqwk/p4NpHzfprPlsWzmy2ywvrgLqm+0mSKP40iLcIofpmbggpUAeoqWdaXrpR4b8RK43FryrwaWJXVMahY9I7rppKT
  template:
    metadata:
      creationTimestamp: null
      name: nbviewer-secret
      namespace: jupyter
    type: Opaque
