hub:
  services:
    metrics:
      name: metrics-prometheus-monitor
    tunnellist:
      name: tunnel_list_servers
    tunnelrestart:
      name: tunnel_restart_nodes
    hpcupdate:
      name: hpcinfos_update
    outpostflavors:
      name: outpost_flavors
  loadRoles:
    tunnel_list:
      name: "tunnel_list_servers-role"
      description: "List running servers"
      scopes:
        - "custom:servers:list"
      services:
        - "tunnel_list_servers"
    restart_forward:
      name: "restart_forward-role"
      description: "Restart port forward processes, when a proxy node was restarted."
      scopes:
        - "custom:sshnode:restart"
      services:
        - "tunnel_restart_nodes"
    hpcinfos_update:
      name: "hpcinfos_update-role"
      description: "Update hpc infos for each user"
      scopes:
        - "custom:hpcinfos:update"
      services:
        - "hpcinfos_update"
    outpost_flavors:
      name: "outpost_flavors-role"
      description: "Update usage of flavors in outpost"
      scopes:
        - "custom:outpostflavors:set"
      services:
        - "outpost_flavors"
    read_metrics:
      name: read-metrics
      description: Access to metrics information
      scopes:
        - read:metrics
      services:
        - metrics-prometheus-monitor
  networkPolicy:
    allowedIngressPorts:
      - 8070