---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: buildpodsregistrycredentials
  namespace: binder
spec:
  encryptedData:
    values.yaml: AgB7wf12hUz0CBv0AZEPh1SWnsu5pN6KdD9Zb9Yeebaops52HymRaGUyqSzLdP0XcS51t5SEniYLuAf7hGQSkprvUPAPIVpdwtv7aPWemf0csr0dRz3bWIwR8PRbF2/IR1zB4EH/3c8d+f9ft3JHT7AqY767sjKh/Y4hatux9t92M1orkQJXM4T5ZCQONSrDGBZt0h/AfSJ0Vzh90ChXgUaKuIeXfdF1QTVQhvZkBuxOtN9o6PNoJxU7K0OOE6JF2ff/aJ9eKj+cGsAGyTCewhsYV43iKzbG9Sw+qCPaSxu6yXEkJYjZ2UCjsi3+DtHZuz540bVziLsW1u26fDlE0bKET3kEZlBe7FULPl8XFVU9xCteSeDY2T3Tm6p/HGI6hTM49Lf7GzNZnU0HKDVZKNQUbIl5XYAAJ1TsQQjphag3gYxQUiu16K2di/DL8EaZWt/HP8wx9JffI3KFjvqhSBSmLHfYMVjZCAbRFmZKdk8K+8Y0hpef1Eb7pHjIZdyhBi10qpy9iTEPIoBNt1HRh+19E1QT0kl8y1EOXBidXn+9d3mWfQXRz4jcRDBUGDVyDgsXgT+aGKjK7+UfAm+GIveEXGWlhWLciGCBsseyIhS1dCIXzeRB4OsdHX65P+c+FUnD78IA9jAkjHSJ3BMaPBX8CFHE8W4/ejCXsJzt/rWG1b/hUHECyyOxwOAoeiwQxLjviBv1vSwya1N3gLuY3rRojtFGNX/rIwNkXj+o+DhXxeotCJv+5ohH9WdmnugK4/6XkkNzNN8ISaWEXTjlmzBQK9bymwQOj0jM7mxH65Y1e0MsIgBk04yQ7X8h7OgnOKo+LolrlENGna9Z0QGPISMMO1e4OGjlbkmKew==
  template:
    metadata:
      creationTimestamp: null
      name: buildpodsregistrycredentials
      namespace: binder
    type: Opaque
