# InitContainer list in hub component:
# 0 - prepare-shared-data
# Container list in hub component:
# 0 - check-incidents
# 1 - check-reservations
# 2 - check-frontend-files
# 3 - sidecar-nginx
# 4 - hub
patches:
- target:
    kind: Deployment
    labelSelector: app=jupyterjsc,component=hub
  path: patch_deployment.yaml
- target:
    kind: Ingress
    name: jupyterjsc
    group: networking.k8s.io
    version: v1
  path: patch_ingress.yaml

# # Can be removed, once Unity was updated and has it's own two fa setup
# secretGenerator:
# - name: jupyterjsc-twofa
#   literals:
#   - SEND2FA_CONFIG_PATH=/mnt/shared-data/git_config/send_mail_config.json
#   - TWOFA_SSH_KEY=/mnt/shared-data/twofa/twofa
#   - TWOFA_SSH_USER=unity
#   - TWOFA_SSH_HOST=zam2041.zam.kfa-juelich.de
#   - TWOFA_REMOVE_SSH_KEY=/mnt/shared-data/twofa/twofaremove
#   - TWOFA_REMOVE_SSH_USER=unity
#   - TWOFA_REMOVE_SSH_HOST=zam2041.zam.kfa-juelich.de
#   options:
#     disableNameSuffixHash: true
#     labels:
#       app: jupyterjsc
