# InitContainer list in hub component:
# 0 - prepare-shared-data
# Container list in hub component:
# 0 - check-incidents
# 1 - check-reservations
# 2 - check-frontend-files
# 3 - sidecar-nginx
# 4 - hub
patches:
- target:
    kind: Deployment
    labelSelector: app=jupyterjsc,component=hub
  path: patch_deployment.yaml
- target:
    kind: Ingress
    name: jupyterjsc
    group: networking.k8s.io
    version: v1
  path: patch_ingress.yaml
