---
# InitContainer list in hub component:
# 0 - prepare-shared-data
# Container list in hub component:
### IF custom.ingress.useSidecar enabled , otherwise sidecar-nginx does not exist
# 0 - check-frontend-files
# 1 - sidecar-nginx
# 2 - hub
patches:
  - target:
      kind: Deployment
      labelSelector: component=hub
    patch: |-
      - op: add
        path: /spec/template/spec/containers/1/envFrom
        value:
          - secretRef:
              name: generics
  - target:
      kind: Ingress
      group: networking.k8s.io
      version: v1
      labelSelector: app=jupyterhub
    patch: |-
      - op: replace
        path: "/spec/rules/0/http/paths/0/backend/service/port/name"
        value: https
