---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: ebrains
spec:
  encryptedData:
    client_id: AgBLCcrIlCUisI+nHIienuzTLBJo6SLlL/FExRltAkgD6f16Or79rgq00Aqku9dQQEQbtbLPbvtnHf03ABJJyJIB3xkVlyoGjGxP7TgRby/0AZtzKuW5T4JGAj1F0F8xBD9aPfHqKpGVB/YJ/VHoNuCWVAgZSoS3eI4CWJiVto2wcqlXPIuto9fvN4/dL2JhQhQEf3dFnIIotbdXcQr/5+0wfn71NfyBWu6iBB9bNj0UOWZ82W9F4QdxFiqQ4FzKDamAmVQDWqPe+MMqCrWWjp7p4isgZiqBg2ZqZlZM2fs4bUPXsDnIEsx5Gn+9WRAWZAo6eAjfYqBszkVcsbDPCL5SUApUlPlq32tWKVKQViSrveKHbBI1lh3czXuE0v42d9sARAspGGL5K/jYvFT/VPB+k7/wx+yX8LrfOUMcWTHKwd0bVT6arJ/SXrwcP/BxmUML8Pxj2h9beVHimi3kSIAEX4lrPaweZzKyfQRzyTirc9qbxDRd1EHIy+H05Hn100YH44tquBfhL5DPMvHSLfpNv94F9xbMuujJIRNs3nH/N9PByPTYuL3x3lq3b6x0RkYTXs0rYFVk5HDTPEStEyqAYDzDzeIkRjwTPgaBAvCp1d+wytPYKQV4zpHV9OVoITe4XoDnNLrk7VMnoHpbx9eejUdOVJtSssq+SvpksVhiSpx4PP1XYnXv6VYtmmgD27yLdS0l7udiYg1s4pBmY6nxSBI=
    client_secret: AgB9fEa3IafaiT3zh315RPDmo/wm0asCL8eoWpFdfoDM2eGFAJxnhVNrsQUqC1QaybUGXAUsAZR5kNuh5mEH+v7ELEpBUg8WMSEL+FVR76HCfeImq5BjCDNuDey2QGOHkIb0Wei5Znc91KEDGJIWqiJTE7OqDG5abvMKkA+I25mPT1u9+h624+om7f7nBnDFTer4GAbL1xUwzHcsSZQqNxHdjFHf/TQtuQ/5rA7a7awCph8ImtO2H0NZS4/1e6m5C8w5OFAMZmE5BzkBsNkxBofcKdWTAGXI5HaJaeZNVqmkON3D6F4fRFTBcflBJOFcXIZxICPJRfWigkidZCi6xkHr81lZdAURDoOMPEu5eUoGeRVexNMCFLvDsPGLt3PKOJns3hIMCzk+x5Fq7SqaGp7ZELi05XgJ63ZvdeHA9j89k4RoSpGnKukWsBQ4U0qagBgoYjBP7exurMLjbGUjmzjqUveanZk0RU9znlOKHTzlZ7USUg9RBhzqomSQi4D5Q5tXU9EXfFbCUZfER06GDqyBkQj/0tsq4K9QDuqb7cjwJBxM3Mn87FtdyN5sC/3dja50JFWJFhycf1Lm9tRJFiPF652agq7rgStbhZDOZUa/IUh6MsFANzWPccZKr/j02bb9vUdDDHcTf2e728OFm2HJrgkXwgi8XDZnsAwDzffKrp2x2+vKuU9b5WMX2orO8Kz9TdPSL83BYmf8NEoCzINrx5rc8ObDtr0+7sq/oVC+i+BU82ASahlRZl8q7/MJ3Bp1ynltOdhjRhdi+4J9CzVc
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: ebrains
    type: Opaque
