---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: ebrains
spec:
  encryptedData:
    client_id: AgAPs+4iupNUOLJ+Fn/XD5dysDl6tqiJsdaqRcPx6AR6qLTwXlNFLxjDwE4EZ79dKJHG3PPn5dSh1izS78koDiGY2PIJv6EOT4ZNf3SkSKZHeL/9sIyci5HpwpHtwViHBWJTg8HAuTTdz5GUwHLqJYQ51UyOSyqhjA3LrQm8QpRk8Voz9oEb8tzsvUxQ1JdMdiwj2sD4YSFuZAl7eRj1RFZ1K9M4gMg5zZxMXTat7AVjHPuaUe+OMqIIEYVmxsJZ5kzlhit7UhdB5TjvoF9qjAC797CjgYrMOxBQ7vuSqmBF6Pwg99wa4ImSOjfT9F2RWbN+CL/RLeKl6oc+Y4I7hZmvazqTovwPzoYTpE/qDWR3oeC/ho8iYibt6y92uw9yWzKwh/cfQ0jZjRMQB2ctIMYPGPkNbho+p15/VsPjhLSLvVAkuzaQZVIiMA0/1c8bI7ZHhekz5ike4YH8jY3JDjQMMdJMZZUie3rV8SOiwpBNXsB7eZJKMnmlODqsUovHo91/mYM7vgIDV1M08Ly7Ezh7lAjFIUkA77T1xRyydzCCFPAbWng1ML2IejKh1wsyNCC3XPWSUphCUPwcJbAnvA9rOrgQbZ6tJ74sODlIUy0jpe/D10cD1ks4Tq52sCAMfIpADIG1R6gAjfoHFg+TPEjaCm+4pm3btZXB3pOwEmb7Ne0kvZhXBQO2Z7B4B5VywwErY1aHi3ArcxYHUtFKeI1YrRI=
    client_secret: AgB4mWCHU5S9fxQC8YmYnk5Cet0r+RY+uDRmEn5n/9kppgeyrTO2LIATcMzbpg7k3LQmbdkK9zebv5bT+5KQhCZCtVwhXXl2V8K+7rbJv5UmqKckTLrAqSofgmlBmgs+Fc0s3xuP6+Hs7jfZQ294NAduMTjuZQV3cEF7vBJBAFEmhq4nb/ROA4rtu+XL9YXG1OjI+ahGaKYpP1gxWkTNuqo3zCGNLVZTClF5xOF+xF3XQs7F4gA9xYk33tj7wZdLmu0M3aqy9kcPqjzZj3oi9/ty8DY5pckdr6ZxY2YYqUtOyVAVhSXgVpvO+00yFTmxQgEr0JWL5J5WZauXc686h7W+/fYcTePrzJHDcSglJjph88TlmrfaSP7YFGQcFKcJox+GzBO0ckdMSvlFsBb9hSdb6J5DPWqAg+lxC9UgxRg2tGAY8lKS8ytczzN1NljHdLJDcm0PC4gUpfPy2U+pPStQq+qHXC9B6mioZU7mVkdDRFBbiP0+4iWofYgvh7J3awWbk2pGHXmbUNIB37F8w/CydMCrOqGjDbwr8KKvHXPAw4/le5EnTrz4+q7eNuJU4njPj7XfY1MuhBI/7/HwPf7EjKfoKrzMzQMe3IlaAtDg+cA4tpwFXxeoOdtj2j8iadQ2ecnQcSEYxBoJZCrna2Ma0eeANbDfib83QNZoeXCSxVklZ+mAcfTMRKwidxy9glrjBJEMS+Uz+TF2MGiCcVJD3C1NZielK9Zcz6rbpmESRxPiJEDl39o+OasnvsOu8Ycs2jjEMJqCoUnFp0TA00+G
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: ebrains
    type: Opaque
