hub:
  extraVolumeMounts:
    - name: shared-data
      mountPath: /mnt/shared-data
    - name: persistent
      mountPath: /mnt/persistent
  extraVolumes:
    - name: shared-data
      emptyDir: {}
    - name: persistent
      emptyDir: {}
    - name: mount-watch
      configMap:
        defaultMode: 400
        name: jupyterhub-mw
    - name: cleanup-sql
      configMap:
        defaultMode: 400
        name: jupyterhub-cleanup-sql
    - name: internal-ssl
      secret:
        secretName: internal-ssl
