defaultNamespace: jupyterjsc
helm:
  releaseName: jupyterhub
  repo: https://jupyterhub.github.io/helm-chart/
  chart: jupyterhub
  values:
    hub:
      nodeSelector:
        worker: "true"
    prePuller:
      hook:
        enabled: false
      continuous:
        enabled: false
    scheduling:
      userScheduler:
        enabled: false
  valuesFiles:
    - values/config_values.yaml
    - values/env_values.yaml
    - values/image_values.yaml
    - values/initcontainer_values.yaml
    - values/proxy_values.yaml
    - values/ssl_values.yaml
    - values/volumes_values.yaml

targetCustomizations:
  - name: staging
    clusterSelector:
      matchLabels:
        stage: staging
    helm:
      values:
        hub:
          extraVolumes:
            - name: shared-data
              emptyDir: {}
            - name: persistent
              nfs:
                path: /mnt/storage/jupyterhub
                server: 10.0.94.174
            - name: mount-watch
              configMap:
                defaultMode: 400
                name: jupyterhub-mw
            - name: cleanup-sql
              configMap:
                defaultMode: 400
                name: jupyterhub-cleanup-sql
            - name: internal-ssl
              secret:
                secretName: internal-ssl
            - name: drf-tunnel-certs
              secret:
                secretName: drf-tunnel-certs
            - name: drf-unicoremgr-certs
              secret:
                secretName: drf-unicoremgr-certs
            - name: drf-k8smgr-certs
              secret:
                secretName: drf-k8smgr-certs
            - name: unity-jsc-certs
              secret:
                secretName: unity-jsc-certs
          labels:
            stage: staging
          livenessProbe:
            enabled: False
          readinessProbe:
            enabled: False
          command: ["/bin/bash"]
          args:
            - -c
            - >-
              while true; do sleep 30; done && export K8SMGRHDFCLOUD_AUTHENTICATION_TOKEN=${K8SMGRHDFCLOUD_AUTHENTICATION_TOKEN:-$(echo -n "jupyterhub:${K8SMGRHDFCLOUD_JUPYTERHUB_USER_PASS}" | base64 -w 0)} && rm -rf /mnt/shared-data/tmp-internal-ssl/* && /bin/bash /src/entrypoint.sh -f /usr/local/etc/jupyterhub/jupyterhub_config.py
              # while true; do sleep 30; done
          extraConfig:
            stagingConfig: |-
              c.JupyterHub.trusted_alt_names = [
                "DNS:hub", "DNS:jupyter-jsc-staging.fz-juelich.de"
              ]
              c.CustomGenericOAuthenticator.oauth_callback_url = (
                  "https://jupyter-jsc-staging.fz-juelich.de/hub/oauth_callback"
              )
