- op: replace
  path: "/spec/template/spec/containers/5/env/24/valueFrom/secretKeyRef"
  value:
    name: hub-juniq-generics
    key: TUNNEL_JUPYTERHUB_USER_PASS
- op: replace
  path: "/spec/template/spec/containers/5/env/25/valueFrom/secretKeyRef"
  value:
    name: hub-juniq-generics
    key: UNICOREMGR_JUPYTERHUB_USER_PASS
- op: replace
  path: "/spec/template/spec/containers/5/env/26/valueFrom/secretKeyRef"
  value:
    name: hub-juniq-generics
    key: K8SMGRHDFCLOUD_JUPYTERHUB_USER_PASS
- op: replace
  path: "/spec/template/spec/containers/5/env/27/valueFrom/secretKeyRef"
  value:
    name: hub-juniq-generics
    key: SQL_DATABASE
- op: replace
  path: "/spec/template/spec/containers/5/env/28/valueFrom/secretKeyRef"
  value:
    name: hub-juniq-generics
    key: SQL_PASSWORD
- op: replace
  path: "/spec/template/spec/containers/5/env/29/valueFrom/secretKeyRef"
  value:
    name: hub-juniq-generics
    key: SQL_USER
- op: replace
  path: "/spec/template/spec/containers/5/env/30/valueFrom/secretKeyRef"
  value:
    name: hub-juniq-generics
    key: SQL_HOST
- op: replace
  path: "/spec/template/spec/containers/5/env/31/valueFrom/secretKeyRef"
  value:
    name: hub-juniq-generics
    key: SQL_PORT