---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: dev1
spec:
  encryptedData:
    client_id: AgBjXxHE7nICqIGa0KrRRSoiCvbP0GX7LUHCRQpZxJiMh+y3eejxt0AMRVdmkVnW2eUsLcNpcPHYWvKq/B4/pvu4MOIjdeKv5KS+Z4x+AiI6Wn8OmS/E2uFIC0i5rP0QiJmVcA5OlL1JDnYJ1ufeg9nBpRJVgkKEQuiw9QJG3OwCchCX4vi9uabLhzzS7lY9ONn2csGlPTUZlZzNkw27S7DR0Lr0zwYa0MSd+H8aT0jrAnD4HmMsgd/YoJKNjPptnTV+8N4h7GrivxYgNRmCxSnzPU77nxA0ZwM2iSjjePAhGIlNNxND2BUk+LhQoJ+tV/wzAWmVKrD0dMfUqQ9rPfKkSVYQA3jceTuQK9z9t3HIBaYvd85LBgVRqoB8vGBhoNLP99d5ZW9l+nFoQI3TXjJaDDCJqDWtNpqcpUvRCwnLIwAl3yejZtsKbwA2NNwtouJbiDqPIpH3rPgOwO8bBsK6l4DhVy4MPHubcJGps7AniTUmCnvzBXhNlx+l7+PJHuRRo0+78feYgkvG2qeH34Bb2fTHEtlzd8CawZ7szf+E5XkXxB+diVn0PzJ5ES26CP7W/MuSqVMjluZ4Hjv1FSMQ4isrdW/F/EYmspTDaKGbevWGKpcpwWvLi3sZJHeG7LcVB+1thQTBzBRffT2Wv5GPx5E1UaJYSxMqSxf6iykpsbZ04dViLsB9D7sAxd4/Ess+RLfukTtx8isVKi7Qswo=
    client_secret: AgBm3LxcMMpmhonML4rlowZ2CrMD9op3EVgPa1HLDoY53DsNrNB/p2PUrW9Pys/IkAlxQBe4pnPJZogxoKAQWzdE+ntudXrHEkASbx9+oHatRD01JOKIkCDZxIhEqBzHmNW9L/g/VNfS4ogsuDhZnFkVJ6FEAVa18f/0kxxIfGUCQ3W/YL6JTnpSWU/QnqYvaq3tgZoPoJ5Xwcb6p0ysRRs1Lor7Pz/Ilk4EjhoztE4+Y7PIkEoEzYHssVja/2MPOZ3bgUJmBOq2jcQFyp8UuhbEzUAgb0o+QP3NXiYXX3g1XeWpchBmPnTNSUVzMPbf7IY+rT93Xg5RuNpY8TPiimnXQEU6OiBfC/oPAH5RSIXuP3RDV6pT116xb++L+4Z3pSFa3ShpYG3k1YY4gn+0SWbehiYNMR+fHtJZ8+6S1FMipi0t/HikOfrIq5mg5XqvnYVAa3Kmv+HSAjnRPafbD7Ueeuuubc+67mz98hYkvBjs47ifFdW47xNH2B11DApz3S7c9AlgYE76XZ66zdyaa31D0YvRKvANo/+Jx71+w7ESgTLahT9u58Q7KwSDl9uuS22LqLMru2llZPZu5CsI99rE8cM2xDxVYnu5V3iwpF9/CfMUEfD6JFFE4QJoRA3rYEdXv9eEBIBxukzTX3NAFhLb0i/9b2ZP0fLpD9zibA4vfOKTS+d6MRAUl7mEqrewkVQTaC7ocAg5SUCAEym3d6gdzIzxV/daNsR0wurNZRZzhg==
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: dev1
    type: Opaque
