---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frontend-git
  namespace: dev2
spec:
  encryptedData:
    SHARE_BASE_GIT_BRANCH: AgBFK02LuZ6gWtENQ621mFX89I4+7cugH1lKEc7EFFai9BFoEs0uHvNPgW5Y+Uw2kc7qPhw9l5wozxpYlv+I5gGGRDi+EpZrHy7rwyWu21EZuLvaDsPdjn//sancISYvhh/XENndzrcW+QTTw9brUm6aGdljuHph+5Y0cG4e9MoEdEE77c1e1AE7Fmb0WKIbSVhObOoEZKB5dtEl7lZOHtDAMD9QtE+Vj3BvymkcvUHeeBofbMVQF5Aa0Zpeb3Hr1YkROBJIaLSlFnUOlPC0lG35se1M2BtQIzK8VPNfzUWMQmyDaKMH6A5o8Rri6Q19BpfbhMNQ45xYwBVq/BjYvbdg+vYl7yaKJkNEdBtbVopkY1J5/v1dsARG9lbZKMeLmTp+G1n5y1/A9Gy847ELHo4K9DqgItSyEggtFZ3Spbd0vtZ00AghFEnrqV6ycN7Oew2zJjfSKpDt39apvPvxVaGax4WOk2suTlyuO8GiJYUxmXw2af+MoJpqNHpRD3vIMrrGzUgxyJhZZxYFv9rxTWpVTd2xnUiWI1VH4WlBMhtMyrxxbYxTaUquEznqFaOAx86YbC1K0cK3Pi0u/7379JGCQxZurqHdRpyiEjARklkMfbB8i6GTmm6ZBEVg1qphxsAYA821phVxvsX9BYWYBswKSLxjFHkf1dWJxO9RToEfCdB2PjTmxvhN53YwIO5Yk44Ki59M
    SHARE_BASE_GIT_REPO: AgAHtuPOgYiwqb0y61CTq+SJFoZZdtOCd/k8zATKD/A8kmHLctjMLICKBe7gsfG33KOI1/j+q7+QBGst28QrJES6XU4LA+CzQgenuM5Xxq7CTDvLGmly6h/rSFOuvrU1bmec6ugHENj/kvL7ISo2heie78i/Fk4EsVLEw1f562uKip4PG4UgeP/ffeU50+i7aZMvQIBuNA5pjEhwb78Ry/C9TUOveDsDQjBKm77udRjcFRdOCaXMELa2huGR2lwsfkEPWz8ytmPCMiIuHBVxppmPd6B5RdyOsdYGyglHTI9reIZIebTsdbthAvQsb8bPvEnEzueqCO8Cj5SoE4QT1/JL1IyvIHbhbEl39d58bYaLMj2KF/aMvM3ThJ99wZtoySdLrfbK6ZK72QKqgAc2Xrh0Sl4V7GSuyFUhc1+HYTVqFhK/HKIwSyh6RQk2qF9OpMWlS04a+YKENGnMW3v6XK49eNlIz42FsGCVbphYCCzBn/A8UZnnXNrTdF9GTmhSPfgxC6s7LbHsMutj5M3FGTqpI4zV2ewMdTrFGwaobC6mmV68cl+g5CcmGQBHstnjRetjhKhPcZ2bg9HLZCocH4rvRKESSGRTp+TtDADBL/OOPXETmkBVpVIaBWhul+lmn7mG7E/J2vDvcg2LYhm8b23xEqgGxnMXf86aajKxHtdGBQTxmyoroTPoqzhwMUHyjRhszBXIBVgPMFvkW6jVUINheohRs2F5QUClu66TrFhVqPZcDfAdKp+jyG249bW5gU8=
  template:
    metadata:
      creationTimestamp: null
      name: frontend-git
      namespace: dev2
    type: Opaque
