---
defaultNamespace: traefik

labels:
  app: traefik
  component: main

dependsOn:
  - selector:
      matchLabels:
        app: traefik
        component: secrets

helm:
  releaseName: traefik
  repo: https://traefik.github.io/charts
  chart: traefik
  version: 39.0.1
  values:
    nodeSelector:
      worker: "true"
    deployment:
      replicas: 1
    ingressClass:
      enabled: false
      isDefaultClass: false
    service:
      type: ClusterIP
    persistence:
      enabled: false
    additionalArguments:
      - "--providers.etcd"
      - "--providers.etcd.endpoints=etcd.etcd.svc:2379"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      # - "--log.level=DEBUG"
    ports:
      web:
        expose:
          default: true
      websecure:
        expose:
          default: false
      traefik:
        expose:
          default: false

targetCustomizations:
  - name: staging
    clusterSelector:
      matchLabels:
        stage: staging
    kustomize:
      dir: overlays/staging
  - name: production
    clusterSelector:
      matchLabels:
        stage: production
    kustomize:
      dir: overlays/production
