- op: add
  path: "/spec/template/spec/volumes/-"
  value:
    name: persistent
    nfs:
      path: /mnt/storage/jupyterhub
      server: 10.0.20.30
- op: replace
  path: "/spec/template/spec/volumes/2/secret/secretName"
  value: internal-ssl-jupyterjsc