# Default values for storage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

grafana:
  storageClassName: "csi-cinder-sc-retain"
  size: "40Gi"
  name: "grafana-pvc"

prometheus:
  storageClassName: "csi-cinder-sc-retain"
  size: "50Gi"
  name: "prometheus-rancher-monitoring-prometheus-db-prometheus-rancher-monitoring-prometheus-0"
