defaultnamespace: jupyter
dependsOn:
  - name: jupyterjsc-hub-helper-once
  - name: jupyterjsc-jhub-coeraise-helper
helm:
  releaseName: jupyterhub-coeraise
  repo: https://jupyterhub.github.io/helm-chart/
  chart: jupyterhub
  version: 2.0.0
  values:
    hub:
      livenessProbe:
        enabled: false
      readinessProbe:
        enabled: false
      command: ["/bin/bash"]
      args:
        - -c
        - >-
          /bin/bash /src/entrypoint.sh -f /usr/local/etc/jupyterhub/jupyterhub_config.py
      containerSecurityContext:
        runAsUser: 0
        runAsGroup: 0
        allowPrivilegeEscalation: true
  valuesFiles:
    - ../../hub-base/helm/common.yaml
    - ../../hub-base/helm/hub/config.yaml
    - ../../hub-base/helm/hub/extraConfig.yaml
    - ../../hub-base/helm/hub/extraContainers.yaml
    - ../../hub-base/helm/hub/extraEnv.yaml
    - ../../hub-base/helm/hub/extraVolumeMounts.yaml
    - ../../hub-base/helm/hub/extraVolumes.yaml
    - ../../hub-base/helm/hub/image.yaml
    - ../../hub-base/helm/hub/initContainers.yaml
    - ../../hub-base/helm/hub/services.yaml
    - ../../hub-base/helm/hub/others.yaml
    - ../../hub-base/helm/proxy.yaml
    # We overwrite some values in hub specific files,
    # so the import order needs to be hub-base,
    # then the hub specific config 
    - values/common.yaml
    - values/proxy.yaml
targetCustomizations:
  - name: staging
    clusterSelector:
      matchLabels:
        stage: staging
    kustomize:
      dir: overlays/staging
    helm:
      values:
        hub:
          labels:
            stage: staging
            jhub_version: "4.0.0"
            hostname: "jupyter-staging.coe-raise.eu"
            drf_username: "jupyterhubcoeraise"
            logger_name: "JupyterHubCoERaiseStaging"
            TEMPLATE_GIT_BRANCH: templates-staging
            STATIC_GIT_BRANCH: static-staging
          resources:
            requests:
              cpu: 20m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 1024Mi
        proxy:
          chp:
            resources:
              requests:
                cpu: 20m
                memory: 128Mi
        ingress:
          # Set JupyterHub in maintenance:
          #   Set enabled here to false, update ingress in maintenance/fleet.yaml
          enabled: true
          hosts:
          - jupyter-staging.coe-raise.eu
          tls:
          - hosts:
            - jupyter-staging.coe-raise.eu
            secretName: coeraise-tls
  - name: production
    clusterSelector:
      matchLabels:
        stage: production
    kustomize:
      dir: overlays/production
    helm:
      values:
        hub:
          labels:
            stage: production
            jhub_version: "4.0.0"
            hostname: "jupyter.coe-raise.eu"
            drf_username: "jupyterhubcoeraise"
            logger_name: "JupyterHubCoERaiseProduction"
            TEMPLATE_GIT_BRANCH: templates-production
            STATIC_GIT_BRANCH: static-production
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
        proxy:
          chp:
            resources:
              requests:
                cpu: 20m
                memory: 128Mi
        ingress:
          # Set JupyterHub in maintenance:
          #   Set enabled here to false, update ingress in maintenance/fleet.yaml
          enabled: true
          hosts:
          - jupyter.coe-raise.eu
          tls:
          - hosts:
            - jupyter.coe-raise.eu
            secretName: coeraise-tls
