# InitContainer list in hub component:
# 0 - prepare-shared-data
# Container list in hub component:
# 0 - check-frontend-files
# 1 - sidecar-nginx
# 2 - hub
patches:
- target:
    kind: Deployment
    labelSelector: app=dev1,component=hub
  patch: |-
    - op: add
      path: /spec/template/spec/containers/2/envFrom
      value:
        - secretRef:
            name: generics
    - op: add
      path: /spec/template/spec/volumes/-
      value:
        name: persistent
        nfs:
          path: /nfs/hubs/rke2/staging/dev1
          server: 10.0.2.191
- target:
    kind: Ingress
    name: dev1
    group: networking.k8s.io
    version: v1
  patch: |-
    - op: replace
      path: "/spec/rules/0/http/paths/0/backend/service/port/name"
      value: https
