---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: jupyterjsc
spec:
  encryptedData:
    client_id: AgCTwAhS5BWutMe969W0wzsa84FaNe6LxnQtAqjAlOyuFM+VvkNzD4YUpuv6/ca9pfsKQkAb+Fl+hSGc0t/dQZ9N6Jo4XZc9Lyzbayb/iW4Nt034IXK1EuoDMO/EaPBCKjZansooJIyeemE+RbZcSmOSk7xmWa6shmtoW7n8ZC4tgX2bdD7wQbDl7bDrzogfoPsPbTTWA4+i7WAg0+pUhkGWUrgA+rv7brsIMwRFHcLrxgaif4maeTxRfTlxUs+Nw4SEBeYh+PgQRFeemjwrhNYOgt2jfFq5V3wdYYeuYc9zNv+i4AGeRDJ78pcPkvQmQKx5IVRkrrL3+r8kHePwePhJ79t5iPMXxyHVdRrAUpeKqSGbjHmKrByqug8zpClEj9pUV3zTMokZvFBsKzojAErAqks9L4YJ1YRtLTUgPQo5OruZ8JoBddEc1sg+V8jNT4rvNhak6PXlZ5/a2Az0eFl6pCyUoRq3uAJ3U/7weXbMNtS6cG5mWEzUr7yq1AUUXNJ1kcJrovD+h8K4irgN5tMMo4aXdpu5zDTClAHNr4dWz98fZ30HPk5n53byVWCIFp6zWx3vDT2xPHpuwiozaiz2XFtL4NJriYLb8CFYMBX5c3l+oX7fbdyAhAMnCgQXjOF/Zvw6pjiH/5WJstB2QpYJH+3Qd/WJKQ92lDW5dJsT69WjJinH0zlD5PqhXWQTPNc2jq2WW8o3DHf6AbQJD7O8kUY=
    client_secret: AgC4vhQhZIp0BhygOXhNJxpH/CWQouSdHNp5mOpYy50pRJLsTYYsm6LwXRZTroA3hmvUVcFKeHFEz2d+tMNoCq3KiFGYCXxYU1PoGJ7dMKaznonU90DX+y8Mn90vj/h/k4wa/Ibbkkt+8xn/S6567GKO2v/IEXtvUpGdWEktXcDOW1WzOaSqjrkETPRRGYdM/Pudhwv5IJKxspAJsmNDYeRmMjfDt40nMOpf7+dmt7byxOuS9ZDMdH6XmeUZB4RUOaEyYaJ4hegnAXnWzgK4HJRSAxis3bTKgek238GWUkNMViCLcUL/EaQ+6AMXHRzWBWPXlsNRA1oHmnTePTxNh7UI0+5HaN+d8Nk75e0ecrbXNVhrcqdVCov0GdSXLjb4Q2QDRL1ZURRe63XC5dywHtwlqDtctvIhf/kF/YUMvf9sdRwlxmxFSMGA+1ZATW5F2SP+H3UECY5xWL+ZYxxuEXsGQMkt0AP8Br/F7faEHYYhYJlhHW2VdLlJaxblq4rrLEpWNgbt80cADJ+3nkeYBqfRd0JkYmqLFJIjvoOTnlyqePwK1GT2gXwGccT3Kmk8ln1kO+52VuXTw7Vj2XjXRW0I2CPrbWY102kDrT21MQqM5bM6OUqD4a7vlTgk8E77UpWN/8/vQ9/cDSvZa1IYBIGBbx1+2ehfi54bX9Qo0idfhXxqLSBsniNUdUiCqpxSIxv6H78jsetFNbqrDs/yV2s9mwOm8P1MzDyA9ntkMmfAvw==
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: jupyterjsc
    type: Opaque
