hub:
  config:
    JupyterHub:
      cleanup_proxy: false
      default_url: /hub/home
      # hub_ip: 0.0.0.0
      # hub_port: 8000
      init_spawners_timeout: 0
      jinja_environment_options:
        extensions:
          - jinja2.ext.do
          - jinja2.ext.loopcontrols
      last_activity_interval: 60