hub:
  extraEnv:
    - name: JUPYTERHUB_STAGE
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['stage']
    - name: JUPYTERHUB_VERSION
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['jhub_version']
    - name: JUPYTERHUB_HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['hostname']
    - name: LOGGING_CONFIG_FILE
      value: "/mnt/shared-data/git_config/logging.json"
    - name: MAINTENANCE_PATH
      value: "/mnt/shared-data/maintenance-check"
    - name: MAINTENANCE_FILE
      value: "/mnt/shared-data/maintenance-check/maintenance.json"
    - name: RESERVATIONS_FILE
      value: "/mnt/shared-data/reservation-check/reservation_test.json"
    - name: TUNNEL_DEPLOYMENT_NAMESPACE
      value: "jupyterjsc"
    - name: TUNNEL_JUPYTERHUB_USER_PASS
      valueFrom:
        secretKeyRef:
          name: drf-tunnel-passwds
          key: JUPYTERHUB_JUNIQ_USER_PASS
    - name: UNICOREMGR_JUPYTERHUB_USER_PASS
      valueFrom:
        secretKeyRef:
          name: drf-unicoremgr-passwds
          key: JUPYTERHUB_JUNIQ_USER_PASS
    - name: K8SMGRHDFCLOUD_JUPYTERHUB_USER_PASS
      valueFrom:
        secretKeyRef:
          name: drf-k8smgr-passwds
          key: JUPYTERHUB_JUNIQ_USER_PASS
    - name: OAUTH_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: hub-custom
          key: oauth_client_id_password
    - name: OAUTH_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: hub-custom
          key: oauth_client_secret_password
    - name: SQL_HOST
      valueFrom:
        secretKeyRef:
          name: postgresql-general
          key: SQL_HOST
    - name: SQL_PORT
      valueFrom:
        secretKeyRef:
          name: postgresql-general
          key: SQL_PORT
    - name: SQL_DATABASE
      valueFrom:
        secretKeyRef:
          name: postgresql-users-jupyterjsc
          key: JUPYTERHUB_JUNIQ_DATABASE
    - name: SQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgresql-users-jupyterjsc
          key: JUPYTERHUB_JUNIQ_PASSWORD
    - name: SQL_USER
      valueFrom:
        secretKeyRef:
          name: postgresql-users-jupyterjsc
          key: JUPYTERHUB_JUNIQ_USER
    - name: DEPLOYMENT_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace