hub:
  extraContainers:
    - name: cleanup-sql
      env:
        - name: SQL_HOST
          valueFrom:
            secretKeyRef:
              name: hub-juniq-generics
              key: SQL_HOST
        - name: JUPYTERHUB_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hub-juniq-generics
              key: SQL_PASSWORD
        - name: UNICOREMGR_JUPYTERHUB_USER_PASS
          valueFrom:
            secretKeyRef:
              name: hub-juniq-generics
              key: UNICOREMGR_JUPYTERHUB_USER_PASS
              optional: false
        - name: K8SMGRHDFCLOUD_JUPYTERHUB_USER_PASS
          valueFrom:
            secretKeyRef:
              name: hub-juniq-generics
              key: K8SMGRHDFCLOUD_JUPYTERHUB_USER_PASS
              optional: false
        - name: TUNNEL_JUPYTERHUB_USER_PASS
          valueFrom:
            secretKeyRef:
              name: hub-juniq-generics
              key: TUNNEL_JUPYTERHUB_USER_PASS
              optional: false