patches:
  - target:
      kind: Deployment
      labelSelector: "app=jupyterhub"
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      kind: Deployment
      name: binder
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/1/secret/secretName
        value: buildpodsregistrycredentials
  - target:
      kind: DaemonSet
      name: mybinder-image-cleaner
    patch: |-
      - op: add
        path: /spec/template/spec/tolerations/-
        value:
          key: "node.kubernetes.io/disk-pressure"
          operator: "Exists"
          effect: "NoExecute"
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 10m
            memory: 20Mi
      - op: add
        path: /spec/template/spec/priorityClassName
        value: image-cleaner-priority