---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: outpost-cryptkey
  namespace: unicore
spec:
  encryptedData:
    secret_key: AgCOT+RiYuAlZZWWHCWFtT2OVaKtju4/nC5t3puX+sBl7Vd0LRrWvYF/rCz5XBjcD7I4qgp/ZT/hu8yeapwuWlFY2ZM2Hb/gwM1Sie+biwbSp+I3wIpehArTkj3JrV2GSKhyS5cpk2cyKV9IDRv4EVDj9Sk5WqBbJM0GCIRbbom/OHqD+C4NrAYFCrY+N0z5g+Ljarp1A+AmBpjJ0kB5CyZOUkaQGD7kFkNSdG4HcMEU/+tkLro+z0dKCQmRNAntYhMDvm2oOtxyg3UQQWw2+My1C01jblphARBDaWvMiji75zKCCA4p474oQvMhmVbPoNVx6iq+T428lf5BDwkqqlMqMpn3S+umViHanA2MtPwNFGEj7eHGxv/92pfsJ2AiwuscHE0ssbODCIgi89BPTmy9vw9ko4iOLmqW+hSUn4aO/BqKId6fnOc4MIz2zeNg3+kPQFoAqpAOUeQiT24zAx4hadUQv7dVGyYX/deYG+9JhKq6DKnB1WYdEo87eh5H+htrXSFk9f3K5PTHknQ7Ad0ypA3XDSKwa9eejiG0lM4ldVH985/H3l2F4hw59EyCbYPdqy5bAYfSRKJ4WlLEKUREXK9vWQabbGls/jNlRwcrUlwvNMcRSqlPmxo1XIFZBu5W2IZAip1zKnhEMWXvS9PX/4Cj86XhZngeLVHWk2a99ATTfGcMP9eGp321Hw0TzyU8P3i2ULH5Jvu3xL4it+nHdPxI/MB4b+I/VVY0zRO2UydxOmlnnV8frksYKw==
  template:
    metadata:
      creationTimestamp: null
      name: outpost-cryptkey
      namespace: unicore
    type: Opaque
