- op: replace
  path: "/spec/template/spec/containers/5/env/23/valueFrom/secretKeyRef"
  value:
    name: hub-jupyterjsc-generics
    key: TUNNEL_JUPYTERHUB_USER_PASS
- op: replace
  path: "/spec/template/spec/containers/5/env/24/valueFrom/secretKeyRef"
  value:
    name: hub-jupyterjsc-generics
    key: UNICOREMGR_JUPYTERHUB_USER_PASS
- op: replace
  path: "/spec/template/spec/containers/5/env/25/valueFrom/secretKeyRef"
  value:
    name: hub-jupyterjsc-generics
    key: K8SMGRHDFCLOUD_JUPYTERHUB_USER_PASS
- op: replace
  path: "/spec/template/spec/containers/5/env/26/valueFrom/secretKeyRef"
  value:
    name: hub-jupyterjsc-generics
    key: SQL_DATABASE
- op: replace
  path: "/spec/template/spec/containers/5/env/27/valueFrom/secretKeyRef"
  value:
    name: hub-jupyterjsc-generics
    key: SQL_PASSWORD
- op: replace
  path: "/spec/template/spec/containers/5/env/28/valueFrom/secretKeyRef"
  value:
    name: hub-jupyterjsc-generics
    key: SQL_USER
- op: replace
  path: "/spec/template/spec/containers/5/env/29/valueFrom/secretKeyRef"
  value:
    name: hub-jupyterjsc-generics
    key: SQL_HOST
- op: replace
  path: "/spec/template/spec/containers/5/env/30/valueFrom/secretKeyRef"
  value:
    name: hub-jupyterjsc-generics
    key: SQL_PORT
- op: add
  path: "/spec/template/spec/containers/5/env/-"
  value:
    name: SEND2FA_CONFIG_PATH
    value: "/mnt/shared-data/git_config/send_mail_config.json"
- op: add
  path: "/spec/template/spec/containers/5/env/-"
  value:
    name: TWOFA_SSH_KEY
    value: "/mnt/twofa_keypair/twofa"
- op: add
  path: "/spec/template/spec/containers/5/env/-"
  value:
    name: TWOFA_SSH_USER
    value: "unity"
- op: add
  path: "/spec/template/spec/containers/5/env/-"
  value:
    name: TWOFA_SSH_HOST
    value: "zam2041.zam.kfa-juelich.de"
- op: add
  path: "/spec/template/spec/containers/5/env/-"
  value:
    name: TWOFA_REMOVE_SSH_KEY
    value: "/mnt/twofa_remove_keypair/twofa"
- op: add
  path: "/spec/template/spec/containers/5/env/-"
  value:
    name: TWOFA_REMOVE_SSH_USER
    value: "unity"
- op: add
  path: "/spec/template/spec/containers/5/env/-"
  value:
    name: TWOFA_REMOVE_SSH_HOST
    value: "zam2041.zam.kfa-juelich.de"
