apiVersion: v1
kind: ConfigMap
metadata:
  name: init-kubeconfig
data:
  init_kubeconfig.sh: |-
    #!/bin/bash
    ca=$(cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt | base64 -w 0)
    token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
    namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
    server=https://${KUBERNETES_SERVICE_HOST}
    echo "
    apiVersion: v1
    kind: Config
    clusters:
    - name: grafana-cluster
      cluster:
        certificate-authority-data: ${ca}
        server: ${server}
    contexts:
    - name: grafana-context
      context:
        cluster: grafana-cluster
        namespace: cattle-monitoring-system
        user: grafana-user
    current-context: default-context
    users:
    - name: grafana-user
      user:
        token: ${token}
    " > /tmp/sa.kubeconfig
    kubectl config --kubeconfig=/tmp/sa.kubeconfig use-context grafana-context