---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: outpost-users
  namespace: outpost
spec:
  encryptedData:
    passwords: AgCBR56IZPbJaFGBi/jcHCHfcXK+wS+U5k2OkTyfhvlbrNOzh9vQHAmpE+M9j4ucdOKBKujjtCrx+xeK/UNU61LwfbabQ5nyxcTN7owuOxFjhXu8Tvplx4LlCn9t2+58iBSUEW0EMOcJuGf0dasUX46UKzaVscz7QKf9SX/iXf/HdblGZY/GwOjaV1vDFx8tbla9ZCzIusbal16KTxQSY7xm1y82yUA/K2LDvpp2Gu0Gom2xZb/gtAeBT66zr+Zc9H7ZamxO2PX7kzn+9oqdAO04DQSg1IwnQPjjBEZIxNhgSy8BQw4xbIzZwVvnArgnsM4hvo0sMDL5wjI3lgS4k8Fbqs7QC1E7IldLEic/So07J4M4GTLX3pKcHzN8IbRHooVKyiHySVRld0A7GqxHI3rUSfkHiyXX9RWMJlHSTcmybsM8HnQOdC4cdrzH47pIktrfmV/RUdbKvLWR2gby/iiw/yrb4cXdwmQoKuMxyyUs7VHJwVknnMCerZ1hPkVqTAEDbXPh+JSBZf+RxStIRNBLwvk5wI9/4Y889j3XHAUDIZJlPAj8mg17UAZhGC/zZLUzS55GTJ4bqCe3wufLEf9r226XQyNUugkcSXI/6C05Mxw8gNMjWTc/6tz0hAfQja6vxVuES3gJ+abkwJkO8iMvm5Ld85mVHzLI2dYKqpTMjM+OQrR1Z0QNs9Ow/nfL33WxttWe7wPTsNnaeEwBv6R5rCav4WxS6QbZMQsplm4YsIKSRFFlvREzHJaNgQ9Tsk8GgxZTXEihQaObabbArd1PqIyVUYKOxTZWd/0TuHzEAHzTnLIdtxdwYjGytj9QD3K0u2cSkjA8J0lDAEPCEiIyPEaknF93SMb1taGU7BJNUTRYvwGF5oMUJ+NJnJY5Ez/t09gV3xEi3ZvI3eOvaSoGZ8QYoy6FtwCOIpJmYTEJKtNpYIWKE5mDUJVne2w+XDt+G186yJc/w+OPt1Lbo5ZldES989veYxoKWAuSLHpFR19b2ICApZgRPtHHuhe0C71TeHF8QTcJUmdFSLih/W3Yepw=
    usernames: AgAtpnf5KWS2Sa4jxs8FRZGflTEoHbTz8wzFc8xayvdlJ2UjzcxwTWOMh8n9oslDyQDHAMauhnZQFbULGRJkOjvjRyxNh48120B48C+y+63yL2wY+eMbv5nBnzQ5ZF9xGnnjbFxl8dk/JXJiJQ3SbdZMh1EWZY1zXHSDcCQcBgdHLEz6SdaehtYF4BfIRGqXEYgqqkJ8dCFF0owuxID4wpeHe2oCDzhe/qHJWDQkzROZ9LSryrU9UEFeNH3c7r/V5YZJxI17bfo69qdNrnvwvLqNHoUAH00JS1NNS+Wd1c+wor/mhkO5xJ6ADhCx/HTt7+pvFKR9gxgL8ArIMJWc1Kkw1gfqVTO+jF870PKVerl80IvlvioCo9ywKreWwkBfD+bPPLM9dmPP9k+rUBT+b5DEhryQOJRBuxneR3ZvIIfXILNeHmyg9Jzmfoc1UaGaut3rQ1AIQaPHNhqSCj+IwPKKzD8N2CKf/6Q4lvRQVH/tKPdbDVHjtquaJFfw+ineBupM/eg08yE5y4DmE0VYbYwsbccNeETF3W1qpHupyhqFfgjVjcM4TQH5R7JvElOSW4FnyaIlLLrrMFzlBwIn1sgDa44BXcHTUj38DJXWJR8Lhe/d/IvXzxxFUCVYL7INl0IWPx+krIQIJXeI4j6CVpv3kxH+/wm74jf++jChx4SDRZ3e9mfZJrsI07Y4GxKdyGX98UbrhB7aHqeLxgyyCciLTtYsBpn889xjww1nlgVsW+1GIWKT1wWNhTJmsszq1HYODw/MXoX/rnSrrhw5CTT0
  template:
    metadata:
      creationTimestamp: null
      name: outpost-users
      namespace: outpost
    type: Opaque
