# Default values for helper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "jhub-helper"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  hosts:
    - host: jupyterhub.local
      svcName: proxy-public
      svcPort: 443
      paths:
        - path: /
          pathType: Prefix
  tls: 
    - secretName: jupyterhub-local
      hosts:
        - jupyterhub.local

labels: {}

podAnnotations:
  sidecar.istio.io/inject: "false"

service:
  name: "proxy-public"
  port: 443

gitconfig:
  branch: "jupyterjsc-staging"
  secret: "jupyter-jsc-config"