# Default values for helper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "jhub-helper"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-body-size: "2g"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippet: |
      ssl_stapling on;
      ssl_stapling_verify on;
    nginx.ingress.kubernetes.io/location-snippet: |
      add_header Strict-Transport-Security max-age=15768000;
  hosts:
    - host: jupyterhub.local
      svcName: proxy-public
      svcPort: 443
      paths:
        - path: /
          pathType: Prefix
  tls: 
    - secretName: jupyterhub-local
      hosts:
        - jupyterhub.local

ingressuser:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-body-size: "2g"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/location-snippet: |
      expires 0;
      add_header Strict-Transport-Security max-age=15768000;
      add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate';

  hosts:
    - host: jupyterhub.local
      svcName: proxy-public
      svcPort: 443
      paths:
        - path: "/user/([^/]+)/([^/]+)/"
          pathType: Prefix
  tls:
    - secretName: jupyterhub-local
      hosts:
        - jupyterhub.local

ingresshubstatic:
  enabled: true
  className: "nginx"
  hosts:
    - host: jupyterhub.local
      svcName: hub-static-files
      svcPort: 8070
      paths:
        - path: /hub/static
          pathType: Prefix
  tls:
    - secretName: jupyterhub-local
      hosts:
        - jupyterhub.local

labels: {}

podAnnotations:
  sidecar.istio.io/inject: "false"

service:
  name: "proxy-public"
  port: 443

serviceStatic:
  name: "hub-static-files"
  port: 8070

gitconfig:
  branch: "jupyterhub"

jhubfiles:
  branch: "jupyterhub-files"
