# Default values for helper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "jhub-helper"

proxyBackup:
  release: jupyterhub
  name: proxy-public
  numberOfBackups: 5

labels: {}

serviceStatic:
  name: "hub-static-files"
  port: 8070

gitconfig:
  branch: "jupyterhub"

jhubfiles:
  branch: "jupyterhub-files"
