---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: outpost-cryptkey
  namespace: dummy
spec:
  encryptedData:
    secret_key: AgBn9Oe9QiQQpX/jbKCR33eyDM4NBxZG9a071c3xlf22aIvutiHAIjPYDMCS+bYI4quf05B+wBQblnf15WrAnCSKUW5tBod93xQGz/WZ6AVNPQZipM+QONFbQMCa5KgJXwMzgxFBUeKiGDxaerfmNh7GKNvnRrKAh46vKK+m5uQxAc4OxkJ5RmFw0Ma3no0MgVoLG5fO3cGe3IsQU+dT9OBC7NuVPMt7BTU+oE1aC82TLkcT5yQmdVAW1SgcnsTNDqq1VJb1myvyLDrA3Gma2NQZzGO6lHekWrQ9BKE1j93ilKVF8bI5M/XJJEyn+42O6r78/LJkcAxpJ771hW6c3G0X5VYg9RlJEH6sAtFX4C+VjMjxc7pEY1A661hIaOuTT7kdQC/ncl8UENCxhFJm61ojAC17XqIx3eGZToVFZUBSzz8a0bn/ZJE1y9tG3xEAT6fqOsp2awd3iKPPIZxfs1hqsZcXdhTuzlmeVmv53fjEmWwUJQBCzzEokwoJpKnKPBs2wcwQp6yl/p15zUB/JNRYPkt4AcxgqwVnPl8i81ZCtLS442Wur5qngJIW1m9ktG6CMYG9B0/yzUfEwPeb3kObZpjBugrJGqHndsWvfBWRvInZTW50Ufhh69wvIzFaMT6PKjGBhx78Jq9z3qVCNQG5AiIAkoS4aeQ9juDC24u+2zeJ0wD+AxQUDYBH0e3Tm7ZsDLF96M0NXORrzVxzVWYFuzj6XFxg6MrjCizUVeGLUOzwdx7Q39QT+ztXAw==
  template:
    metadata:
      creationTimestamp: null
      name: outpost-cryptkey
      namespace: dummy
    type: Opaque
