---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: outpost-users
  namespace: dummy
spec:
  encryptedData:
    passwords: AgANA7Uxx2UwTYIi5eBztgz+53W11WnPJJi/DdlKsXO3FIGwHtjp6UCgUteCFES4UezvewpL//YyH+LzrC9SrvYuYOsiE0k8KNF4XsDoPsMI2oZmLt2MBus4qFG9xkLAUT+sWBElLKcCto00JKVDZvhPs7Eb9+TPUXx4JsAGqwyFhgMAhQxEFMVTqtBvAoo6tpSJu2tP297Y2GsxhtHw+ALHnDfabRyZ2jIkTdqAkZ1oJhg/5LTFE5vhJYzF/LyY8iX1u96e+dVTHlh2c+OS7j+PlrY4xLKrBaF5Jd/eEVPk7xmpLUHyevPwGjzLswhmLzegEzxMhzCKgycGJkrpDlAOiZCsa5DRD5aQ/IEmHIFtQcDpKJLFZso6fmfZ0D5HG4NubFv2r8W5I0YMDva7G3waS4rvr9Z0IYKLeHXHd2OZ049jxepbgYKs8rde2q9CKtLxg8jL35hWgYGxZhBehCIc/gJgEYRHx7D9UVOB+I7ypPgyWXMspHF6NMh5mHtcMn7iyYUMvqoevOQOyOA4iluXzCFZiVjt76mcExMx+TcxTsppmqFXw//CrvZ9imPTqgDY30/7ITymnOAP59STnKq9tSrDfKimn7Jd/LvaNJlqN9SZzJPimzaVYNgxePKD1FA/yxGBlT/4vLFcYjYGT8wZp0++JqhJ6+40FpPmu9QpFMCLHxt1ng1d5/MUKDy+js39/3qhtezWJPItjEaI7XzEGIRW77AtxB7ZbwP/dJ2iZ6OiA0MQJvbTtDom0XEjMqCZRcqzeqQUP/D+Q7mTywbpGXek8ufNNiingRVD5W1BhqUIFgohfbDQ1cinrwzsyL21ovS3RtVSDX6l9A9167UKVOOdtoyNA7bamQUSZivQl90=
    usernames: AgCWPW9zmoVynJ65/dzWaDKb7yCypf07MypREJK6hbI77Q6YuZ3KtSbh6VNI2pbo6BCrovgZnI5KegsoLepX8muVyrXzIE+uST0COElfrB/5gISAJbw9dGmOrXyFIkl6VJiYUhztzimwdCQY0fq98N57CAHDbDVRtsmKR/MIoAUYenB1bYbTe4HGY7DmQdbUvGBfHhgZKqgRZBeiMhhQ7ymeQlufl0JNtp3b8L0pAGT0s5al0udkJzlWHmb1SIvbX/t/fMeSqt6bHDk0Cy/8iMPXvCCNiD3/uX6dxwlgPRSRGFQq3bIcT4UL0VX3V9uFNaLtSQK+N9dVagfCtGNrj/+2TkGCuxklu3qPjf8I6XRf0gJPzTcaueSlQae+ZNO1xFlxMffdjUJZQyiok80/pmCEfAxnYid5OE60ThWmIBv2Dvs9zAZihBzg401jH2VCZT9NOzrZNSjD7pxp0AoE/jTYDYS1M9mAYmTTAzRy6jmuudgy4NYf3OCzYOd67nHfSPIVGX3IB7rw38DE0wGmKAJttv8aSO2XaioIMi+WzbcnIG50+tlktMBmUXJaXY2KfnZAfDfYHWMJ7y6xo+SNY2WvkNq9ysaIHGc+EA+LMKYtvUc0NFbQH6RmIYocQmrLy3yqoHQkDCiOF/r1bn8i6MTeKZny7J11jfFHcKKm5gNWc6jMQ4144oIox0g51lwnLJ7nHUP2G56tVLE=
  template:
    metadata:
      creationTimestamp: null
      name: outpost-users
      namespace: dummy
    type: Opaque
