---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: euroccgcs
spec:
  encryptedData:
    client_id: AgBfcpyBaLLViURAdGGrwDq2LQbvVU6jgNAMAMS0uk4pQYS8vgI2dqyng1yg7qwKKVz/n+Ti6+PBO2esGquk53GVJKXwnY6Uhrc8PsLR3vrO5jaFNwYLZSmY+zNENXIvWfpiQ9eF2Tkbw1p21U8A70u+VsaYAHWl28FYHfj0l5Xq1wf2VG/g9KkAqm8GlXumUeGxEfjMLyTvInRIz9ngXKBKOTdkhiznOlDLh2CSkXAqwYiO20byysC6CIZoNZeWACNmc4b7q/Oc63nU4q1xQOFJ2JYdEu+mUtuVxdlYJX9wRTQ9tbxXag0WLE7eA1K3Nv30VlJ3owx6A9/56n09km+ZMqiaEk88SeQjuAv+Ib/txKUfVyPG4YBoQlz+pFzFE8hsxFqElZWFvqAnBrV6a8PxxCTNxnEUqTwFf5LZ/7I8yRxuX+qMcXTcFBl1hNgnxS/od94p0sQ7mSL8to8YNEKbDKx9KNuNYoo94RYVQbNpbw40FRZnkQvx6nJjN+xZcrUWyJed98jiUMY9sL8w7iqI6W2xkVULA9iFRudLdxFZ17OzD5Va32yK6WT6bY1HaXqN8e6V1Sde0Fgypwo4O1Qan42gWihszLbPD/UkPQ9dChVpD1BWNJ+9NUlM82fJVn/lbdSSTUCx8vbHWcNGqrzZqGIqewZbhGr1SaW6GVPeD9gpkYKjoJVjT5oXB1gx/LfYdlnayDnfp6p2z7IZXevo3123kQ==
    client_secret: AgCdFfAG+WZ19mJeccgCCEQSiMqIn3uKwteZhb9YdV2oobv4o/D64F1A7MF7fzf04gsKo+yRnfTdSEKL9Gm0io9kDEjC0pK2VRVcSxexGjFtSdqemutHALm9KuH85afDJz452OU391zLgCKLHyHS7YB/yg08WHREwoSX4rhW0v7MOrXa0TT16iULRTwN6vXeZ7gq3k4SEzPvtpA3Vbj8/1jUst8LfkavrI8aeWxm4pSBaxZEyZtRzhERl7S9nNKJB1HgHGeK6SLZLUZIMDpeSIKtdBqN9ZdiPNDJIvilqoefAgznWulI1MoxkjlTpvR9l70aQhjLht2PL35fGfdlqTmYHpnanstV0BJqFPhIvbX26aFdIYLqWmn7J46fXNevIpXz29FUUhqetFzsAo79i0vsHua40QOoqqdWAtfL1DZ5VF9mU7U66Cp/yiQI8NZhKmZHDdGhvYQUecKfk+FRYxJUDbaTxBLuPbvOPhU/RerQBgWmL+H6UMR0vuQrZBGjJFsgDqcj7v5ThJLAh7T25nhWeWZr6QSDhIO7zPyD4DsgJ7RkszRqORolncjQtTKO2barW8+XvS3FXZRmTw0gzG9/akRtNb0PriHNDg7u/0zfgyNwcjYQqvMp1v+cnm701Ah/6xyR8q/zzCJVhtz9XP2DJPitmt4Fk4z0haFXSZShL+ebm6rvwMOuY0yjNusqUxKQuFSqiciJK9ap759KzXuxoSEB7cqiGalF4BY244MTJg==
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: euroccgcs
    type: Opaque
