---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: euroccgcs
spec:
  encryptedData:
    client_id: AgA+ws5hpn1ke8+KJk+RcH1QidYFMpskRRh+0Gj1W01ooO9lPYkq+X0WhJBe2ILJbHXBug3xWCIVTOmWjjnH+8HmDyVkzCMQonf51lTEPVu/XBW2G+xNESjmVvf3s4R9IviVujTV3aB1JZQ2T01eUjA9zXJfqepZiKnm2zMr/QPNZwZRxZ3bpFSsZ2X6eCVt2z4FARIOwtDMNgrO86jtV7UUBMF6kHdMMeTqJwGDhiBWJlAwD/bUqOs71uNGB7O4CyFOAS6zSJlJ9aZQvbIHoEw6VRIRQ8pxe3l7lWp1vk5LTzTVfQSw3WVgY0r/XMyPsrfSG9Zn3J7KcJ/c2Idi8mk8c6B8QxuHRQUHtCoBLiwIRvHWQUjT7i0qsKD+qp6hElyYdFMsf+UJ/R5lnkHmPI7kwi1kQTFAGqSnEP5+pdIACLFH6H6uRYxCSkcVKg+hJNWTIvB/gkyCYynifg1VWg1Svcbwb3ExoHscEITOBhq2gdfN7xwqhEPTuYY5+2gvaBvFi32Ffe0utabodTvs2DAK0d2RpeWT1VBewbPJ52pPIzdnQilawPsjKfX1JyvalFRQlhHhrnkgBtxdveJGzZTj/HjMto5P1HFANQLXnToQCs5hbTYfxWD91IuF0xJNU3d4f9FUtJKFvmd3DFCp//5/zBk/Yk1op674A8LW7IiDA9UWoyN1FjNZLQR6VCmkjIc+QoypJ6FsGwA5nCuoS1Z5XuxmFIFB4JT1
    client_secret: AgAUjdjzTPjuLg0bDvCZx7sfHaFcTD6D3S7L3EqRbMRb8udxCaxHnYvxIhwdt3iaKTmrV0xKrMwiuPiP92zUm75g3/054dZAuUrHHMH6fTWhi7SANJYZYDIIinNOmiRh3YNcsVtdkF7LU1ImelcjP2GRfIzoDYHx0DWypvQjqVbeRf8MNyDWP1HQ0aaXLc07PQubpajXFmq8tR1ttaDZSB09Ndm+fdlXZ90AY2zl91LmNBJGXHxRitQ1FzhIwrZLyKsYznxJZMcPDM1upxw/GMFdnHS2aMcES/tA46Hc5QgNBSuI2PcDrUKmlHpXsO/7NPU87dGEJPLCKcEaPXxBvcF5o2Mxq3z83Ig+WH7C13SeQWPvNZS8nmIJGf8xckbHJ6vhYccMa0Po8awi/ZzUQr7txCSpp8Qy+aRPSND4OQihT4dlR9Xze2bX2PHpoSlGWyOR1xd02GA0Ic9RhTvvrveLEvAHQt0UG03ozPxEtf13Fub/OUmRH+h4ZkC0Se8w+qB3gG3fiXdvHN8xcZxsf3JVfmEUjz8tOdtcwjZ2i2WdbP5jc+PMEOcWR1QY162VGxKX+49cn254DD5OVOrgtPUGCBwPkYXucROaLAq9BPLfNgQq3REftK6WWCkd1l+48lpuE2esBu4bHd2UjeVCa+b3lMTsTJcJmbcLBb57DR+Ldowa6C0DaDd2IL9mTjGGfFTmq4IYCQ77NBxERoAzBQ9UVrxm3dIQahaJChfVBIleIQ==
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: euroccgcs
    type: Opaque
