---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nbviewer-secret
  namespace: jupyter
spec:
  encryptedData:
    GITHUB_API_TOKEN: AgBgzuJ5NUe8xf5bde+R8/wjOt5uPVjCiGHXyPIMSvQsBSZVxVn0p2XkOHWwhf+eUhCrCqgzk13DVmXSUXtFctHrTkkBYCOa0+pHrpnIjQXvNGEAqSRxkWwlOIQfQBiAOYABiknwDAC3jSAPGAlkeAzH337rGRXGEfPTmwSXdjzlVs0s4PuyCqdapuCJ9b4GoK0lYp2YgQoEMbV8XLdGiTkkJmxWHRGnORN7A6KOTczedqh4gFLaWO/yJ1aRLQ3+j3wD54gNKIH52OTK9c1tXnJmQyRmyVbBun1dViYPkQtjT8r8RZfkyo7Mw6srkw0B97m3tmcjF8jpbywzZYiXIYonn95Gf0sDyaBoRjXlt47vqmeYjrMxPmRpdihbuM+Ty3H4GRU3fNXutcPc8UuvAvwG0vOM3b51l8kFh6SyVmrxJaPkXCksd9bQrGfiAj66e7REYhIvLq3rs+Za82WYeZo8gNKqofYNnaflpyNJggxBuckM9cIep9fbkLcHDmHBfJnx4CFT6RN9eYw9AkPMlZtVDAPT15Ajpshu2unFnDpSs5Gi36Zn7D5Rd42AKr5oW0Ivq23TJTpJSDyoJTIyjsHYA+hDv4MaZ7wZG8unK4MhWfOJmwmGirylC5lxEjGCY2BxAw930kT0IOR9+A5iiLJqG3zw04Q0iDKcP/QDSWVRoxbDmWoz2wtPQxkcqcLjXE9li30uGVvLmIrmgGjk0ipUn6x0MALcZ4miQH4p5sv0tTAuX6/GvD7F
  template:
    metadata:
      creationTimestamp: null
      name: nbviewer-secret
      namespace: jupyter
    type: Opaque
