- op: replace
  path: "/spec/template/spec/containers/1/env/0/valueFrom/secretKeyRef"
  value:
    name: hub-portalgauss-generics
    key: SQL_HOST
- op: replace
  path: "/spec/template/spec/containers/1/env/1/valueFrom/secretKeyRef"
  value:
    name: hub-portalgauss-generics
    key: SQL_PASSWORD
- op: replace
  path: "/spec/template/spec/containers/1/env/2/valueFrom/secretKeyRef"
  value:
    name: hub-portalgauss-generics
    key: UNICOREMGR_JUPYTERHUB_USER_PASS
    optional: false
- op: replace
  path: "/spec/template/spec/containers/1/env/3/valueFrom/secretKeyRef"
  value:
    name: hub-portalgauss-generics
    key: K8SMGRHDFCLOUD_JUPYTERHUB_USER_PASS
    optional: false
- op: replace
  path: "/spec/template/spec/containers/1/env/4/valueFrom/secretKeyRef"
  value:
    name: hub-portalgauss-generics
    key: TUNNEL_JUPYTERHUB_USER_PASS
    optional: false
# - op: add
#   path: "/spec/template/spec/initContainers/0/env/-"
#   value:
#     name: TEMPLATE_GIT_REPO
#     value: "https://github.com/kochhlrs/jupyter_gcs_eurocc.git"
# - op: add
#   path: "/spec/template/spec/initContainers/0/env/-"
#   value:
#     name: TEMPLATE_GIT_BRANCH
#     valueFrom:
#       fieldRef:
#         fieldPath: metadata.labels['TEMPLATE_GIT_BRANCH']
# - op: add
#   path: "/spec/template/spec/initContainers/0/env/-"
#   value:
#     name: TEMPLATE_GIT_USERNAME
#     valueFrom:
#       secretKeyRef:
#         name: portalgauss-share-config
#         key: USERNAME
# - op: add
#   path: "/spec/template/spec/initContainers/0/env/-"
#   value:
#     name: TEMPLATE_GIT_PASSWORD
#     valueFrom:
#       secretKeyRef:
#         name: portalgauss-share-config
#         key: PASSWORD
# - op: add
#   path: "/spec/template/spec/initContainers/0/env/-"
#   value:
#     name: STATIC_GIT_REPO
#     value: "https://github.com/kochhlrs/jupyter_gcs_eurocc.git"
# - op: add
#   path: "/spec/template/spec/initContainers/0/env/-"
#   value:
#     name: STATIC_GIT_BRANCH
#     valueFrom:
#       fieldRef:
#         fieldPath: metadata.labels['STATIC_GIT_BRANCH']
# - op: add
#   path: "/spec/template/spec/initContainers/0/env/-"
#   value:
#     name: STATIC_GIT_USERNAME
#     valueFrom:
#       secretKeyRef:
#         name: portalgauss-share-config
#         key: USERNAME
# - op: add
#   path: "/spec/template/spec/initContainers/0/env/-"
#   value:
#     name: STATIC_GIT_PASSWORD
#     valueFrom:
#       secretKeyRef:
#         name: portalgauss-share-config
#         key: PASSWORD
