---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hdfaai-credentials
  namespace: nfdigeneral
spec:
  encryptedData:
    client_id: AgBhc5JjCWR6XweQ+ZIERhjW1UyDqsc1XWDJ8HdXoSnEv6F3uhPhFWrgJ5OE7FlyuzDVF2AjoDZEfPDKGq7t1UxBcScc2lWvEMpY6Fi3FOWeaJIkZnxYs+ZUlirJ//rQmrGffh3HlvWNzqkbZkmn/d/6UrNWu3gi1SkTYa19Y73yXHwB0M0qbp9GllOZUKgZ3KwfmRfAZiHGOzn0D/a+nWu7r8Ps+d5R7N16XiZJczIxVRztBw70gJVjJGevTT/WfyUz5p/Gqnw7ZnZXqdKL7cChyYLdLY4goXrYest1s001/TJw4ZagpVX/r2GUtdXYZh3ap8F3ZfRfKh3rZ90ifZ5ugvxqPIBcB3eB6G54p79BXXUBpqkM0g9WeT3BrNaW8yQaOESVr0MhAwGx4/bSv94D6EPc+Xbnq4ju4lW3y8LoUjJ9DaVut4sAukLhvTf7YrcD4xllzDIB43TSZ+NHN+21IqMdS9/BnbZWL+o/P827SmjHJODz9C55zunLfDmStT6O6101wbKf2NrGk3If7Kmfnhy42gGLEuyNWK95iR317v2WCKSqAa793wWLn/QFPbA22svpfCY3XSg8aOVlmhqOiSrdjV0ZU0xCZnp5/Hj0tSrCJhWfKAF/T9SR1n7XaUvqSiUo3LyUkV2C6j2hsNDAnXn+E3oNDsMKqubff6shSR16z2juXjfn496vKZtPN6K35tVvwB1oATP4FTBIH3+H/F4oobWotA==
    client_secret: AgBJh06HQG64tn7Auz0AdCcitcNCQyprX5V7Ow3H70m7F5siHnDuomdMnM0/cqc31gba9oHg+ytsXO06jOTcaRSnpFFmuOjKsHiuAd5tWjz2xZ7uSflcsXw5eQ99GZ8duSYNWLNR/YWBy6t1jzrnhUsYV6FbogeOnC8fFwJf4sQRcJ7XQirJYbyLexH2vNSFeX9Pd4lkgUvhWSUbWLkzq2EdqZc7VTDEkF4How/Xmqsus9KTcRnLpvBc+IvEhL1U5KnWQ8DOu7/OWKJnQD7GiYbMPd7dEw0m27gKPEBDcjNCY71sWohe/njn3lkfsC7j/L4zQNlzhUw8uo0RdHtw22vXvQQ9txVt0K3rmQLnKDA7FwtP8y9lPKWNi2Q3LDai1QthJX8AxI5+IXqU3EDZYOZZAwCXqzSBlp/WMSkP8VNe5gyAmuMdkY8klLzwx/NmTJqQcpNN2fYCih3LCMU14fO0hwMkMz3Vz2RSDDYvCeC6NLjOhKey0FlIzytOC3hVvceQ6GNCJJViIiRyPTUFFtpHqWHphSg6T/GyizIEv1nLyshQmC0mrHDH81vLk9bhKU+iREx78neo3XAyVs3lwh4G4qhUgtbQ7LQt6eodxXqcFVtzMViReGXzI4N4/2pkzcAlWt1RIZkBbnI6wiM4+7+mxpFQuT0VZPqC1IGp/ot+Ip+22QEyk27sc0D2AoVkjWOGor+CzT6vDsVejtcqHVRdICXQMp0xafRZGVeT0Q5G6DzFgpw=
  template:
    metadata:
      creationTimestamp: null
      name: hdfaai-credentials
      namespace: nfdigeneral
    type: secret
