---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hdfaai-credentials
  namespace: nfdigeneral
spec:
  encryptedData:
    client_id: AgCilv8Vz5iYgVqnd7UWPFhvtpi3quhVOHQvHdjd7Km8PnI5Gcc5YUB922vXVsgD6iTgvH9nPnWw7I562TPd9CWrYe5ShsQ2j7Hru8MZF18cXWQxjewgkgAuwhy0U1o067wJPGJ4lPc8ztxWPdMCB3Gk22pIXbCsL8yJeDJ5XuY3CgEHbF01RnRpN4Rj5puH1hbm+Eccwf+bAMTtjhMKRQR5b2kCuS8WAvCYzvZ3D8e1LkPqQ6jIcSmrwkvKpQjJeCkAVvueF6Bg+rB1sUomp2zU9cao1dqq8CL2gK47mb8Qf2RcH2bfzPlFn8rViZWz6O+ZJyPwkgeBz/28RiRwlWV6MEUBb7ELRcpxURYRwgxWP3l0b5GcQTGG2zdStMDZaaTMd3QqmjJWJm3YXqqtqQVJqz9zcW9xv/aQtHxEjjVJ2civ0dB7G+gP642oL5J/gpJZ9CFgcTAa4L6SRyBAeIn+0Q2PFZfI4fTatP75xHwH0I5S9VEdABB5gLyest33T/+LHXcLMBUKUyNdVDwJNHdhKQ9BhAEl9FvJjqCf7v9HXUp2+B59WMJKY0iCwgoRFDx66Qlh8wgxszEQAswiXnXyNZ453ZoqTF3VYzrm9wxOg0btAXujl+ooY3tf164HhGtMMTVR/2VbTwE1J1aDxz7p8FFPTh5NjDPBIdNoEB1jMMSXGXhZ9CNAhacdCUFwIAGFBhLkHNnwJ8uOtCqvWqjiNKkvPwI2OQ==
    client_secret: AgAs7zjTxmJ59zlkmCU/dxKay0uKq6LDY8F4ltpktdTBZ0DOCpQPBrQVfyMj3k2WFfcfbmLwHTEaTzXxOpVbWh4rCndVgccApJzdmJGaCUwGxANjPL0b9UARq9AB/9A3mjXmcbWTqVhkTAtE5U7iMpZUOjzEBM+M/uer/7ApttA86orHEv7nbe7r4TKj4xPKEDpH+Q/0DUJvn+lereN94rMoM8Y00rkKznde2HSI+NgcWPIc7H5O0jx2765G+2IWHTgic6jqO/EDWPpbXpDlUujQgmkhtM/9XfYM9nktwAQ8HYN3k+ewbDUuoanbCfcMnBlXJb5s+8gZ0rVjpUoEfinmpWXJavAmk2L7xSUKN7Mgkk+wYQvtt66Vt+c8v1wWxKn3D7IRSJ9ck1kILTPvluHEV0+zpjyk02ES7smz2v7KEBg6Qswiws180kEwl4f5rNdq+4HlbO5ecZ425i0luW2o5obZ4/Uplp5uZd097ZLIdrW8C8bGNtxYZLD5bVLy1Tsv6UYFscJ1Ti5K7csWu5MvM22KmVv5oLUQ0w42ADn14FJ+5u5FfQAmK8R6xE6MvSUDx2RUs/yudO+mpa+VMQL7ygoyTnXyilyOZwgqc2SBmx1ceLm1IiqJ4Dzw963kCum5V8y2qEBdA9hd3NVdUfeGStJtw5kTEOR68oOTJWn42FQY/t4zxz5CZP8c9ZP4cE1quILic5c5+TuttFJLwZNBF/c77NV0169mtDA8N70jZg==
  template:
    metadata:
      creationTimestamp: null
      name: hdfaai-credentials
      namespace: nfdigeneral
    type: secret
