---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hdfaai-credentials
  namespace: nfdigeneral
spec:
  encryptedData:
    client_id: AgCYT3gvMwLwbvucj22CGX6pB0ODdlvPL+BeDk/uCEZGGNbU/v+utzshsSwGCKnT4Hevb2OWTHAkfy+tEEJhMv5ewVrAqMTGjnPh2Xr9noyvvygMXo73ycgaqt/F1PYLibCJiiTtiwhgwL0y96OGxyAB8fOFzkQ0pPnEEa7hXTLyMuAeBV+xTO97GgYE5SqrQ8ztKnl1TU0sXu0QQrb2rzGq65elQJMfGPDFlLsmxpQPFtBGTTG41+JU3fURRc0I2uoi+OGAlGt2rxkYmsalWprc62Lsi+tqmiN3l36x/GWNMaeS1tj/kQ9vW0yD3HTzr9RUcBMUPYls/TIOx2ZleEVI3UVbo3etRqBQXSyebNnpU3Acn6QRaArc7f6/IU+gZ5+F69N4GqW6PNhimnVq7oS51pWNr1g57suVfnkXYPpNmABNe/tFGOfgWvPNY1a/UWQiWwGZVuVyR3RPoSTWES1V69sEbxFUCG98uNPuKW0erHAUqqo3g00tIqg366BHzvuCzwYYvxrgQpy5hMidLcOQD5Duw55GdorC2UT+suu0nRRqGngefFzFvDTdMJuSXCHUXPDOgbII1TdnPqQyrxCibN7MiWXfea/JHYbGEvkFts7qEmEhgKss9XMMj74/B5mnMP2Wr3hk6SB/gCCOp0goBvznKvVyU5Tm9hjPDtTsvTcXmHU8a8f2vWe6UqKK00fV9DUN5myxTiiG4M+HMrQVKxd2rY0nkA==
    client_secret: AgB2KXkHaaJJ7HEsnloRscpgIaiwtOqoRkA10m+T6iTWYNnZHREfYq492YPOrz+Ve1DIK23bc17h7WES15Ti3ASz04Kgv5Knkpqqu+e7OM5NU9NGKBZsgWoP3rD/91llL1tOXiN8W4+UYgeMK0CYNmSIdEdclm2yvhYQ0vyucA1s5gmuQkaJOYv3Y6qxgRS/Jcd+ZXr5NZT90Wnejrf0wO7HLjshileIx+EBGBn5ZHpsLUVRkCgRluWQ7YJdbkNl1A++n7n/nMBRqzQ1djYT5uzohO6tguUAgA21kWQHyE8CPiHu/c7zi7HDBu7iv0Fe2WUX8LYmiTuRwosMV8aB+7wgpYe72KTfpUXq4sFiDMv7cueM4G4xNAreCo0C6qOE9b4MuwRi7VzOzRQNoWad+bVeJ1WGLLBBFR4vV0fUN1uQ1foZzL/fU7IZGuZyTPDe59M4Se5KMkgXBQ6wPcj/iEuR1fQ9gk7iMF5nx4FzMYbkeeIPilcGrxuhVXsWzWay4LhtSR8Rz2xjbE9Mop8gtWhj5QOIv6q+5zZxFiich2DjSvNYWeyv7X6Efvvi/GUiQ6f77AiL0OtT/9zHhOKUnXn9GLlQLXwJJs2/mqVBbzubAxH6oQYPsnOLpjEQvk9TJvptxJzl26CEmZ4UNq5wt+fNod+nCTIgVQi1o0vvvOGiS0L61BVyYH619tvuVulPhPrdbIKAqIFLLpGZ7bCNAlX5zYxpH7dJfB+kpc02UDkdEXzKFgo=
  template:
    metadata:
      creationTimestamp: null
      name: hdfaai-credentials
      namespace: nfdigeneral
    type: Opaque
