---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infraproxy-credentials
  namespace: nfdigeneral
spec:
  encryptedData:
    client_id: AgAeDWApGFDJAV+L9zEFEPyi6gckbmWJVTYhnxNxoKhFAhRX9+RORL1ESBF3up2AZ3hAaHoaMOBNkkjdWvZtdMWyYE6w9MJ59l5YIZyNrd7a1fmRhpmG1YcN1fzvadGvPP/BsxYArUihwRG0xrRKXthmYnwDceZA/jey5gygDAzwKRID9aTKFJRjVE+Ydv1TjSalhBFe5SXQUoaCJdpkc1jt31X1Ti4hZ03if3f98Ze3wGX4QonpWkkyb7Nx4QUWEuNrMM9e8ryhLnNPgNEIHAg7zhdX7+RpYmJWgdEqsKQtyaxrw2684gBKi8OmQ9OJCgewyH1o55cPCLMOV539CxIQHFQm9pSWknubFziYcey3GUuc7vveuB0Ttb5O/X4nmU527f4akfJkOWABHNyi7uOfFYtDwzLW7iDBkICknSxqppaTcckk5xemKv8nQSRfiQ1jmLaZa6XxLc0pAwXo+edUeU4VZ5PuZyr58Io5xLHXrKGUS55ciQGsn4GZt5dz5duDCTcL0kV2TzYlI4t///eSgrtUnlteTlMBgK55ImSJN6Z3DwLYOgAJlOYHGP6gL6EVmnfHdJJNUnIhdNGJH6C0funt3Z7QGRD9DbGa3gaKPe0Ro8P0CahrFXRgB8d89Waa2P60i3E6R78U4sx92xlMR7jFi6SKrDzVM7LxT36j87QXvLWjMkpzjQxE+suSiPQrZKtemuvBrA0/CXbj5VhFr7KBaSX+ffTkfds=
    client_secret: AgABs2OzWrWtunngFk9GnxTYMgDqd1s5cb6eRmFazBHPrykg4SNdcjsi44JRizWLlfqP25aUl4tqQb5ti1iMNQhEN9yZ/5WnzfnEHb2S+L6Ju0MPMiilxKquvmwFjM3jQoANSlP+HnBD5818FnFsk6i6ahdPEIyTcuB3y+XDg/gBUI9P4pPiczpgZRH9KJd1lL+sX6rHYNp7ecdAxPiJ8Dy9tBtFhv0ufTT5chLhQ1pDvwMAPIOkRK1AqICj8HXPT53ih3w8MmkTfrDkqfC74a9tW4MRfZvRvQ0/Y8gLUkssFjrxVvdsmshXIh8JbGc+CBnTNl1nhBcsHNOAYzy1Wibk1UvriykMOHC/thBZW90/O+9RappCY/9YDmflxxjyDRoU3f0ZAkFtgkAm0ZjPRqMoeSt61tEoaTTDUgCAQCjRDyqeEXjq9SD9mb70uTyFj6+84pTnxVZVjm4qog56T0xql78HwvOKTh8nYfyEpBvQRJn6LnBJgdtEjHyMRD6ESXmeEZGp4TOunvCh/c8qn26qC2WJbAher2NePF1XXfEOQQZ+EcF9NFhOihrYlfyOL+j5V8ptZ+DfENbu+IsbFY7YwJzL23I+wVk0ADnoQ6vWtrOkgW/J8CVR/iVKdT98jTsqB8w8IeS/Lwof5AWOmJywBOMpUntQHv5rRZqhn2VRK0QS5QV/ocXZSVxhfIgVvcGCc4kz2g5IfTeOQVI1L5YwFFDQO1YI4SYdpayGvI1v0my8XqsGz/YFEqCVr4EjHHmZluX6zoKMCd6+2mQOYjpa
  template:
    metadata:
      name: infraproxy-credentials
      namespace: nfdigeneral
    type: secret
