---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infraproxy-credentials
  namespace: nfdigeneral
spec:
  encryptedData:
    client_id: AgCR/JaebysaEiTqv/s7WA6pMZbT+A3387zSfvm/Fj4ybJXcWx46NssUosNV2LRsOf8DU9ZqeNH09oUVnSFt7Ekq22I8hZRg2sDcwYlIoFYvz3XOVb+OV84Hdm3isS6d37Lx+iNbMumvtiVo+bjaMhsQepFuDavwiaAnoRqO0DOUlq4wwPP7MwFt76V2931Jj7PMEVHElJ8BrCvxg2wUCTL4hFZlVf9GdbNAivDRX68nWRHikc17qWLT7f9d3UmXtyFmk29vmvomsLK2fQuPIvqJKDL87it1OLOQjVqtS1Iuz6p8A9FV8aTpMR3ka3AHLtcs7Eq2bFFJCAn+sIA53PbaNR4Aj5Rw4k7hOl2J0qdaXXaCO7QSpyPiqJ16wFYKRLcZ5ZXU0LnyxO67F39maROdu7weXOALsP8BadbHleiHN73HTR/7Iu2GsCoI4gxWOYGwFNtXocQKHXUM5DSALrqexlJSjrjAQ2gVvKcX+IgbB26w/4hZcf1jdU+haavIW3wkp56y2FA0WbAl2rEChxclXJuo0cIvTmkiYuppQntDFO9W8d0oTTNNZzQVHspWQZl+Be1wY5OY1BOJxPb1TdteQ170lxtSlWX8U/DwDv1EMS88R5BcMUu2zivW6yswSfnhy6jPNicqhYza4xIx/ZWYNgtbXEscWkKfNf7EzGvtNdBo+Ao3cfnyJoU8DhUJ8akMh7ZCsKHGMO/MO3wYU8rM3bfa
    client_secret: AgBfWmJlEq8uFvi7Yf2haHq4Ry0Uv7pEPH5F5Sz9bbV8OV05We8wYOtdtX0UL/rjh+atS6WIV2plfaOE2meRtskMGXslWqcuEupTdVQp2bALpimGPiiflYLSmkho0BsWTW3daPrYns2muhzq/JtL9+SLn9eNQQ6n3aPEmqePdahfbA7NHRQAFp7W1pWqXQc5ZDnuAU8hxwjFpi/EQ0E7BKeuU92tKEdOuJ8/Icl5D7TYsSfuU/DzGew2U+0JN90fADLNKL1PJ+YtlBJkn3rrF5dpyu+dfgDvF6Sv3OzWSZjxX0JaC3v9aq+WtMMRQvfh4DzXD/GMxgMnZfq8ll3sFVlmmop6r780zblNlYOKXZrS5eHEhTe/nuswPnz3xXwnnca/vapx9aSmXj00kZX6z7uXXYA9o/vO8J8YMBSEASoccuQL5yexo3GPVkLiUVdTSVqTGXgwhhkRkEaSxWO7ejYA7lZ3M4RMm2gsHmhO45/d7Ni0UsMQFhQgZh0zzgzNeXDTzx/oXeQTBW1bxqq/2dmX+6RWe6qvak4j9dF7Lbj2jKUq16MEgUKZ86ug8Ho9NIc+BnqqrMejo/uptb+Id4oKIrMWRbNhInvvTMIAd2OmG898IRf3Ezr5KjmgHnIb69ZO7EMuNzOlXMnfkiyR15mMu1DGLKjS/ZFNfArxS4F5QfYTJ8Gb2CnFuNzXTndSLNfEu+WtfkzAayc6Hpyqxv9rtbFt5V/1bVveU0jhgKp8KmjI7i8A/7f4Hi4YwuCDp2kbG4J4slbxZQfADRvkCRJ/
  template:
    metadata:
      name: infraproxy-credentials
      namespace: nfdigeneral
    type: secret
