resources:
  - jobs-2.6.yaml
  - jobs-3.2.yaml
  - jobs-3.3.yaml
  - jobs-3.4.yaml
  - jobs-3.6.yaml
  - jobs-3.6-juniq.yaml
  - jobs-4.2.yaml
  - jobs-4.2-juniq.yaml
  - jobs-common.yaml

patches:
- target:
    kind: Deployment
    labelSelector: app.kubernetes.io/name=outpost-unicore
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/readinessProbe/initialDelaySeconds
      value: 30