# Default values for rancher-monitoring-storage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "rancher-monitoring-storage"

grafana:
  size: 40Gi
  path: /mnt/storage/monitoring/grafana
  server: 10.0.94.174

prometheus:
  size: 50Gi
  path: /mnt/storage/monitoring/prometheus
  server: 10.0.94.174
