
c.JupyterHub.internal_ssl=True
c.JupyterHub.external_ssl_authorities = {
    "hub-ca": {
        "key": "ca_certs/hub-ca/hub-ca.key",
        "cert": "ca_certs/hub-ca/hub-ca.crt",
    },
    "notebooks-ca": {
        "key": "ca_certs/nootebooks-ca/notebooks-ca.key",
        "cert": "ca_certs/notebooks-ca/notebooks-ca.crt",
    },
    "proxy-api-ca": {
        "key": "ca_certs/proxy-api-ca/proxy-api-ca.key",
        "cert": "ca_certs/proxy-api-ca/proxy-api-ca.crt",
    },
    "proxy-client-ca": {
        "key": "ca_certs/proxy-client-ca/proxy-client-ca.key",
        "cert": "ca_certs/proxy-client-ca/proxy-client-ca.crt",
    },
    "services-ca": {
        "key": "ca_certs/services-ca/services-ca.key",
        "cert": "ca_certs/services-ca/services-ca.crt",
    }
}
c.JupyterHub.trusted_alt_names = [
  "DNS:proxy-api",
  "DNS:hub",
  "DNS:drf-k8smgr-jupyterhub-forward.jupyterjsc.svc",
  "DNS:drf-k8smgr-jupyterhub-forward.userlabs.svc",
  "DNS:jrlogin01i",
  "DNS:jrlogin02i",
  "DNS:jrlogin03i",
  "DNS:jrlogin04i",
  "DNS:jrlogin05i",
  "DNS:jrlogin06i",
  "DNS:jrlogin07i",
  "DNS:jrlogin08i",
  "DNS:jrlogin09i",
  "DNS:jrlogin10i",
  "DNS:jrlogin11i",
  "DNS:jrlogin12i",
  "DNS:jrlogin13i",
  "DNS:jrlogin14i",
  "DNS:jwlogin00i",
  "DNS:jwlogin01i",
  "DNS:jwlogin02i",
  "DNS:jwlogin03i",
  "DNS:jwlogin04i",
  "DNS:jwlogin05i",
  "DNS:jwlogin06i",
  "DNS:jwlogin07i",
  "DNS:jwlogin08i",
  "DNS:jwlogin09i",
  "DNS:jwlogin10i",
  "DNS:jwlogin11i",
  "DNS:jwvis00i",
  "DNS:jwvis01i",
  "DNS:jwvis02i",
  "DNS:jwvis03i",
  "DNS:jwlogin21i",
  "DNS:jwlogin22i",
  "DNS:jwlogin23i",
  "DNS:jwlogin24i",
  "DNS:hdfmll01i",
  "DNS:hdfmll02i",
  "DNS:deepv",
  "DNS:jsfl01i",
  "DNS:jsfl02i",
  "DNS:jsfl03i",
  "DNS:jsfl04i",
]
