---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: dev2
spec:
  encryptedData:
    client_id: AgA8/vfD9T8p5y/iLAjCT0+kuQ98A3dWdoZCQL3KsXou0VNNoyKVz9zVIFn5HzZOAlPn52CZb4ByWFaSFk4gtAOmRG4L4ybDRgesCyLszoG72f1D4zo/dwpdo5dEpXBAZ4suM6daA7Ycf3b71g09xD3rAkxTsUJACvFl2UVoJiHGe7rGhZ7gmBEKuYjc8DYcnwUE/XRHZUiH8lmQDn2pRbXMwtvsB64mwcPNKkVL5qDH+PIzM+EfymR+QxF+2QNF8NiYFg89vXH7CA94FMv1ZPOGGnTUjbwGhcq6j8sqhWE+Rs+3873hpSoqOA14CJv2yzSV2tKD4+Hnh7ZDSTMB/4wXN9VoiImR5M9Q6S9bBUA5+Gt1+ujQYxt9D4F2gFJPVf0gLBy0Qn9sQmd9e77BY/8I9X1YCUdqsrBDwKlmXSgmL2h9mLfjP6SrhYSBwd61az21P1XI1NOwwxl1nucrmuN9SYNz8+VqjFOVivjA+aPn8x6vushJUvz6RFulQI+bddBjE03zohB7+oulG4NuqkMIkgUucxvWKPAg4xTUY0Ny1FiOy1jF6ien7eyt9LUPo9aBO9e9uDHcoYqlMN3YmEQVYwj6kU6ovSgzbjsa3ulCmc0/QyOuTF/vGlsEc1Ddvd5woUYC9muONB0NceTJnS/6OfsS1R3K5cqwbHtZ6T1n5vHuucEd/Bo87HKihxMz8nK30cR2nBIfwhqr1XFpDw4=
    client_secret: AgAxwnpCsTY60AP1Lkbfr+Foiy+ftMxm0+94Jyer7e2Gr5Pz6uLZxYKOnfz0L/z86+yqWtqAv8NNg9lHmvdCCAOQYCAfi27vyadr8l0QQl12CjBh3anIbSkorbL6uZfoivSY2R3OI/lLcqwP0pQYL651FAyOQXmVhSbbC0D6OdWDL5rK7e/RJ73AD/efKoWyq7k9/m+4HyIjpCiYBid9QVl0jDv9hVW06jJnbAsE9HAkX2bqrHf/egCQvFfIvz8u+ufz73OcWjJK+AAxOUxkm9qAdSIh8Hlvh8ONvVtR3pxFxRW+OdQ6b7YiX5+h4OsCu+E39jovS4xuBtQAAbZO+cLo2I22CejMyAixCiZDperMeSg5hBme+291oyd0tbWdVYeqqJlg7fuy1CtQRh7i2pS2uchexFUzZOFdy5kcjBO0/AXSoSPuGSnMA9UfOD5EfGZBLUxpJxQpHCkjnMy9UvWghzAdm3NuhBzObx+aip5vwz9jcMB5l6Z9sbeq0tgjz/Hrl9FfN/4BupOaA47D4HaeEP75KpL1OHYDzU9f2Vik0HCPg+buaOEctv/mA43TIMZAwahBpxHRzclv4CIbqXQMaS4/m+QuxhgGL++tmows3yRa8zeNrUJQfPZ4Pw5JLUBoSs3bj0nTaMmlttxRXR14XYJ2D60SMMxsWKtOWjIzonJAFrZaFeOMyNftb83jJnHVlLiBIhoiYblcATQGxx3L/O042pWuDg2f31rz7ZQFPA==
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: dev2
    type: Opaque
