---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: portalgauss
spec:
  encryptedData:
    client_id: AgAjCDrylRGD0613fboFh+4vQ6fZIHdOSin37YnNRvwVW6do7umEaPWMVR5Co7fmeMuCwMlzdT7zbLJVQXL8znzDgSYL9zmkztNBY9JXYUiqt7FRReHY5X4uiE2vpT1SqpHScDms0GEGY9DmyBHxdo68DutcCqCk20b5Plfib8aI38TDMw5Zv4vokn14nxmuIMZnJJ2PIo5uCuOSTcuA9rt45jWZw1GOuB7S5L4zzhjsi38svcOOhfTsXBySKdevKWXkwv/xaG5R+STRIo3tc0gsi2R0s/OFl49SmZQ79rmfZdHzIIIeBPS9Ixg9fiC5bNM8YUK7kciKschSuFq7YOqWlZpctSbpi2wZ30KyES9dSHOqvCzhhpc27TXvJ009xivxWfIVuBFEKa5L2Au0a2dDsFGzOtBgTj3aWFf9eLxce1iury3ljd0lc0wcMeKqIoVtpa9Y0va3GI865rJ7uq11B/l9r2FGW0+iJsMD6h/WehVqq8UHDIFQzDep1d8qVqcC9gx0RBV+68yMtzuoGp3r9mNsox9NwycLiurWGYUYtlutxSrKq9fWPakdxopHqepV1DKnmbWV4owhPJuQcQIkfw7MvUHIpSiI3NGPdGcowpcgnyeO4FkcL5Vl3cGVhSlyo1/jPVuG8iC3L7pOpjy7zsj1+xyvBhH4FWXP+zx6to5vdY+A52cSaKRWQfSIg1v+x1Au+py2cSI66QEcNYeob5E83K/jJDN3
    client_secret: AgBRNSHZhsBojgONi+JniAZE0PI8hQOaqXcbhfClo3n9DbZrDh9PmbMvK+MQCktCurRDNRyjKzTQH5dsoKxfDQBZ1OztfvvoxNnlnW6Yh3zNfTykN4t+VgQJNmO8blay1oQwZ2wTuBQF9yUBd/v1EZykgnH3KEiSL8M7IUx5d9ZKC2vZhvQx4kwYkPuQW2Ik0OYYU4trcIt7vfgnRQAFfMuP2yA1HlwmJOSJJXxdrJSRUiJzrIXvJUxleQinqDX1PL4gKN7YqWk7EfVDKoaKIlOv+EIgw5UVgOI7VYHJuzdSyIDXhNw6rH2t6Ktirs9Y9w39yIO7tX6PizKIqrYKXmlAoCdW0Zt+F54HpU8kPWVwm7TObOcLU931Cob1ouY6lbZ/GT03osrvijU9Wo7nxg3tbQjK35GVbIzYDLwvchnAYDlJGy9hUXcEldLz+BOjIMlo7xf+CJPmNmXQmAw5wfL9kG3/WWkhRZvjwuQDrrvaUpWJ5EZcITgXWIcvKPT7wWl1ky2i78Nhy1tROicBPAN+sBl6rGdvJm1S1uaOzcWRcSmMYMsfhwJv6FtMgIui7fGiEyN7DaiWDr/p4GgeTmGIlHNgqsmqmzrhEg/tbEkIb8loqHorMDHW7J2Td24w/xQ9PIB2iPgnvUW8tcB4hrnSftBDLlAcGmCbFSzepi5jO87xatRmvGjorbu0kal/ciRStnmIh+vI3kSHadwA9Lg2p2AnL/Tg08EFX30nbBSYjg==
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: portalgauss
    type: Opaque
