---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: portalgauss
spec:
  encryptedData:
    client_id: AgBbEG567PeD3iijbu56EvB9gxlib9MJpjvlDF9ZB5ng6Y0QmU9ZaLX8NjuBxJ/SkuZfdFuWFga4D/10alKKDANhAuSTfZyp8wMza7P17m3sRTlSdi1YSHjvpvIQs50zXW4kIhEEWDuBaoDQuCcVwPQevCgjsbw6K8qNm+0OAwvFY/jiUwi6LphNcDyg8wZxpOhVy6XqqSvnZ11uCzc1DNuQA/2hr4Z1jyAKmOsFAdg4HV4Tic25PaF73RcAdSGKaGWpvJ1h7rsbWE1HflIOSoPmOHG2qsgKY324q+wUcoYGMZm73vuSmR/A9HkZ1WbcWQxEILBZO4cNe3TqCNNfEjf4co2qEfSgJctSzCT0pNn5RJy8yr/It3+N98zXx6eM/goKld/Y1forWp81vNW0PBwLLd54cQXZ1uJd1xsuZ+D9r02GpkY4nuQMe/rqnfGQojr5WpNBzjqybi9AVcdKndPvqM9U4IJT1QcP84gqvaTOTQkNo/zEN276mSjHZl990aN775b66Tio1mmtLekb1ZIfQiby3JZqaB3gzr83brZR60c3RIX/nE+KFYSXs0oJXOLB40iXegjIdcXiHq/RCO0KcbuMmHvRS/hQh9/aw9dHAwQ3iQRHrteaqcouh+c3BEg9J6s2FRlgP14WOrP9VbzECvNZBgUyk4SwYvCRJXywAqfsgHm3fykfu38Pc2F7A0/aKK5dFP/UsHjyU1nN9NT8OWiHzCHZ
    client_secret: AgBdPiD6822pgDXeEhoH+aQn5nDmzBV/frV+VMzkII/OKv49EmFUjJeEu0gCJLyd6DBhKY9lPAC8azr9zPLsUgqx4iLifAF9cD+6ePf7j4Y+U/OaXSe+2Li5dlD5SNxjdzZrGWh/LflXkRRl2oRwSehi2Pou5xn+aB4LWZrZQ3cf7cKQ2SZB43kuiqhwK6WP85BRzukylGLu4Ifkh5QxLV6+QybAbRME8DuM446aFp885cEjLpz2DqObJ1BWNHzG7UGLnF8+g9ZW1Z1SnRmJ2FmCQcD/vb/7EtANeNQd1uVfVK1vwDxLDG+aX3SGLPn3dOMmQP6KuVIdEbBNasS9HISOsS86yvNd421GPFi1+/gceoixu0NBbmH1uEFA9F8/8p8h7pDcb2/uDjODRLwXnNZ1XLJOWG5cO9MYx9rL11MXjdrL9aNeu/MAPmCNEFSaAH5asX52o9eLBBUvlAWk+2FWWd4vjnG0xgorqE2AP/oeHhp2lRPhQtMA2cn3nQEGa/7Itbnkj1O4Lj9Zt8q9yPNTL9aMmFfq1HtrQU5N6locSgYnBOLygli/KsjcJNJ+MWFvI1nZz+ixLtgXhUCC2RPQ5tf+bsdKXOUi3IBijV3AK7tN++qoUVLyy39wU6dVoyllBqiktYt6Yxy5PaohmTNaE6A7Em3A9lF9mHwx/P1Pq67yTCQkfk59N6LSu8HvcA5oJAdgCfN48/5LeLDdmfJlFxp8uumwSNisQqOiKJHwAQ==
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: portalgauss
    type: Opaque
