---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-registry
  namespace: jupyter
spec:
  encryptedData:
    .dockerconfigjson: AgBYRZL7LGvn8UES2AOmYVBWb8vyYV8qBi8uhQ2xue2mldSJvWPp/lD0wbcKGQWB4VQPhqjwtlWgWLcbUGx4kWpn4En21sLg8ZUVdwaF7i5pP6wVOd7JzmXyXvYrjAF95UU0Yr1WVFGdXcz6BWJOTU4MVLCRySBqywfRLFUaVvPIDzjKR4TLkL2ld62BYu9WMgTLHc6polS9MlDPVtV4OYrK/3xfUlXNFqqXMewOTNPe2SiZNyplzsXCo2opvkLx9SccimbUoRuXKM3ec1OoZiLw9OA5BNbXfWlXABf9hMVzTSFDJsjuZigfiGZ4O/6QEyho1Qmycki1FJwDBdTEmEgmwKczZsczsVjgj0CEcOXy8xv6PkkuwAaITOgCZ/ch260P8ZG8nyhDWaf0Jl8j8tc+uvPA9Y26KeBb3alM2z1ebJUev4j1jHbx2K7eWiWlFsh01j62ZE/Uysw1j+ZA8yvq3oxohpazQGbVOZ/P5AHO2lk822bq4sLtBB38ilhISCD9OAZV5Ue4O/zJ/bP5OzYBOrBzF2Bd4oMpdkz9FmiEkHCKVZb9qN/I9tKI5YHIrLxH4WX26UT4nMJRxjf3yJp4+d5k1xW3DKXoJK4U7sOpFlv0Ouk1E8uCtxMWupxbX9vqn9Cg64HTLR9v/x/ktgpKS3scNvMqGCbN7UG2SKNTUKbnLFi+lrCcMlCr3Q3XlJaQHa9V51qnywQqqZKhBZ36uB4NNacTtvfwdhB5maOkzrkE8gerAX9msbqLIBnBMpYxl01QNSHEUiaJ7pC0dRlhB+j7nDnILHYq3dmwh4pJ9l+6Dl3Yx/BiXC6PhyfNw0yz8EJA
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-registry
      namespace: jupyter
    type: kubernetes.io/dockerconfigjson
