---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: juniq
spec:
  encryptedData:
    client_id: AgAnVRIk9kxSAY3eelbkYWSbpJNYa9dxMN+iV7JHhst6XdDRNrqx7HbqQP2YbqqnNXDz23kPkOYi0R9T4ufpC+ANrmdJ48MBGq3QFfzU+bHZk4UfvwQmvyDExh+Ho7vu/nVVOzvChk2SNHzME++UdJ5DA5ncfLAilrKcO6z770W0nwtSmJX0QRsIRAUch2vMDbn77ORwuaEw9M0fc7aGN1/6H0tyPPC++zRV/tHNRk5xc37DZgDeKqFAVrVADpn/tKhHUAV18bC0BtJAWZ1JZHMPpOACxZWI/QZx6DULd+mSXHNMyBzPoVN7sBbW/U15lStN4rK99cMgGtb7sokNjB71497cLk0SQU+D+dDGg+RTQckAk3nNQ3da7z926CUxMxFE1cVG6e2itPeF9jY+KJ2Agd2A7uNfDXBg96eHoOpx0CjdX34bohVwoP5+u+wQt1tcLxFRMV3uNjzNC4+CiZJfBZeFcRP6U08K9jackvZXIG8CqTnD5H8fYp+iL0qkthCh8kEFW12QNkywzg8WwIQ/FbaiS3/CKpxpOEp1BzMpzvZq37NhcJpzlwi0/WKgscQTxe4r37smrP99kpbbsVxVfELWekwIP4+r/UKZSVAiilxgMDYDaacpdjBhe3wfQlV187hOTnAIT7t01lY8Pno85jQXGDyzRcRjfZFMYSt6+mWmaCH7p4CpXO/hudAc10dGemLSVcCQZVpSDtnhgertAsm7J/lXiefu
    client_secret: AgABONxgcImV6L7FNoLm0z05PLPi4mbyEAsLSGDB1x6Bjf1o4b+rKvVLg84TW9la+A98Mw7rhHVPZvsqJ6XsNghL+Ws+oye+PcMWJQrzD7YkyEmo30aw6GEl1ZBV4q4ef+MRtcirVWlm0eUOh25fnWV/dKLIUSMgqXyMtajp0QT79i6trUA0ORxQk307BlULFOu/ZQGBwvX4GQj4N80bfXh2LP21QD70/3sxsZD46koco4wCHJIAOAKvq63rjqTuqx4jFuYoikU/tFtu+9AOAnFi6VW7kOaUp078Pp9jRUx+GFKUAs7xk4wv6EouQtsLdAg4n1S6Kom3dQ7r3Xv9Tp0EbvoBiTo9YldG3oJ5xd3nMqy7qnSSXn6Wvupg8BFDX036a4a1SYp+mSXggzQfNK1zIuxngx96RV3Wu1O7bIz5DRMkpf+9ofs6fI//gPBtJE7xHfKGRlyUmEcUAkOgTKduiAPSZFw1UujISib6gYXU7gkauXxJodA18d4ka4FFucAat3qx3z6FFLlefN64h1tGJ1xGpFdDMEHiWN12i5M0x+nVbSTJyOX2be1qkFLitLCC6C8vmsdZRLgbYT212bKR4kAK2kbxtuJEintYbspxsUKq2vbJkdjR1Ijov2ZGOAnpiJ0KPVw/7ebYAXdybEcTM7NLZOQ9DB3pr/rxwj4JYOo1D27tDUdWpccPpEIjI5wJWGbQx8ktrEiBfZeb9feFuac8Zp4wfR2klTe7kEJmyA==
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: juniq
    type: Opaque
