---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: juniq
spec:
  encryptedData:
    client_id: AgBJj+9w1hvSFKJSNnNn48kCw4EYhk1y6V5PyZ30iXncgaEIdPZlTrv9O60ukW+wJ8pyWdk3YHu+Vxg/fGv12RDLE8DKpmps0B3vpRzqwtP0b3PziD6K8TCfoEyBFnDYkE2Rn0Zsbd4GAo3RWQzPGGap5B7C9/GeeP7Beq/MuH8wIjelMjVAbN8DObsR1ilRYaBrYWDFVn46x0Qza/eFC7Sa28bb53HyJMMibx0JWQM1X3hCPG+JrXK0NCw8c+K495Z/Qbs0WmmTpoc3iMFfIvUP+SwYshZiwlKFNrWmoTd156JAppCbAoVaCZ59sgWV6CBt/j4ZyIeMMYJwbsBxSpevqNjO2jkFVQ/oRGOdrHWZGexOWJ9y2f1Xn102Wn+CNW4x5PDai10Gr+aPdR2Dim93NJVgcVjVl8/NmQR45OHjF49WJP7gA7ckP2cup0ieAAhbmJCkDmPKodbBM63ufYRlat1E2qtgvLJqjjio81l9uqW4qBAt+cPLx4r6FOzpfQcX+MznhRt1OxnN8+o35hFm+sNhHOjS5eJp5klZCwmoRJ5I90yujvq9HM1qCDB/cr8CpdmdCt2puSAIm/foFIC98FKxbnCnWI+5sp4LdWD8OjspxuAyeH9IVUi0E0nAAXwy2K+wyszynbHsVysirdY9AZo4kJvySTWU8R3AgFFGrulNEHMT5kRNN2RmukBGl/ZKwpThON2WoXZk6e5wOab0
    client_secret: AgCbM7oRUGgJSSghTyXbuHfEX9gZPCwmpLu+aEO8iEVfPI7Be1RSp3A8EUdTheZSFEVdtJBPVwFMIwcNnpK/u8Mvf/pybQjm6qNUOzsBmpX3uLGp/mssxtrEhFerJ1TvPzkLKvWd/YGFF6AuZWqTgzI7E/C5bRComPV66h8TjOjKwbdxb9GzsPdoWhBBA3L5YsA4KW2w4aVSyW0LWdw0Xdrxq08dq5xZY1WeoYySu6yvyJ3iZZPg8PKGEScFFiuiWqmu4UE6KVaoSZ0N/Ol04Fld2F1bKZm/YnpnYvV3XdQADMELHpDZ4Toi647rKh5rG4Fqr/DmANkheV30kJEH470Mwg8wJrmaMXqKSD9MHuOtFP8v40AbEHcJZgN1B+vMD3NFlhuQZGx/IycieH0afJi5USQqbaB1aXB0KjNMNCv5NibAgnV6bKE8l49SQqi/hYz3uiAc0B8koqQIxfPCPamUVGwQnO4j1ZH5kSWUwUrnAPc2IKCZfmzDGt2gQLVC2mG9eKocW2tHVLiB+4QseARz6LYTwQ1p8qP36PbcI95u7I0UG6tpDQKqT/yNR89VVwxNwE2Mh0JqY6LtrQGEZJYYr7O/dLK4kMKbXdqg2Fluoil9h0453BkDQsrpAjkBgPBNP45IGUYD3QfmbjGcQLVI7zToF7fOQliJRh1/GER/Owc14oYzAZyCoEzEyAkI/bVd/8OMjyXm85AQNrIgcqds7cJ4ZZKABkBa5jVrAz+s+Q==
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: juniq
    type: Opaque
