---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: coeraise
spec:
  encryptedData:
    client_id: AgC0+mW3cF7Aq/0GTZls++05URAst96/jbhYlZB2G+vSLohrupmOBduyWjKLx5p/QgvrCzL1aw2cT9VEuHUhhytwiAPEnL+DE3MBinDRgrGcATSQiX9APPQ1f8wvL4JIATE9U3dK8X4iLzh4qI7Bb8DxhcOPek9fJxPXxfn3/bwRIsji+A9Nn7hDA+4u4d5f5ZSDpedtJr0M3l9EquKWqXUCr39elQOKCYV5LC4orVVMDbS5Cen91hU9EXXbYgKbWnmcFa7OCg6uNRlGm96cvvzhCKAb/2+eq5eDtglv5j76xY3TzgWN/zLiRJwf5y+lUtrMXO7ypQpij8+4URiT/xzMCzpsFDmgKrgzz/CIPrim0Gp8Isos/S62BBTkEAoBSRJvISbpkxYFCK8xsWv05Yx7adpOxAo5rLWFmp+H+fs5cM4laDqBonXvpcdCaVSUnN0XZqbw6AskUePuxx73PxhmdET45oKUTihuUdKfClaJWfr5cAmGSEu/gzMX3KY1weejVz1tf4cwCobbagWTQoNpBWg+iOUUyCB30gE6WQtULOhuxY64RCcyttsSVh0pqQgfnfemoC1XDx30+u52XIRzyWthi7QBZqgvIe4qgmEb5bxO4FtGMZH6NyiVcY4CGwIXOIS0A1oizJhCNiHyQIcVLgQlyphPaSROm7DeuxsnlC1/aVptzQ0cO+DXbQ/KNt/zQBJrbpPG7JDDVyolXCmx
    client_secret: AgAOs0W2MqBeNlbNqGRXJVxh7LFkExHZtqKzMEUEb+qGuUIK4n631Xxt0s7QvVl1SfZF5Iec8gnpp2rPj6tmycVDX7OECEvQoK0tvY0aUAEPRKSg6dM/Cki7P+zflb+8wIl10TmknNYqMvWLUjh9te5oQyIs5bSyxkFrtnVfQ7fcODNSfx5hJX3EoMnif32ss5ATbQaeol87HPTzKdciYeiNjAumkiK4DbBxhnqdgjePA5IOe2g0aZrk7emHF6BtyFcpSFBMGydD2K2bQHx3cA2sdvPcGgF8/E/2sHHpCeHI6/LHYnVbN6mQysM32idMLIX1ljse9PTrP1CIDMi9Vl7Q6HqthKcLDoXy0ruaSUh9hDmNOT3Xu8x8+OV6bihaKvkICiuaRL7CFJxe8fyMfczLAeXrzkh1id7WbRHryH73+6x5SuAirOKtiBMrchN/6xGsqEYI5aP/Yw35F+eO8r7NRzV/Lkm9buYy4aZocp8HrC8QG6uyZkw7U07G4S58caZzPqoYYOrhi6inkzP8tPk0wgxO+GNRrsinapiBAvmRGsqkq/Ol+iusBNXVRh0ulQmJRJcWKLLAxh1SAhugtOxSvvBf/fNSD8/eR9EP/fTr0gsRcRMXV0JR+L9QE098mHvVlULz2VnNQoyPyV3k/iBRXJogv01sNcMrHuhRH+kx4IE2e9v6fNyVQ1JJxeyAYmbPASqCi6muMqnfhQt3I/4tIBiZs4a1fetG9FGpiLs8WA==
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: coeraise
    type: Opaque
