- op: add
  path: "/spec/template/spec/volumes/-"
  value:
    name: persistent
    nfs:
      path: /mnt/storage/jupyterhub
      server: 10.0.94.248
- op: add
  path: "/spec/template/spec/volumes/-"
  value: 
    name: internal-ssl
    secret:
      secretName: internal-ssl-jupyterjsc