extraPythonPackages:
  - jupyterhub-datamountspawner==1.0.4
  - jupyterhub-kubespawner==7.0.0
extraVolumes:
  - configMap:
      defaultMode: 256
      name: gunicorn-config
    name: gunicorn-config
  - name: tz-config
    hostPath:
      path: /usr/share/zoneinfo/Europe/Berlin
      type: ""
  - name: outpost-config-ext
    secret:
      secretName: outpost-config-ext
      defaultMode: 256
extraVolumeMounts:
  - mountPath: /mnt/config
    name: gunicorn-config
  - mountPath: /etc/localtime
    name: tz-config
  - mountPath: /mnt/ext_config
    name: outpost-config-ext
outpostConfigPath: /mnt/ext_config/config.py
