outpostConfig: |-
  import os

  from kubespawner import KubeSpawner

  logged_logger_name = os.environ.get("LOGGER_NAME", "Outpost")
  c.JupyterHubOutpost.log_format = f"%(color)s[%(levelname)1.1s %(asctime)s.%(msecs).03d {logged_logger_name} %(name)s %(module)s:%(lineno)d]%(end_color)s %(message)s"

  c.JupyterHubOutpost.spawner_class = KubeSpawner

  c.KubeSpawner.image = "jupyter/minimal-notebook:notebook-7.0.3"
  c.KubeSpawner.node_selector = {"usernode": "true"}
  c.KubeSpawner.tolerations = [
    {"key": "usernode", "value": "true", "effect": "NoExecute"}
  ]  
  c.KubeSpawner.volume_mounts = [
    {
      "name": "nfs-software", 
      "mountPath": "/p/software/jsccloud", 
      "readOnly": True
    },
    {
      "name": "modules-3-6", 
      "mountPath": "/tmp/custom/load_jupyter_version.sh", 
      "subpath": "load_jupyter_version.sh"
    },
    {
      "name": "modules-common", 
      "mountPath": "/tmp/custom/load_jupyter_modules.sh",
      "subpath": "load_jupyter_modules.sh"
    }
  ]
  c.KubeSpawner.volumes = [
    {
      "name": "nfs-software", 
      "hostPath": {
        "path": "/p/software/jsccloud", 
        "type": ""
      }
    },
    {
      "name": "modules-3-6",
      "configMap": {
        "defaultMode": 400,
        "name": "modules-3-6"
      }
    },
    {
      "name": "modules-common",
      "configMap": {
        "defaultMode": 400,
        "name": "modules-common"
      }
    }
  ]


