---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: outpost-cryptkey
  namespace: outpost
spec:
  encryptedData:
    secret_key: AgA5n/r5R1nY9iAqjqoZKDjtdnz356EGfSzePYG8t75RbX3Ai5B7z6WntmNNy+N6KhENFpI3P4vncnt/Req+KUv29L6obeEdBZ5Vkch4wo4n5pLXC5d3/cKVu+qjEhsK9aH5NWNjZGPYy4Unk0pLo5IXQXGd/kLkhx/bj4eLYMQJ2mxk8kOK91FmKG0B1gEP6RF/4OQqOYOqmfvzpl0YRLdc7dEs+vl2HVCgLzHKSGVHd0xqgqUnKqE6Y24mQ57OSaCZYBHZiIoN7tk1UM6TpB5bvrADV+7XBcHoMh1z6QYVnxBc16Ix/PZi17A5SdlAh0J1EgLqGwDVtoUqll+ma5nuMaA8AuVrCOboVrsOOBCZCn5kfL3mOmPLnsPw81g5/PhKejVMs9f1bZ1lsfUTxxqBpxMy7tZAOchAKN/gLW/Dr4eC5GA/Qhu44bIE8RP12+RSdNo7/IMLaa9qX0/HUMqzJHGb8FeXPX+HeWyUthcrcwAgsmPekUymoDRa6QY1DayISgHUJVdbbNVGFtcU+ySlMu2mPdxShgBUUITx1acXupiihRMwbR0I1IUZDF0J6FE9m4dJkOhOGZxHlGuzf0dxWkA3vstBhFeZXCbJrN94JuIdQgb9R32mTo8Fqgiu+JQhJOhDbB2t4/Fx5RAevgGXAVToQXELe0f1N8lOU5cn7LTx6eBq2kaq4odxRIkO/uXZ2JYZ3DIiRHLKLg3hWHPbFY9fGsOuATvC1KkAhDzFEi0yOtnjH2YCnZtikA==
  template:
    metadata:
      creationTimestamp: null
      name: outpost-cryptkey
      namespace: outpost
    type: Opaque
