---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: coec
spec:
  encryptedData:
    client_id: AgAzGQoIi70yY5hWYey92fwPGdz/OjvCPTvkYotWV0LG36B2vX/K8mqzbxR0mQV0e7IPeQHTOT3I+ktLadQmDvWbulnB83ME3jRAO1d0fyqLRKIZTtV+Qidn0MPZc6RM2RZAFzPSbRqyYZDYWuCoGpZUUWVqO5cm0wiYcT4JIaxNyUqv8nfXkmW3d1ETwr43y+bYfMVLvMaaRukUqDKWIhyFPlUBrtYbUX8pQCp+QDDEq1ZBrFV0tP8P3K/Kj2r1lqkCQvs/xz6HmCqOR2fRoVU5ev+ZmUPzr9yOixps5uXWslDkbHuuI8QKzSbNQ6PsR4cW2arCyUEQLzkctOAay83kYsCcLh6OIAGXDPciG7ZIogwmqM8gBDsCcC55sSubE9sJ2m2EDG8GciCRcDWDo+GeMfNs7KhknWLM14YMBq2lun7nszdeRU9qzurD4yBXcu87mOv2DylHT5tEh8wHDURY63UTR6apUaEN66N4W5OeWCuHp8UlVddSNuTKAhvPXtAho7+Z2rrR7iOO/o3Cf2txgqFEhblGkjat8/aLHy9mSYBnVAAVD79mVK+zoRF8f3sjOIn+whTza6ngBJuDYuXDtb3UeLTk3n/BdpEhC5wrj/en1S1BqGYu9pt3DwOVpWs9BYcvryea0+eA3+i5lJgwSfMTq2S2Nsw4KTAHEToiLA0X7bgh18vLqdCTk2tx5ecPgJsiPBNfw64ffkwEyVk=
    client_secret: AgBPT1nzECC2a90sgXjaCCGIgA5+GTv8xE5/Edq2s7Rh4fW4l/JQbIPa162fSBxcqT5tEgKmpUqIdxpjev7wWofz+c8fJusu4yAOwQc8ED0YzAp62a5g3uA8osbVnSzi5lQ8J2e2Fu2i2pCsITeGEe77d5CKI63YsbQoH49vX2tnl7DtdpQnUbWZRuIJ95coNirJLWoihFsdPdddJo4vUz8rfXfjDJC7h9zco36uHdqHjgeWNvjELTE+nVWT8AnxTNTwMmC+Y652Dj0A0B5yMmsXd0qibTgWXCph4vq5fONYStxzVd/6pBbbVvc4V2uTqN/A0IabibkhZMnF++Qyf6xBFOjjDyL+wTbzwtEM5mkdDp8hO4UwD9KrxQX53othEoCsJpr0cF8kNV1aFeqJWpZgy2Fg9utV966advnt215mT1JR9NxpUafYFwI+O9JfmIkJcObqTQzChcafHJ3CPIYDPL9wIusYOUupfcZ9oFM3HbaylFS81EsmxImdmhcWWb2Ue4piA7oJMqIorK7jPEOFT5HevaSWn+LKIv1DruyTfilpvINh1+o9pUojG3Pdzvrl1f1jHsNDhLFXMSPEV7ODCp1XGDKLVo3z6qDB3YH/t2VDT0fnvpRFd4IpA/Dhf7qMB6iHhvsYhjJc4TX5TH+Q/fByfBsgcaTo3O+nmdYNLo9E/9AjI5XsQCCXlCp5h78U5AZfTaGWLi3TXUXvTYi7MiD0UH6Pqj8/TWAdlPMJ1A==
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: coec
    type: Opaque
