---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: coec
spec:
  encryptedData:
    client_id: AgBySqeDFRxlY4L4ICHzVzMiZMIZX1kN9tTWzX+wL9OeQJ8ZAD2FWK5JjTWNjTh59DBtOgtr/dwAKqYxRHkIiiQeQCHhcx26ndbxwj6VKgAM9yUomcSpH+jQWOsN4PuVpISirVZ8q3o9RxRe4j5t7Mk2pG6dFlzr0BnrmBL2vDWBFYMjODpkJ0PueqdQQeHMONR6N0pfOslOXz7nUWJFMJ8kjw9SU/2yyWsGXjvhHgU6NJej6KMOZdakoDEaZkrfgqKPWMV8Dr8E5NPVzb9Qi1uhUaBjPiE+7IiZZHNYwCwJcp6R/XCgxV1NhECXapGRHMnPz7UZVcRTwCyYhzhZduHAE96Ifg6GztHWv0oxmXm4X9BHMZDovATlmSMcAYXrUQmBSSSl5u6xq1Lps30mZJQvJG/RCsohz1HQAX2uqFPkmcsF50wF7hlZU6u6G3lt+eAcF7LR99wV8kdWqBIIDf9Le/TUtpHpju5PpRrJKOszQsHNIALS7LT8qcD8/mZpK7BLA6msQbhZQAu1w9CP26DkkZXXA61f5Gj3L2yu8Lk0A8ZK/MIefLd+WCfA5mRpZ3ktAFSnSXh6T+8ikfC3/mLtdVh7rrtn7omT9161CiEIw5BRIrWKHDRg4pJSyJdbeCKH7XjP/IoSaPval1Rbete/VMJmQDhZ8Fw/sZL/c8S81JKGzo0fh2kipHU9PvM+miX3qUiLuLJvvy+19RkOkf6wjs5ezd6xM4Fz
    client_secret: AgAkYiKWOeTSrCvPUe9nQ5inJyKzPvA75m08b9gVmqIy5rsZeAxArt0QUL0HDu//D1qA1ZrArMis/G70a94K98j+jAR9JM6lPWKdokMt7RlH43/+3i1xdSGrFXhbfFd3Sdo9Bm94U0rt97Mf155v6VSRI3gIfttcQarb5K9yCz82PxalQ4hLwvQfp0Eyt30KXIkMga5YimGHXJ03oaSs+natglNRe6qqpQ+HBqYmZnFe2oc9LEqTTs5/YrJCYR/EYRdoLgJNUQ9a/B/WzhIKcJqrHaPpTXBwXjd0zmRWmPtaZid1jYV9DNAsBvJ/0SCusiE7stpTtFeL/xRHD928sghkfrQYK6X3WfhRc/v27U9RJ22nfXE3erpvcwTv8hg9MPzN/N8txSH/tzFwT0JcyT87TMALHxC982XRnd1FMwxOla8r7OFBVJqQxAhwb9fOsh5moM+BIWGHoOpDB1t0nm65lWYpuD2rJRnshyjIy/hHIjpydaStEFbp+QRazXH0l3C2qqYJdf/sshMD55pjpOOqlkZNEnvcykj/bAmuhJoMGIzZILh9LWCiqg5GsrP4d/A8Jcj4gxs64LszfiBWBANybQYJgpbLVRsorO4TSoB3+Ea7xJKxJANvmWg6I7Fo9N1/9dTKA2JLg7n+CQ75U5X2hdJ8xZheAuZI1mbvfChhl6uPXh0NmEkCMo36dkK5caZgxfdhJuBSD+hDnpdBM++9BicT3DDK1MG+mtp2mitg4A==
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: coec
    type: Opaque
