---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hdfaai-credentials
  namespace: nfdigeneral
spec:
  encryptedData:
    client_id: AgA2bOY5AjQGEyEozegZHaVnGt+E2myaze6SuBlc4OVTPIF57XzZvDyeHQDhoIyk2+VRmhRbC3ChocjlfZCENEVpbPnXRoo78MYNQO+cF8hZeJtvq9TehsuytPpLkCRx14f1NcFfkRZDzCkvghOWVLcVtyEfxDFhc1pHunX+8/nL5qkeoxy4n3oOGVNXR1/GJs7XhuopuWjqIkyopUBqfPgtxS28EnMIrpEU7PAju3ikzR3gFGP/VXtSU+dv6/IDmwWYT6GqJNNKR7f6GTWAyyr8MJL3w3sXiHdMNhpprOfBAr3ETb5W4HIiJWIzMMP7DCR6EpryaiQkioVhNR1mlTtLZzjAUuKziuW+wXTRloHLEYFjphXh2Ze4xvHLvvzYispgS24mrnuwM6NXkfaTPOhhBx+aIKY9f+yRSoVPCBjv0kAqg38LH2XYJS8T37X44pyMrWTG5yL6oZWp3RazzI//43xMY0PN5n7qBeHrgFsv3DegmtEStq+FoX49ssiZMzqDzCSuqZlLPfHQ1H6EUTj0jfYTMuJqUYeudfF3ZwDwYJAWVujXznCdjd0QS+cHR0y/+L42Xh9l8BSTJ3UzoKhCmnHlGk8sJpF0ReZLLbZEMffKcIPapMspxmPfEbTuyuc9+8S9SGOwMVJs0yPnTGww3O1raN6la2uRmuE3amTCDCtrxuRil3cX5SoFXzq/l/cvjsHtjl1u+7eKJzj0DfQKO/dtvQ==
    client_secret: AgBBqMpSY00IwPWATSMfsZpg8FP65H1HVN18hT0EZc7tCU4SYfxhuVa9K5xsdI/RsxABRG6+EszGn7Pg4fcpEczWQI8s3p/vDwHBE4brudUYETYacRKumQIFRp+1QACwe8mTQ29T7E9kNnLNGRYyVi1siGTm4fi1vjkRnpuzmYqXjC6L2NMLbe8R//sWFeHksXVdpNxRy789XHmmSJzcXYjAoHNNX+KlSkoqf3Mooyal7JBd6U3YH9FmQRXhLaDGJwpRaUnwRZEvq1nZugbMAuXy5UjSo2R3oSBIyn4q8qnCIO7d/Y9lN58xYsVbem2dNeaJDqjA8HIJTEFq55QpLPk6YnpBZe0uP8QhtJh0QK5AmYZ9x+h1q7bTUMouAh+hXE06MgZKorMS+505HLI3G48UtgrbSKMhhWshpZDfkX4TKIH03hAk8DHG0M/g/5S6myNwVqspnt5h3c3EhutvlatXLkcXTv02DkbPWodP3TbwnjzAqwSfYm4cKhN/pG58YBPOOTONNSKYwjWz3rqI7FDUjqCDiwueej2IAcwDW4mW76suz5h1Px6T93xrIy6BNGjYkPr1R0dF4g83gLncr+NrpS3y1G0nZn6aQNh6XzPRg9nQHrvRwQWSR1T+IaPi7/1YsjDw4162WtQIVfdyPwQksERSCBeufiU2X5qZTDuv7xva5k4XFj8WMfi2IlfU4JI/5PwDG0YSOHDpiKESLItgxREcaA==
  template:
    metadata:
      creationTimestamp: null
      name: hdfaai-credentials
      namespace: nfdigeneral
    type: secret
