apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "drf-unicoremgr.name" . }}-mw
  labels:
    app: {{ template "drf-unicoremgr.name" . }}
    chart: {{ template "drf-unicoremgr.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  run.sh: |
    #!/bin/bash
    git config --global --add safe.directory /mnt/shared-data/git_config
    while true;
    do
      sleep 60
      /bin/bash /mnt/volumes_mw/mount_watch/..data/compare.sh
    done
  compare.sh: |
    #!/bin/bash
    compare () {
      if [[ ! -f $1 ]]; then
        echo "$(date) $1 does not exist. Exit 1"
        exit 1
      fi
      if [[ ! -f $2 ]]; then
        echo "$(date) $2 does not exist. Create it."
        cp -rp $1 $2
      fi
      cmp -s $1 $2
      EC=$?
      if [[ ! $EC -eq 0 ]]; then
        # File has changed. It's important, that the files have the correct ownership 
        echo "$(date) $1 changed"
        filename=$(basename $1)
        cp $1 /tmp/$filename
        chown 1000:100 /tmp/$filename
        chmod 400 /tmp/$filename
        cp -rp /tmp/$filename $2 && rm /tmp/$filename
      fi
    }
    cd /mnt/shared-data/git_config
    echo "$(date) Compare configmaps with current files"
    compare "/mnt/volumes_certs/certs/..data/tls.crt" "/mnt/shared-data/certs/unicore.crt"
    compare "/mnt/volumes_certs/certs/..data/tls.key" "/mnt/shared-data/certs/unicore.key"
    git pull origin {{ .Values.gitconfig.branch }}
