apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "drf-unicoremgr.name" . }}-certs
  labels:
    app: {{ template "drf-unicoremgr.name" . }}
    chart: {{ template "drf-unicoremgr.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
{{ ( include "drf-unicoremgr.gen-certs" . ) | indent 2 }}
