# Can be removed, once Unity was updated and has it's own two fa setup
secretGenerator:
- name: coeraise-twofa
  literals:
  - SEND2FA_CONFIG_PATH=/mnt/shared-data/git_config/send_mail_config.json
  - TWOFA_SSH_KEY=/mnt/shared-data/twofa/twofa
  - TWOFA_SSH_USER=unity
  - TWOFA_SSH_HOST=zam2041.zam.kfa-juelich.de
  - TWOFA_REMOVE_SSH_KEY=/mnt/shared-data/twofa/twofaremove
  - TWOFA_REMOVE_SSH_USER=unity
  - TWOFA_REMOVE_SSH_HOST=zam2041.zam.kfa-juelich.de
  options:
    disableNameSuffixHash: true
    labels:
      app: coeraise

# InitContainer list in hub component:
# 0 - prepare-shared-data
# Container list in hub component:
# 0 - check-frontend-files
# 1 - sidecar-nginx
# 2 - hub
patches:
- target:
    kind: Deployment
    labelSelector: app=coeraise,component=hub
  patch: |-
    - op: add
      path: /spec/template/spec/initContainers/0/envFrom
      value:
        - secretRef:
            name: coeraise-frontend-git
    - op: add
      path: /spec/template/spec/containers/0/envFrom
      value:
        - secretRef:
            name: coeraise-frontend-git
    - op: add
      path: /spec/template/spec/containers/2/envFrom
      value:
        - secretRef:
            name: coeraise-generics
        - secretRef:
            name: coeraise-twofa
    - op: add
      path: /spec/template/spec/volumes/-
      value:
        name: internal-ssl
        secret:
          defaultMode: 420
          secretName: coeraise-internal-ssl
    - op: add
      path: /spec/template/spec/volumes/-
      value:
        name: persistent
        persistentVolumeClaim:
          claimName: coeraise-pvc
    - op: add
      path: /spec/template/spec/volumes/-
      value:
        name: custom-config
        configMap:
          defaultMode: 400
          name: coeraise-custom-config
- target:
    kind: Ingress
    name: coeraise
    group: networking.k8s.io
    version: v1
  patch: |-
    - op: replace
      path: "/spec/rules/0/http/paths/0/backend/service/port/name"
      value: https
