- op: add
  path: "/spec/template/spec/volumes/-"
  value:
    name: persistent
    nfs:
      path: /mnt/storage/jupyterhub_portalgauss
      server: 10.0.94.248
- op: replace
  path: "/spec/template/spec/volumes/2/secret~1secretName"
  value: "internal-ssl-portalgauss"
