- op: replace
  path: "/spec/template/spec/volumes/2/secret"
  value:
    defaultMode: 420
    secretName: "internal-ssl-portalgauss"
- op: add
  path: "/spec/template/spec/volumes/-"
  value:
    name: persistent
    nfs:
      path: /mnt/storage/jupyterhub_portalgauss
      server: 10.0.94.248
