# Default values for k8smgr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "k8smgr"

# Allows interactive start via VSCode to debug code
devel: False

# passed on to Django as DEBUG env variable
debug: False

authoried_keys: []

labels: {}

deploymentNamespace: "userlabs"

tunnel:
  port: 7002
  user: tunnel
  host: drf-tunnel-ssh.jupyterjsc.svc

jupyterhubs:
  default:
    host: proxy-public
    port: 443
    forwardService:
      name: drf-k8smgr-jupyterhub-forward
      type: ClusterIP
      port: 56789
    remote:
      scriptName: manage_tunnel.sh
  juniq:
    host: juniq-proxy-public
    port: 443
    forwardService:
      name: drf-k8smgr-jhub-juniq-forward
      type: ClusterIP
      port: 56788
    remote:
      scriptName: manage_tunnel_juniq.sh
  eurocc:
    host: eurocc-proxy-public
    port: 443
    forwardService:
      name: drf-k8smgr-jhub-eurocc-forward
      type: ClusterIP
      port: 56787
    remote:
      scriptName: manage_tunnel_eurocc.sh

gitconfig:
  branch: "k8smgr-dev"
  secret: "jupyter-jsc-config"

secrets:
  keypairs: "drf-k8smgr-keypairs"
  passwds: "drf-k8smgr-passwds"
  databaseGeneral: "postgresql-general"
  databaseUsers: "postgresql-users-jupyterjsc"
  tunnelpasswds: "drf-tunnel-passwds"

extraVolumes: []
extraVolumeMounts: []

image:
  repository: registry.jsc.fz-juelich.de/jupyterjsc/k8s/images/drf-k8smgr
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.4-2"

imagePullSecrets:
  - name: gitlab-registry

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 443

servicessh:
  type: ClusterIP
  port: 2222

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/whitelist-source-range: "134.94.0.0/16"
  hosts:
    - host: drf-k8smgr.svc
      svcName: drf-k8smgr
      svcPort: 443
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: drf-k8smgr-certs
      hosts:
        - drf-k8smgr.svc

loggerName: "K8sMgr"

gunicorn:
  processes: 4
  threads: 4
  timeout: 30
  maxRequests: 100
  maxRequestsJitter: 50

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
