---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: outpost-users
  namespace: unicore
spec:
  encryptedData:
    passwords: AgCfyBRqTI03XRW47EpkM8bt4xAOEEQi+V5OjgjUMEitoNfYhX7P6JiIMo2qq2yAavZwiJ8Ug/ZPvozFWX4NLBRAejVQZcU6nBqmiowACiFJW87PlilCAIRAFHCOtIjdWMDnUXcY81q4mn1zTAnPBZ/aTnPMGyw1vEKVVG1puisSZuy2NQL2w7exWQqXHubk7ZYE6xlYALRN1gtUuQE+PcJNV1XxHXDbCbBgy2apOKxDZMDAzdW1GfF2JHH0WGhWdDbZCjz8cMSQxotaolL3YSITRysUYqN50OX42Wos6GLoVykKyV4gSJHVVA5QaM2kDlbIs2JiE0dGWDnQ9R8XhEJ9TLgWnLX0JL4wyvhR7lOBIKrnCfI9MqTsrJAhHWqdjk/VMo1RJqGmT4hBXTmsKRiVeq0hBRS/s3LWgCKkokmVKL04IYWM5ZrvCjEBCJ49DkenwzeIKP/0QUawtQ8zkOzEVleETPHwMJvP6WFnUh4nM34x5Z6hp5cL2fWTETFd0SheWjzX6xL0LqBtmYOkE0GR2+iaKIxz76HBvCPk+mFFUao79sJd8q7+Q/bv/mJtNMyvWsiKiYY58+9zeiAUf34axVH01SK869AeLkNQdn94+VilT9/1IfMGZu/umLOrYvMaiKVJRqjl+qHcBynOuqeclQcmT9hHmJgXb9hTXHiWp8MoDkYYYrXlRoF7etSmRxDpR2ZLSIuvnKp9OAWG7naj8Va57IPYop5jkWll/PDX8wkJp2I8yUtbVTP9Mb40VSuy7TtdUtfKaNl7SFTq7/whRQw2hp5yEnLX23IvxwxPRoU7pMloevehSDMWtMdT3auNs3RNHmI7gZGqTa/vWltQ9spkTSbj/uGtcwFOKpzSprSr4GcfQeas+j8j2wdb1QAF3kB/d/gP7AjIhFt4AqVHR/Gis9fWo0PAfnudjzMLCSDaKbTHFDXnGHkcJzJBV0jGwO69zZb3q7pvgoqAoHdSThNsqp8TY725ccbeG97X+leGub74AzQVPDSxe98qMfGGHokLy2ud4wtVtvWVM+IcRn0=
    usernames: AgChakoUYrCwjDheVJgXjTHuQboALIZjO1rbMJal8BWwSCTK7AfLeleAgNGHXo7+f5w8cVr6zScOwM9HvmVvIPL7XI56OPDMefl97gJ2FatEiKOzU1Njxv13o+QZVNDBb3hSmVhRjFWB29W7YjZDPAbKHXnWqTjj0HJKfgv5VoaVYwgyCBxaNu4l8FFASCsSqAm/lQTA1CQBAy5Af5yXM6pTrJiGbY6+vz9OUoTLcLNT3Gi5uf1wtuEAUZuhQuE4Gyn+e+Gvse/1nl6vEbH1jmQVdoWQZOjfJ+06V3DmBdXDOJ9Tme6WyzwJs8j9/8hGFc5ynEiyWxbcPXNcGx63/WVbF2b6d2gLHUxWPJQrPQWD86wyIHK+/NuVrPlbthIHISAguUBVz+p8z/KcCvWeLJPAYfR5k+Ff3yGk8p1v01hzLl/BCwN4nUB5c8rdEo8RZhafuTzX6Kikt3uk3VsXRxc/B4RqOmIwsrhyyuNnlotGx8atTlfkyODqVpnVRdf1V2mGkdG210pbXAdyAx+9mq7HznvOOk39MqkcGjuf3TMW95q14OnrSbdozjT7Ya/uQO9pmKBODdpuXhD81ekSW8aP01LpWUsGX1Yha4pmWtixjTsTNk/eIjIJa+Wq2RrVMnpVSWRUbl2y5TUulvM08FD088N1INEHGSjBkkz+FqTR960RHWPkktcvDsuEFvAHXpXNZTfUu7RlTLMYika1kbbLZJOZjf0HLGAYkXI9bhJAg6PPUWSUkyXKJ41K7X/JK4izWA/gvKWwLwyrxMPU3Phy
  template:
    metadata:
      creationTimestamp: null
      name: outpost-users
      namespace: unicore
    type: Opaque
