alertmanager:
  alertmanagerSpec:
    configSecret: alertmanager-rancher-monitoring-alertmanager
    nodeSelector:
      monitoring: "true"
    useExistingSecret: true
grafana:
  nodeSelector:
    monitoring: "true"
  persistence:
    enabled: true
    existingClaim: rancher-monitoring-storage-grafana-pvc
    subPath: null
    type: null
ingressNginx:
  enabled: true
kube-state-metrics:
  nodeSelector:
    monitoring: "true"
prometheus:
  prometheusSpec:
    evaluationInterval: 1m
    nodeSelector:
      monitoring: "true"
    retentionSize: 50GiB
    scrapeInterval: 1m
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteMany
          resources:
            requests:
              storage: 50Gi
          storageClassName: nfs
          volumeMode: Filesystem
          volumeName: rancher-monitoring-storage-prometheus-pv
prometheus-adapter:
  nodeSelector:
    monitoring: "true"
prometheusOperator:
  admissionWebhooks:
    patch:
      nodeSelector:
        monitoring: "true"
  nodeSelector:
    monitoring: "true"
rkeControllerManager:
  enabled: true
  proxy:
    nodeSelector:
      monitoring: "true"
rkeEtcd:
  enabled: true
  proxy:
    nodeSelector:
      monitoring: "true"
rkeIngressNginx:
  clients:
    nodeSelector:
      monitoring: "true"
rkeProxy:
  enabled: true
  proxy:
    nodeSelector:
      monitoring: "true"
rkeScheduler:
  enabled: true
  proxy:
    nodeSelector:
      monitoring: "true"
