alertmanager:
  enabled: false
grafana:
  persistence:
    accessModes:
    - ReadWriteOnce
    annotations: null
    enabled: true
    finalizers: null
    size: 50Gi
    storageClassName: null
    subPath: null
    type: pvc
k3sControllerManager:
  enabled: true
k3sProxy:
  enabled: true
k3sScheduler:
  enabled: true
k3sServer:
  enabled: true
prometheus:
  prometheusSpec:
    evaluationInterval: 1m
    resources:
      requests:
        memory: 1750Mi
    retention: 7d
    retentionSize: 50GiB
    scrapeInterval: 1m
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          volumeMode: Filesystem
