---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: jupyterjsc
spec:
  encryptedData:
    client_id: AgAVKknmsDYV9JSSBLOiaByRZarCw3Ov8phxsMOWEg7MvxKY9EusUbdt2zow8yBgPFYv/d8pbETenRHE5dvdI0NAt1c784aBbGYYTRGBC6OOuy5siIxt/iOo8w5SFA0hCOSEmcrARcTohO3vnDuDNlQIugp2xPd/y9nCGZhforZrN/YXVOmfqyYIFVDjECaGofQhN6l6gT9FSbMROv44emdxntKuQVq3on/pdFtaO6XhUqw0UZKuH+lZR0phI0bvlAg2oCh7jEa1Y6p7zyVUSKEhr/YG+U5He0HgPXf0GhQeGgaqkmkZ4ThJ8Y9CN1oGakaskBrOvMSlIarl5jy+UYteRLh8hjEpuTP9bK54QDvlq4dxRyh2wGH/uW6UcDJvuW1gIzIPof2uWGiHLEOlP0SpzmcrYeIJ1nQWNob3N70wZ6rdllNXjZjmKBRYf+1Cdeu/vUYK7sIyaWLXW8XaSmUR3MDUBHfNCE5uGHt35RoegzIsws4kvDueUjzzjgA3aZNk1SiPiSbmDX27BXTlZeT43qseG+yCmFP843E8OV2FiBIVoBCzvltAN3N1dCqGZjAzhQDTMIWKfs45IJXvdnyfZDdFhY6q9+Dbh+7VWad6SXVWR0bpPA/in742D3F7nic1RdQ5QQMu9aoE3hP2fGdmEAYTtpHq82g23VW2Xdb0VFLbPlGzYUJ0rLYchB5pCfYpfBMuPMWC0rWDIYlsnUrOCcADJijdOTSj
    client_secret: AgA+iApqA6berep4h6uOzEBjuxqVa/NQUL81cHOAuzUD8QVkO4fUOI8NZSlw/ki7OBons3ncm3i4O7LjDRGFLo7RvHNghBLPXkdNFAG890XvzZBR3YT37Ks8rDH4MgliAdskBP4wc3sNSsQZWHAGLAXevef5RJ6D0Q5OMkwMVNa3hS3tYlUPTAIpKech5kHPQF7MiGanSGxst8usWAeTE5O5Lbn3D0erXsHTVBEkR+B94a+Gp0SqoJP4IXT8JSn+m51W7BLmn/RMcl48leLQ0DTMsvJJHzn5Rh+n7X9aO4qVeK0t19kY4dZFUVpLmXgyEsRYATwuISSTtVbcihQv7RDTE7JbKLYc6f2cQ2kOJFXLaF8S9UeJ7lkqgZgKRY2O9LhBbQ6GQCZU9JTMGgyvM7GijFgLUqKXucjAZ8b8WDCN5Spn+3+gWnMnWXCtNmL16nTacFISo4nSXP1Z2PaXIqt7Q6zG3TAC02038QZrs+o3EDvrr3iMfZ31XVnZ3Z9ZBwJnTqCIZWLcRW8UmiIQIdTxUKuBcVABQv6Ni7w/hH2a/FutjryhCwsP5xG3ciGmtpCEZksqUH99f+Ui1pzZS/g8CCX9fO5ymEo/VcXMOS31l2sIqJd+PBlscuMn/gqsEscP1+1xjjLSCFDymZ0Jwrjad34ezgpm9ThNK+19ID+ziP3zZJEkafMCcyuaQ951vmRS9BfDn3QTn7vCeAvP87XT1MzXExqCA3Jr70pMKlPYeQ==
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: jupyterjsc
    type: Opaque
