---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: jupyterjsc
spec:
  encryptedData:
    client_id: AgBFoOkENC7dvTvaNRyCQsAjZ2zSwS6WWxQ/PL4STAvLV1mrZljN0b1bNnNW9yu1zCVpbBNYu+DkGw/lpShD4QA6gXXZuAh1+ofU47lvjsHN1jRivXeZktMMSZ7ZftGLxamuX/axArBenppf9c0S4CfDUZ6uHuL2AWEhaKh4GwoVFbdXXUZuXr2m2x29jYTL/10uHM9zuacgUa0H8u7HMfklG6ZVhVaJWJ6oj1fUo0BEcXPCl2OofeCxq3iFXt4Xag/tjTKabaSNNTjs//8bhYfzEMmi24l5r+M2sWFXT3mOMB5jun031hVNUSFrjI3+xdqHlcfewYygfKEvxMVxxQXrY7NiUyqvza9zz0CH9zNDWtZQVcJjmUdNbQT6fDcNONJvMFth2QUNifFuKj6/VulO47V4kmpfLsLRohgj245l1v8wuOsTf9iDjPxqrjyvLaLN3Zq2qArnM4kJBzImcBHAeDzRaOiGUCGgdZfKpU9Ak8Y/feivehhZjO32ZGsy1Yoirzb/KWQTH8/FuAANVstuHwnvDgf/6a9P8evF9b33uIs1b9wkD7HAzixpXdSsYepzGuU58p7vb0JGqT9P5FOMsLu5sTbKqZ03B7O/NesEIJDwBN8vhCgr9ggTEX5dsN0swRs7HQ5nCFmfGe88ArYh5d+0UPcHnK4HYxT/B+Mm9tmRTH2+vJwg60qiWFN1BCzfMWaufPBhfb2hkEqtouvBCATp2VI=
    client_secret: AgBtnm04z2766C34mhZNqtmCoS7EzfPpVMUsFlscy2VHOfPx0RnzJfBd/fDbq368jaYX2X8Qcsuj9yYCR3uk/vgbKDRApv3PHQt6G7lKD+n8eC80AuqaWYoxc4HpE+ZgkeAWb9Ojygzymia1bVDpA364WAreXwGR0Me2DSHiOlZJS/SGKQ67dmSxgvaESsYONpvgtBU7jBM75B3M1NcmOFmBni9SBn6WZaKflgVI7MNohDbeUC2zaDjl3KTMG4fxPQK9XP78v3mtZxgS3OoqaY0LkDNTatasrthyKT76WhMjNLRqetWcxMvh9lFMg4WSn9NnE9TvFHZl2tfdUjRblSG0MEvw2px9JC9JGDdpMkyjNd97nOhBDAT+L8eWw7GE+nhveebylIr1nOKg5QaPkFP6ykjh+40CEo1JxcxtzJEtDTL+MkMbDk9ZnYEAGjT3KOmC6eLn7KJHdBpKD2NghJznxAJfk+k48O28xwFEx5FZZGkJRmjoYlJme8ZRIozdWebEJyRiFjGtJhOTDzmlGWCCeYvnvu4rQpFMRy29CnmCHgpX2cBU97IaI6Loo9CU1O7jBous6qOhfi/L3JjVgWdD/EtI93z09S/nkl2J0w0xvV97LkEOsmhPwM1pxj6SKUpECGNjTzLrczMEgPUI89Hh6UzSXcPic2XYXlKTj5cKmr7SS5yUDU5AhcoDjLYJngjKtJxpF0MuhzVEtFgPxYPSb/NTOmah6OrHb5AVVzmK7g==
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: jupyterjsc
    type: Opaque
