---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: buildpodsregistrycredentials
  namespace: binder
spec:
  encryptedData:
    config.json: AgBxuW1XkaZwjcKL7J3v843JW5q6TENwZWisB6+BR6kaPkBEIp2xn1eyfshQt3jWZ0/KMfMr2u63mXc281odJLko+2JfbhLN7biWV7YwzpHiBysZaMa6lIj20LHBkc157AZlvbTL061/XeORgKBQywYnhBCJeIvEdpaRQUSW7JTtSzSA+9kzPruUX2GxkQmBDAMaTxlRcLrOvVb5YSPBvajJtmplqxUbXxleeAGaMbHIl+H+vBSLck2hJcVLEFPM0Zi46Jw8NanV5tH7z77vntIt8iXhsqlXR9IZF0by0c7JICunUyMjztpXGjWAlwj5URIX0L0ft6TDYcc85AG9THnOXzzlSu8nPRMwqK/yQRwP+awcYhyYXd/yotPMG8zvcMn20cGmiCmrHE+E70Bhv+iNIcUIK1tGmf6leuqni1tI1epQU4rxW1GR7Sa2b8NcfdQ3/+QmIGzIL7Wr4xAqFjVtGAq1tDkUxOpaTLJnchbFNJAjTu/8JIRvAX8exhMfMzzvOv5L8Ixokv8DKDMZ++kgueyzy6p12wqTzDYPxGZ8h0U/HZAsxAeKxGM+haDXfD1ZsSaS9YkV4//njxXIFl9/53RjUOAEF5ZFocfT7Q4M4u7p2NgcM/SFyfg0m+utEhp6ljzppXqAJKqSpaJqbFjW6DxUf3YRfUwTaPrsWt+mAjybL3Yfmyw7nz0aQwQiRTiVY8k7DRsx1byEuykS1rTU/kLFReadojZBr1qC4XSmlwUSpS84HsT8qbhrdJnFuafOl9nqdrglmmG2cpKAKC4jpvtyb3rb/ytKylfClZhNTCH2rTlTLNT0b1QO6NkLG7YSdsFVKukUNWSnZ8foAmTXQLyanrsVjL6j5SQBaJkv3Ky4uLA1xa+0BE8/JnroFfZ+hAOfqcmYtqiwtQ==
  template:
    metadata:
      creationTimestamp: null
      name: buildpodsregistrycredentials
      namespace: binder
    type: Opaque
