---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: buildpodsregistrycredentials
  namespace: binder
spec:
  encryptedData:
    config.json: AgBCxZ8r4rcMDhMvfuxCK8bqDw9pXS7Dse5c4yf2RQw4oelOym9XNFLdnjckSihghnxsGJTSXCO18DKzQRZjeAjErjjtAo9LiwXSDZWwSa9qOuMdJ+ZGuQn9rJqR1CLUCMM0RI2Az6VVufZvyGuXHKhOEB77xivVyGDrHa/C4a37DAqODOtM64CCAh8gLo0nbf2tqCQu+c1Lzo3pmXUc7fv5RfMQrUxg7aySBYyQWzJqT2Uft7HzlZFCnFX5GqpeYWGQrDio5gWe/VUnvrBZlr3H6hrOMfzGh+4etBxNCnpXK6CKcZ0qFlnObDaq/r8z77Z/NGNf1sP1FW5O7d/+Qr+Skn0iqz1dh7oKwAHYoh7nQ9qtMFQ6wfelXn53YJQ2EiKm5+fLXXLYFbhSaJz8IAvrQfWsc32l9oUrUH0eE5hJbq+NvxfNCgAH7vkLfM/q28fPo4s2HBei/n44heSx9LmrCL197UtxiCWrFwgg2sIkTIOFarGlo62cpFslnSqbYd9V+Z6zS0UtpEp3B6GscgElkiv/f0GTdQU53lWYa9NwOHPURXF/fswxdLZBnzihUzWD7CaE3QrWsayHDNn2e4C3wY0ai9DN+2acXooDHOtYa8HyQ0kjs7JCxRF72CJf2kQbzPsjUk4vPkzGvQczulB7Wa+vyY7vBvP2G9zsVFXiENhlyf8tjLw7E0b0XzQyTdQd5QJ/J8F2jwEeBwIiZs5y5HnM/kUDyFQnEAeowVVK5Hr/3PTiDjsvP/mJD8/2ZdRjSh9QvJJHA7lQ1B5qwokvEyFroxbTCKyYOVPjIfynmAAgDAP3WalIZkjTwHe/NP+ZG0nm5iAPnlzOcs87psynP7DQb0fp//LWLQk=
  template:
    metadata:
      creationTimestamp: null
      name: buildpodsregistrycredentials
      namespace: binder
    type: Opaque
