---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-registry
  namespace: jupyter
spec:
  encryptedData:
    .dockerconfigjson: AgCAymEpRuk+Ckc+aS8SzECNIm7VDYTbs+vb1mogPKERCq7CI1+uVPEyALSGMKr5qTeVMgy5j2skk2m/sp3flHzwPD3sn+cvSWImkSfCnVoK9r6nuAUPdN7g3+nZFS2mV2TJMXnkH2f0slyG7hJ5LLn4tbMgjIZa/jHmieCz0SFA2kqQWW7N0jbH4Hzjs7guftU2VtG5jNMqDexmv6tx9qX7b4H7QGgMK8VZejrv482JNAB+IqhA4ozoEn27KWmo9VMXdc2vzCIuGcwAB/aRV5h21EO7uLFWVLN0uwlnpGZpjwPL7uokE+qSCRQoUyW/jP12MCyE4zVpU5UwdoC8o0jUBpPZPXs+j5R5H4ncL5j08lJtihd5iYHWVUAVVy12mYTkDkXfFpqmwbsHm/GQ9sbzM+kdPcr3rnbkft+shf3QdaM2Is0Cy8DfV9SMwof7u/JkIcmJaOmZNNP9N3Wppd8F0fYV6m+LCaexHLW5mhOh4GtwiRiYSgXu/pbwetbLMyFBEWKvXFBOM0pTrDsc+kd1MsRkEV7Zn3LYkEt9yOMVAf+DBmMoE+W5v42IhwLogz3u8jy2by9SOzFWOD+8/brS1wqS+2MGfYIRoGBJi6tqr/6eqy6KMSzq47gRAlPICD45+JJCSIU+NX1N6+314KcRPc3c6tSxpPn4waVh3u1n/E765EZXFOsJ+9RYnbg60cwQqL7SOvJjezeiNIQn/7qJ6Vog4vF7mB/9KondZ2VwQG+F6tWFVkCQNZYjKusEFgqMGONGBcr071Mx/xPRc2VSFcw4oq3qhsA8NmaK0dzuH/Dw9nuusM0jglUWrqpvPOZj0Ax7
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-registry
      namespace: jupyter
    type: kubernetes.io/dockerconfigjson
