{
 "title": "JupyterHub Dashboard",
 "tags": [ "jupyterhub" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "hub",
    "query": {
     "query": "label_values(kube_service_labels{label_component=\"hub\", namespace=\"jupyter\"}, label_app)"
    }
   },
   {
    "name": "proxy",
    "query": {
     "query": "label_values(kube_service_labels{label_app=~\"$hub\", namespace=\"jupyter\", label_component=\"proxy-public\"}, service)"
    }
   },
   {
    "name": "system",
    "query": "JUWELS,JURECA,JUSUF,DEEP,HDFML,HDF-Cloud"
   }
  ]
 },
 "panels": [
  { "title": "Hub usage stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running servers per system",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_service_labels{ \n    label_app=\"$hub\",\n    label_component=\"singleuser-server\"\n  }\n)\n",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(\n  kube_service_labels{label_app=\"$hub\", label_hub_jupyter_org_system=~\"$system\", label_component=\"singleuser-server\"}\n) by (label_hub_jupyter_org_system)\n",
     "legendFormat": "{{label_hub_jupyter_org_system}}"
    }
   ]
  },
  {
   "title": "Server active age distribution",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(\n  time()\n  - (\n    kube_service_created\n    * on (namespace, service)  \n    group(\n      kube_service_labels{ \n        label_app=\"$hub\",\n        label_component=\"singleuser-server\",\n        label_hub_jupyter_org_system=~\"$system\",\n        namespace=~\"jupyter|userlabs\"\n      }\n    ) by (service, namespace)\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Number of users with running servers",
   "type": "graph",
   "description": "Number of unique users with running servers.\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  group(\n    kube_service_labels{\n      label_app=~\"$hub\",\n      label_component=\"singleuser-server\",\n      label_hub_jupyter_org_username!~\"(service|perf|hubtraf)-\"\n    }\n  ) by (label_hub_jupyter_org_username, label_app)\n) by (label_app)\n",
     "legendFormat": "{{label_app}}"
    }
   ]
  },
  {
   "title": "Daily Active Users",
   "type": "graph",
   "description": "Number of unique users who were active on JupyterHub within the preceeding 24h period.\n\nIncludes non-server activities.\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(\n  ( jupyterhub_active_users{period=\"24h\", service=~\"$proxy\"} )\n  * on (service) group_left(label_app)\n  (\n    group(\n      kube_service_labels{\n        namespace=\"jupyter\"\n      }\n    ) by (label_app, service)\n  )\n) by (label_app)\n",
     "legendFormat": "{{label_app}}"
    }
   ]
  },
  {
   "title": "Weekly Active Users",
   "type": "graph",
   "description": "Number of unique users who were active on JupyterHub within the preceeding 7d period.\n\nIncludes non-server activities.\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(\n  ( jupyterhub_active_users{period=\"7d\", service=~\"$proxy\"} )\n  * on (service) group_left(label_app)\n  (\n    group(\n      kube_service_labels{\n        namespace=~\"jupyter\"\n      }\n    ) by (label_app, service)\n  )\n) by (label_app)\n",
     "legendFormat": "{{label_app}}"
    }
   ]
  },
  {
   "title": "Monthly Active Users",
   "type": "graph",
   "description": "Number of unique users who were active on JupyterHub within the preceeding 30d period.\n\nIncludes non-server activities.\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(\n  ( jupyterhub_active_users{period=\"30d\", service=~\"$proxy\"} )\n  * on (service) group_left(label_app)\n  (\n    group(\n      kube_service_labels{\n        namespace=~\"jupyter\"\n      }\n    ) by (label_app, service)\n  )\n) by (label_app)\n",
     "legendFormat": "{{label_app}}"
    }
   ]
  },
  { "title": "Per system stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Active servers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  kube_service_labels{label_app=\"$hub\", label_component=\"singleuser-server\"}\n)\n",
     "legendFormat": "Total Active Servers"
    },
    {
     "expr": "sum(\n  kube_service_labels{label_app=\"$hub\", label_hub_jupyter_org_system=~\"$system\", label_component=\"singleuser-server\",}\n) by (label_hub_jupyter_org_system)\n",
     "legendFormat": "{{label_hub_jupyter_org_system}}"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  group(\n    kube_service_labels{label_app=\"$hub\", label_component=\"singleuser-server\"}\n  ) by (label_hub_jupyter_org_username)\n)\n",
     "legendFormat": "Total Active Users"
    },
    {
     "expr": "sum(\n  group(\n    kube_service_labels{label_app=\"$hub\", label_hub_jupyter_org_system=~\"$system\", label_component=\"singleuser-server\",}\n  ) by (label_hub_jupyter_org_username, label_hub_jupyter_org_system)\n) by (label_hub_jupyter_org_system)\n",
     "legendFormat": "{{label_hub_jupyter_org_system}}"
    }
   ]
  },
  {
   "title": "Active servers",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_service_labels{label_app=\"$hub\", label_component=\"singleuser-server\"}\n) by (label_hub_jupyter_org_system)\n",
     "legendFormat": "{{label_hub_jupyter_org_system}}"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  group(\n    kube_service_labels{label_app=\"$hub\", label_component=\"singleuser-server\"}\n  ) by (label_hub_jupyter_org_username, label_hub_jupyter_org_system)\n) by (label_hub_jupyter_org_system)\n",
     "legendFormat": "{{label_hub_jupyter_org_system}}"
    }
   ]
  },
  {
   "title": "Active services (try filtering by system in the dashboard submenu)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    kube_service_labels{label_app=\"$hub\", label_hub_jupyter_org_system=~\"$system\", label_component=\"singleuser-server\",}\n) by (label_hub_jupyter_org_service)\n",
     "legendFormat": "{{label_hub_jupyter_org_service}}"
    }
   ]
  },
  {
   "title": "Active partitions (try filtering by system in the dashboard submenu)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    kube_service_labels{label_app=\"$hub\", label_hub_jupyter_org_system=~\"$system\", label_component=\"singleuser-server\",}\n) by (label_hub_jupyter_org_partition, label_hub_jupyter_org_system)\n",
     "legendFormat": "{{label_hub_jupyter_org_system}}/{{label_hub_jupyter_org_partition}}"
    }
   ]
  },
  { "title": "Hub Diagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Server Start Times",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(jupyterhub_server_spawn_duration_seconds_bucket{service=\"$proxy\", namespace=~\"jupyter|userlabs\"}[5m])) by (le))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(jupyterhub_server_spawn_duration_seconds_bucket{service=\"$proxy\", namespace=~\"jupyter|userlabs\"}[5m])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Server Start Failures",
   "type": "graph",
   "description": "Attempts by users to start servers that failed.\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jupyterhub_server_spawn_duration_seconds_count{service=\"$proxy\", status!=\"success\"}[2m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Hub response latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum(\n    rate(\n      jupyterhub_request_duration_seconds_bucket{\n        service=\"$proxy\",\n        namespace=~\"jupyter|userlabs\",\n        # Ignore SpawnProgressAPIHandler, as it is a EventSource stream\n        # and keeps long lived connections open\n        handler!=\"jupyterhub.apihandlers.users.SpawnProgressAPIHandler\"\n      }[5m]\n    )\n  ) by (le))\n",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum(\n    rate(\n      jupyterhub_request_duration_seconds_bucket{\n        service=\"$proxy\",\n        namespace=~\"jupyter|userlabs\",\n        # Ignore SpawnProgressAPIHandler, as it is a EventSource stream\n        # and keeps long lived connections open\n        handler!=\"jupyterhub.apihandlers.users.SpawnProgressAPIHandler\"\n      }[5m]\n    )\n  ) by (le))\n",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(\n  0.25,\n  sum(\n    rate(\n      jupyterhub_request_duration_seconds_bucket{\n        service=\"$proxy\",\n        namespace=~\"jupyter|userlabs\",\n        # Ignore SpawnProgressAPIHandler, as it is a EventSource stream\n        # and keeps long lived connections open\n        handler!=\"jupyterhub.apihandlers.users.SpawnProgressAPIHandler\"\n      }[5m]\n    )\n  ) by (le))\n",
     "legendFormat": "25th percentile"
    }
   ]
  },
  {
   "title": "Hub response status codes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  increase(\n    jupyterhub_request_duration_seconds_bucket{\n      service=\"$proxy\",\n      namespace=~\"jupyter|userlabs\",\n    }[2m]\n  )\n) by (code)\n",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "All JupyterHub Components CPU",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  # exclude name=\"\" because the same container can be reported\n# with both no name and `name=k8s_...`,\n# in which case sum() reports double the actual metric\nirate(container_cpu_usage_seconds_total{name!=\"\"}[5m])\n\n  * on (namespace, pod) group_left(container, label_component) \n  group(\n    kube_pod_labels{label_app=~\"$hub|drf.+\", label_component!=\"singleuser-server\", namespace=~\"userlabs\"}\n  ) by (label_app, pod, uid, namespace)\n) by (pod)\n",
     "legendFormat": "{{ label_component }}"
    }
   ]
  },
  {
   "title": "All JupyterHub Components Memory (Working Set)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  # exclude name=\"\" because the same container can be reported\n# with both no name and `name=k8s_...`,\n# in which case sum() reports double the actual metric\ncontainer_memory_working_set_bytes{name!=\"\"}\n\n  * on (namespace, pod) group_left(container, label_component) \n  group(\n    kube_pod_labels{label_app=~\"$hub|drf.+\", label_component!=\"singleuser-server\", namespace=~\"userlabs\"}\n  ) by (label_app, pod, uid, namespace)\n) by (pod)\n",
     "legendFormat": "{{ label_component }}"
    }
   ]
  },
  {
   "title": "Hub DB Disk Space Availability %",
   "type": "graph",
   "description": "% of disk space left in the disk storing the JupyterHub sqlite database. If goes to 0, the hub will fail.\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "# Free bytes available on the hub db PVC\nsum(kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"data-postgresql-ha-postgresql-.+\", namespace=\"database\"}) by (namespace) /\n# Total number of bytes available on the hub db PVC\nsum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"data-postgresql-ha-postgresql-.+\", namespace=\"database\"}) by (namespace)\n",
     "legendFormat": "{{ $hub }}"
    }
   ]
  },
  {
   "title": "Non Running Pods",
   "type": "graph",
   "description": "Pods in a non-running state in the hub's namespace.\n\nPods stuck in non-running states often indicate an error condition\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  kube_pod_status_phase{phase!=\"Running\", namespace=~\"jupyter|userlabs\"}\n) by (phase)\n",
     "legendFormat": "{{phase}}"
    }
   ]
  }
 ]
}