{
 "title": "Monitoring Information",
 "tags": [
  "monitoring",
  "kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Monitoring system diagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Monitoring CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\".*prometheus.+\", namespace=\"cattle-monitoring-system\"}[5m]))",
     "legendFormat": "prometheus"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"cattle-monitoring-system\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Monitoring Memory (Working Set)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\".*prometheus.*\", namespace=\"cattle-monitoring-system\"})",
     "legendFormat": "prometheus"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"cattle-monitoring-system\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Monitoring Free Disk space",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{namespace=\"cattle-monitoring-system\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Prometheus Network Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\".*prometheus.+\", namespace=\"cattle-monitoring-system\"}[5m]))",
     "legendFormat": "prometheus receive"
    },
    {
     "expr": "sum(rate(container_network_send_bytes_total{pod=~\".*prometheus.+\", namespace=\"cattle-monitoring-system\"}[5m]))",
     "legendFormat": "prometheus send"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"cattle-monitoring-system\"}[5m]))",
     "legendFormat": "total receive"
    },
    {
     "expr": "sum(rate(container_network_send_bytes_total{namespace=\"cattle-monitoring-system\"}[5m]))",
     "legendFormat": "total send"
    }
   ]
  }
 ]
}