{
 "title": "User Diagnostics Dashboard",
 "tags": [ "jupyterhub" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "hub",
    "query": "label_values(kube_service_labels{label_component=\"hub\", namespace=\"jupyter\"}, label_app)"
   },
   {
    "name": "instance",
    "query": "label_values(kube_node_info{node=~\".*usernode.*\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "User Resource Utilization stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Per-user per-server memory usage\n",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  # exclude name=\"\" because the same container can be reported\n  # with both no name and `name=k8s_...`,\n  # in which case sum() by (uid) reports double the actual metric\n  container_memory_working_set_bytes{name!=\"\", node=~\"$instance\"}\n  * on (namespace, pod) group_left(uid) #(container)\n  group(\n      kube_pod_labels{label_app=\"$hub\", label_component=\"singleuser-server\", namespace=~\"userlabs\"} #, pod=~\"$user_pod\"}\n  ) by (uid,  pod, namespace)\n# ) by (pod, namespace)\n) by (uid, node)\n",
     "legendFormat": "{{ uid }} ({{ node }})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Per-user per-server CPU usage\n",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  # exclude name=\"\" because the same container can be reported\n  # with both no name and `name=k8s_...`,\n  # in which case sum() by (uid) reports double the actual metric\n  irate(container_cpu_usage_seconds_total{name!=\"\", node=~\"$instance\"}[5m])\n  * on (namespace, pod) group_left(uid) #(container)\n  group(\n      kube_pod_labels{label_app=\"$hub\", label_component=\"singleuser-server\", namespace=~\"userlabs\"} #, pod=~\"$user_pod\"}\n  ) by (uid, pod, namespace)\n# ) by (pod, namespace)\n) by (uid, node)\n",
     "legendFormat": "{{ uid }} ({{ node }})"
    }
   ]
  },
  {
   "title": "User CPU usage distribution",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(\n  # exclude name=\"\" because the same container can be reported\n  # with both no name and `name=k8s_...`,\n  # in which case sum() by (uid) reports double the actual metric\n  irate(container_cpu_usage_seconds_total{name!=\"\"}[5m])\n  * on (namespace, pod) group_left(container) \n  group(\n    kube_pod_labels{label_app=~\"$hub\", label_component=\"singleuser-server\", namespace=~\"userlabs\"}\n  ) by (label_app, pod, uid, namespace)\n) by (uid) #(pod)\n"
    }
   ]
  },
  {
   "title": "User memory usage distribution",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(\n  # exclude name=\"\" because the same container can be reported\n  # with both no name and `name=k8s_...`,\n  # in which case sum() by (uid) reports double the actual metric\n  container_memory_working_set_bytes{name!=\"\"}\n  * on (namespace, pod) group_left(container) \n  group(\n    kube_pod_labels{label_app=~\"$hub\", label_component=\"singleuser-server\", namespace=~\"userlabs\"}\n  ) by (label_app, pod, uid, namespace)\n) by (uid) #(pod)\n"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "graph",
   "description": "Per-user per-server memory Requests\n",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"userlabs\", node=~\"$instance\"}\n# ) by (pod, namespace)\n) by (uid, node)\n",
     "legendFormat": "{{ uid }} ({{ node }})"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "graph",
   "description": "Per-user per-server CPU Requests\n",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"userlabs\", node=~\"$instance\"}\n# ) by (pod, namespace)\n) by (uid, node)\n",
     "legendFormat": "{{ uid }} ({{ node }})"
    }
   ]
  },
  {
   "title": "Users per node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    # kube_pod_info.node identifies the pod node,\n    # while kube_pod_labels.node is the metrics exporter's node\n    kube_pod_info{node!=\"\"}\n    * on (namespace, pod) group_left() \n  group(\n    kube_pod_labels{label_app=~\".+\", label_component=\"singleuser-server\", namespace=~\"userlabs\"}\n  ) by (label_app, pod, uid, namespace)\n) by (node)\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  { "title": "Anomalous user pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Very old user pods",
   "type": "table-old",
   "description": "User pods that have been running for a long time (>8h).\n\nThis often indicates problems with the idle culler\n",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "(\n  time() - (kube_pod_created * on (namespace, pod) group_right() \n  group(\n    kube_pod_labels{label_app=~\"$hub\", label_component=\"singleuser-server\", namespace=~\"userlabs\"}\n  ) by (label_app, pod, uid, namespace))\n)  > (8 * 60 * 60) # 8 hours is our threshold\n",
     "legendFormat": "{{label_app}}/{{uid}}"
    }
   ]
  },
  {
   "title": "User Pods with high CPU usage (>0.5)",
   "type": "table-old",
   "description": "User pods using a lot of CPU\n\nThis could indicate a runaway process consuming resources\nunnecessarily.\n",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "max( # Ideally we just want 'current' value, so max will do\n  irate(container_cpu_usage_seconds_total[5m])\n  * on (namespace, pod) group_left(label_app, uid) \n  group(\n    kube_pod_labels{label_app=~\"$hub\", label_component=\"singleuser-server\", namespace=~\"userlabs\"}\n  ) by (label_app, pod, uid, namespace)\n# ) by (namespace, pod) > 0.5\n) by (label_app, uid) > 0.5\n",
     "legendFormat": "{{label_app}}/{{uid}}"
    }
   ]
  },
  {
   "title": "User pods with high memory usage (>80% of limit)",
   "type": "table-old",
   "description": "User pods getting close to their memory limit\n\nOnce they hit their memory limit, user kernels will start dying.\n",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "max( # Ideally we just want 'current', but max will do. This metric is a gauge, so sum is inappropriate\n  container_memory_working_set_bytes\n  * on (namespace, pod) group_left(label_app, uid) \n  group(\n    kube_pod_labels{label_app=~\"$hub\", label_component=\"singleuser-server\", namespace=~\"userlabs\"}\n  ) by (label_app, pod, uid, namespace)\n) by (label_app, uid) #(namespace, pod)\n/\nsum(\n  kube_pod_container_resource_limits{resource=\"memory\"}\n  * on (namespace, pod) group_left(label_app, uid) \n  group(\n    kube_pod_labels{label_app=~\"$hub\", label_component=\"singleuser-server\", namespace=~\"userlabs\"}\n  ) by (label_app, pod, uid, namespace)\n) by (label_app, uid) #(namespace, pod)\n> 0.8\n",
     "legendFormat": "{{label_app}}/{{uid}}"
    }
   ]
  }
 ]
}