hub:
  extraContainers:
    - name: maintenance-check
      image: python:3.9-alpine3.16
      imagePullPolicy: Always
      command: ["bin/sh"]
      args:
        - -c
        - >-
            pip install jsonformatter python-dateutil requests &&
            mkdir -p $OUTPUT_DIR &&
            python3 -u /tmp/maintenance-check.py
      env:
        - name: CUSTOM_CONFIG_PATH
          value: "/mnt/shared-data/git_config/jupyterhub_custom_config.json"
        - name: OUTPUT_DIR
          value: "/mnt/shared-data/maintenance-check"
        - name: LOGGER_NAME
          value: "MaintenanceCheck"
      volumeMounts:
        - name: shared-data
          mountPath: /tmp/shared-data
        - name: maintenance-check
          mountPath: /tmp/maintenance-check.py
          subPath: maintenance-check.py

