defaultNamespace: jupyterjsc
helm:
  releaseName: jupyterhub-juniq
  repo: https://jupyterhub.github.io/helm-chart/
  chart: jupyterhub
  values:
    hub:
      livenessProbe:
        enabled: False
      readinessProbe:
        enabled: False
      command: ["/bin/bash"]
      args:
        - -c
        - >-
          /bin/bash /src/entrypoint.sh -f /usr/local/etc/jupyterhub/jupyterhub_config.py
      containerSecurityContext:
        runAsUser: 0
        runAsGroup: 0
        allowPrivilegeEscalation: true
  valuesFiles:
    - values/hub/config.yaml
    - values/hub/extraConfig.yaml
    - values/hub/extraContainers.yaml
    - values/hub/extraEnv.yaml
    - values/hub/extraVolumeMounts.yaml
    - values/hub/image.yaml
    - values/hub/initContainers.yaml
    - values/hub/others.yaml
    - values/common.yaml
    - values/proxy.yaml
targetCustomizations:
  - name: staging
    clusterSelector:
      matchLabels:
        stage: staging
    helm:
      values:
        hub:
          extraVolumes:
            - name: persistent
              nfs:
                path: /mnt/storage/jupyterhub_juniq
                server: 10.0.94.174
            - name: shared-data
              emptyDir: {}
            - name: mount-watch
              configMap:
                defaultMode: 400
                name: juniq-jupyterhub-mw
            - name: cleanup-sql
              configMap:
                defaultMode: 400
                name: jupyterhub-cleanup-sql
            - name: maintenance-check
              configMap:
                defaultMode: 400
                name: jupyterhub-maintenance-check
            - name: reservation-check
              configMap:
                defaultMode: 400
                name: jupyterhub-reservation-check
            - name: internal-ssl
              secret:
                secretName: internal-ssl-juniq
            - name: reservation-keypair
              secret:
                secretName: reservation-keypair
            - name: drf-tunnel-certs
              secret:
                secretName: drf-tunnel-certs
                items:
                  - key: tls.ca
                    path: ca.pem
            - name: drf-unicoremgr-certs
              secret:
                secretName: drf-unicoremgr-certs
                items:
                  - key: tls.ca
                    path: ca.pem
            - name: drf-k8smgr-certs
              secret:
                secretName: drf-k8smgr-certs
                items:
                  - key: tls.ca
                    path: ca.pem
            - name: unity-jsc-certs
              secret:
                secretName: unity-jsc-certs
            - name: hub-nginx-config
              configMap:
                defaultMode: 400
                name: hub-nginx-config
          labels:
            stage: staging
            jhub_version: "2.1.1"
            hostname: "juniq-staging.fz-juelich.de"
          extraConfig:
            stagingConfig: |-
              jupyterhub_hostname = os.environ.get("JUPYTERHUB_HOSTNAME", "default")
              c.JupyterHub.trusted_alt_names = [
                "DNS:hub",
                "DNS:proxy-public",
                f"DNS:{jupyterhub_hostname}",
                "DNS:drf-k8smgr-jupyterhub-forward.jupyterjsc.svc",
                "DNS:drf-k8smgr-jupyterhub-forward.userlabs.svc",
                "DNS:jrlogin01i",
                "DNS:jrlogin02i",
                "DNS:jrlogin03i",
                "DNS:jrlogin04i",
                "DNS:jrlogin05i",
                "DNS:jrlogin06i",
                "DNS:jrlogin07i",
                "DNS:jrlogin08i",
                "DNS:jrlogin09i",
                "DNS:jrlogin10i",
                "DNS:jrlogin11i",
                "DNS:jrlogin12i",
                "DNS:jrlogin13i",
                "DNS:jrlogin14i",
                "DNS:jwlogin00i",
                "DNS:jwlogin01i",
                "DNS:jwlogin02i",
                "DNS:jwlogin03i",
                "DNS:jwlogin04i",
                "DNS:jwlogin05i",
                "DNS:jwlogin06i",
                "DNS:jwlogin07i",
                "DNS:jwlogin08i",
                "DNS:jwlogin09i",
                "DNS:jwlogin10i",
                "DNS:jwlogin11i",
                "DNS:jwvis00i",
                "DNS:jwvis01i",
                "DNS:jwvis02i",
                "DNS:jwvis03i",
                "DNS:jwlogin21i",
                "DNS:jwlogin22i",
                "DNS:jwlogin23i",
                "DNS:jwlogin24i",
                "DNS:hdfmll01i",
                "DNS:hdfmll02i",
                "DNS:deepv",
                "DNS:jsfl01i",
                "DNS:jsfl02i",
                "DNS:jsfl03i",
                "DNS:jsfl04i",
              ]
              c.CustomGenericOAuthenticator.oauth_callback_url = (
                  f"https://{jupyterhub_hostname}/hub/oauth_callback"
              )
