defaultnamespace: jupyter
dependsOn:
  - name: jupyter-hub-helper-once
  - name: jupyter-jhub-juniq-helper
helm:
  releaseName: jupyterhub-juniq
  repo: https://jupyterhub.github.io/helm-chart/
  chart: jupyterhub
  version: 2.0.0
  values:
    hub:
      livenessProbe:
        enabled: false
      readinessProbe:
        enabled: false
      command: ["/bin/bash"]
      args:
        - -c
        - >-
          /bin/bash /src/entrypoint.sh -f /usr/local/etc/jupyterhub/jupyterhub_config.py
      containerSecurityContext:
        runAsUser: 0
        runAsGroup: 0
        allowPrivilegeEscalation: true
  valuesFiles:
    - ../../hub-base/helm/common.yaml
    - ../../hub-base/helm/hub/config.yaml
    - ../../hub-base/helm/hub/extraConfig.yaml
    - ../../hub-base/helm/hub/extraContainers.yaml
    - ../../hub-base/helm/hub/extraEnv.yaml
    - ../../hub-base/helm/hub/extraVolumeMounts.yaml
    - ../../hub-base/helm/hub/extraVolumes.yaml
    - ../../hub-base/helm/hub/image.yaml
    - ../../hub-base/helm/hub/initContainers.yaml
    - ../../hub-base/helm/hub/services.yaml
    - ../../hub-base/helm/hub/others.yaml
    - ../../hub-base/helm/proxy.yaml
    # We overwrite some values in hub specific files,
    # so the import order needs to be hub-base,
    # then the hub specific config 
    - values/common.yaml
    - values/proxy.yaml
targetCustomizations:
  - name: staging
    clusterSelector:
      matchLabels:
        stage: staging
    kustomize:
      dir: overlays/staging
    helm:
      values:
        hub:
          image:
            tag: "4.0.0.8"
          labels:
            stage: staging
            jhub_version: "4.0.0"
            hostname: "juniq-staging.fz-juelich.de"
            drf_username: "jupyterhubjuniq"
            logger_name: "JupyterHubJUNIQStaging"
          resources:
            requests:
              cpu: 20m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 1024Mi
        proxy:
          chp:
            resources:
              requests:
                cpu: 20m
                memory: 128Mi
        ingress:
          # Set JupyterHub in maintenance:
          #   Set enabled here to false, update ingress in maintenance/fleet.yaml
          enabled: true
          hosts:
          - juniq-staging.fz-juelich.de
          tls:
          - hosts:
            - juniq-staging.fz-juelich.de
            secretName: juniq-tls
  - name: production
    clusterSelector:
      matchLabels:
        stage: production
    kustomize:
      dir: overlays/production
    helm:
      values:
        hub:
          image:
            tag: "4.0.0.8"
          labels:
            stage: production
            jhub_version: "4.0.0"
            hostname: "juniq.fz-juelich.de"
            drf_username: "jupyterhubjuniq"
            logger_name: "JupyterHubJUNIQProduction"
          resources:
            requests:
              cpu: 20m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 1024Mi
        proxy:
          chp:
            resources:
              requests:
                cpu: 20m
                memory: 128Mi
        ingress:
          # Set JupyterHub in maintenance:
          #   Set enabled: false, update ingress in maintenance/fleet.yaml
          enabled: false
          hosts:
          - juniq.fz-juelich.de
          tls:
          - hosts:
            - juniq.fz-juelich.de
            secretName: juniq-tls
