apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxyBackup.name }}-1
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    release: {{ .Values.proxyBackup.release }}
    component: proxy
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxyBackup.name }}-2
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    release: {{ .Values.proxyBackup.release }}
    component: proxy
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxyBackup.name }}-3
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    release: {{ .Values.proxyBackup.release }}
    component: proxy
  type: ClusterIP