hub:
  config:
    JupyterHub:
      allow_named_servers: true
      cleanup_proxy: false
      default_url: /hub/home
      # hub_ip: 0.0.0.0
      # hub_port: 8000
       # See https://github.com/jupyterhub/jupyterhub/issues/1222#issuecomment-415264385
      tornado_settings:
        slow_spawn_timeout: 0

      init_spawners_timeout: 0
      concurrent_spawn_limit: 40
      last_activity_interval: 60

      load_roles:
        - name: read-metrics
          description: Access to metrics information
          scopes: 
            - read:metrics
          services:
            - metrics-prometheus-monitor
      
      jinja_environment_options:
        extensions:
          - jinja2.ext.do
          - jinja2.ext.loopcontrols

      internal_ssl: true
      internal_certs_location: /mnt/shared-data/tmp-internal-ssl
      external_ssl_authorities:
        services-ca:
          key: /mnt/persistent/internal-ssl/services-ca/services-ca.key
          cert: /mnt/persistent/internal-ssl/services-ca/services-ca.crt
          ca: /mnt/persistent/internal-ssl/services-ca_trust.crt
        proxy-client-ca:
          key: /mnt/persistent/internal-ssl/proxy-client-ca/proxy-client-ca.key
          cert: /mnt/persistent/internal-ssl/proxy-client-ca/proxy-client-ca.crt
          ca: /mnt/persistent/internal-ssl/proxy-client-ca_trust.crt
        proxy-api-ca:
          key: /mnt/persistent/internal-ssl/proxy-api-ca/proxy-api-ca.key
          cert: /mnt/persistent/internal-ssl/proxy-api-ca/proxy-api-ca.crt
          ca: /mnt/persistent/internal-ssl/proxy-api-ca_trust.crt
        notebooks-ca:
          key: /mnt/persistent/internal-ssl/notebooks-ca/notebooks-ca.key
          cert: /mnt/persistent/internal-ssl/notebooks-ca/notebooks-ca.crt
          ca: /mnt/persistent/internal-ssl/notebooks-ca_trust.crt
        hub-ca:
          key: /mnt/persistent/internal-ssl/hub-ca/hub-ca.key
          cert: /mnt/persistent/internal-ssl/hub-ca/hub-ca.crt
          ca: /mnt/persistent/internal-ssl/hub-ca_trust.crt
      ssl_cert: /mnt/persistent/internal-ssl/hub-internal/hub-internal.crt
      ssl_key: /mnt/persistent/internal-ssl/hub-internal/hub-internal.key

      trusted_alt_names:
        - DNS:hub
        - DNS:proxy-public
        - DNS:{{ include "jupyterhub.hub.fullname" . | quote }}
        - DNS:drf-k8smgr-jupyterhub-forward.jupyterjsc.svc
        - DNS:drf-k8smgr-jupyterhub-forward.userlabs.svc
        - DNS:jrlogin01i
        - DNS:jrlogin02i
        - DNS:jrlogin03i
        - DNS:jrlogin04i
        - DNS:jrlogin05i
        - DNS:jrlogin06i
        - DNS:jrlogin07i
        - DNS:jrlogin08i
        - DNS:jrlogin09i
        - DNS:jrlogin10i
        - DNS:jrlogin11i
        - DNS:jrlogin12i
        - DNS:jrlogin13i
        - DNS:jrlogin14i
        - DNS:jwlogin00i
        - DNS:jwlogin01i
        - DNS:jwlogin02i
        - DNS:jwlogin03i
        - DNS:jwlogin04i
        - DNS:jwlogin05i
        - DNS:jwlogin06i
        - DNS:jwlogin07i
        - DNS:jwlogin08i
        - DNS:jwlogin09i
        - DNS:jwlogin10i
        - DNS:jwlogin11i
        - DNS:jwvis00i
        - DNS:jwvis01i
        - DNS:jwvis02i
        - DNS:jwvis03i
        - DNS:jwlogin21i
        - DNS:jwlogin22i
        - DNS:jwlogin23i
        - DNS:jwlogin24i
        - DNS:hdfmll01i
        - DNS:hdfmll02i
        - DNS:deepv
        - DNS:jsfl01i
        - DNS:jsfl02i
        - DNS:jsfl03i
        - DNS:jsfl04i