hub:
  annotations:
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
    kubectl.kubernetes.io/default-container: "hub"
  consecutiveFailureLimit: 0
  db:
    type: "postgres"
  nodeSelector:
    worker: "true"
  networkPolicy:
    allowedIngressPorts:
      - 8070
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
