---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: coec
spec:
  encryptedData:
    client_id: AgBHAnPKliM71PkfFmtez6+OeppTh6eotxuAlUa8DBR2/TGIyR5gju/mZKXWYbFlRvKfBbONV95eSHAPsorbwxG2GBrrVyuBSNygDxxtgyRfp3awa7AeSfn3Pk+7cYoHqzgKUCbBKqVYRofDGO8PQ3rlRhuFv60JOvymnwltxU+yzobO9rMZrQ28biozyPRiplRnPq0deQb7Atf+l/EPu0UiZCKVFmktzf27P14ZL9dxAh6gPcT0RUa6P1oEgidFEj7eetOKEfZg1WBFjMiUr4FAmaqEfqQc4IUccOqBWBK+yDwMT0isEVGuQfL4RkSfVFan/9+p5Hpdtewq2NQ98EDoBkS4jJzhcp7j5h+rPXjWjfoEnSyyE3cHGVPJ5qvT5E9p7bn3flbsh1y3MeWZ1zow9voY0J3NZFgjjyrVKU0hmZpdpdQUVhI+2S2BTVwQlRaF89r+Pi41xFidByahHUHLWBtx9+Ppf+HY7cjD+/9l4d1i5LfomYyD1TDvZSFRgzTTdLx+YZx2kFGsozsUQoRCM+YwKGSScnO4C4gmiL9AvlcJmJSphzfho1w5M1bVm/vbvSMLEMFIU5NIhtrO5IY3rDg3MRjXit2wpte4zGi55I2osGbVBMpDMFLTQutZRM+xQX0pp5d57h7V218NQBNLuEFJu7HZ+n7ygJvPLLsD3/XQaIoXluBhezIHu60YcuAX6PFEX/DwkZtVgWE=
    client_secret: AgC0dNMFTYUIEquRfpYEorSgpiVAhb/7RAZ+okTKuA0XtqSz1qImOYBIoDLk5sOGBSXUcySUZLbSI2R6m6wZ0ggKUyKSHkisjCvg3d/kBWJ+QRCyQbEuvxip4vwzEjv+g28HBJ/U2pZB1EjnjWbnFUUIaLrKd3aISPdLW5Y6X1jLkaIi2kAYb6QECVpxX1C9p45K/g9hjtXjD/72CO01saWL2aFmi55L+KKRoN/wo7ktfErV1Lxe8dbJNDjOKYbSHjFL8czz5CYETTARYRa1/p7kFnbI39+HcxizZv+OYQDFPVjhnlQaGkOwFouQMmpP9hD9LehMQG8rzJjpLwv3hclH72Oo7VzR9pp1LexQk+A/A/ZMDJndNDemrQTBee9zF6nGoUvzL6OQeFl2QAZjrzu2TdQsP7mQgyXXoGcoUVtb4QsMOLZIpUSPpxmsQvqiD5yVnncMbueYuJZ+fWVPLnz+L7l17ko2MaHkO8WzTrvC4uz5ZQyaXa69e9m+UjajOFu5sgxuMdoE+yJblpfQlc4F57mulMovIvbUkfClC0CsJu23jCP0lbdHdSnMm/1+mLOXBvO5iUvhSBG5r0W2BODP62naUbOn9tRZzL3Po9aCTvM4cDx/0WmTiL5xZ2m/IHQhZJerWP/KYZQo9msgIAb9+T1aW090Icie0yX3Pu0ueqRHN9aYVER5Gkc64b/4LqDhGi/68Ovd9cbIyB18zNIMJPZC+vc8akT+iVsm55no5Q==
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: coec
    type: Opaque
