- op: replace
  path: "/spec/template/spec/volumes/2/nfs"
  value:
    path: /mnt/storage/jupyterhub_juniq
    server: 10.0.20.30
- op: replace
  path: "/spec/template/spec/volumes/10/secret/secretName"
  value: internal-ssl-juniq
