- op: add
  path: "/spec/template/spec/initContainers/0/env/-"
  value:
    name: TEMPLATE_GIT_REPO
    valueFrom:
      secretKeyRef:
        name: coeraise-share-repository
        key: REPOSITORY
- op: add
  path: "/spec/template/spec/initContainers/0/env/-"
  value:
    name: TEMPLATE_GIT_USERNAME
    valueFrom:
      secretKeyRef:
        name: coeraise-share-repository
        key: USERNAME
- op: add
  path: "/spec/template/spec/initContainers/0/env/-"
  value:
    name: TEMPLATE_GIT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: coeraise-share-repository
        key: PASSWORD