---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: infraproxy-credentials
  namespace: nfdigeneral
spec:
  encryptedData:
    client_id: AgCnK3/usseQYm1dKq9Di969sGP+RInWOwGYWD6aYm1HmsE9BOSy6tGr3+B5iY/TNn10RM7iXuCXTsFK/2isEu9Jaf423vSjEbZ74F5wn0mZBr92Krh4lQ11eTB2jMPi4jiwAYASQx5Cet/ATpS5guQwAGqrvKLpNqMCB0IAKPFqN9Efw6n9EcRgmaoIlqYADy82RSQHu5NmokyowDlVxJALsYXjCqDcAJVrvwQJgX1MlbAIdAv07q7OUGXDX32HNlbNVh3drToFI1oYnK72WaIPbnUkWALGEZtHY4/k2q/er2uD7r63toYpnjZcyNt0TR5aAKewz9TPnLON9U0yw0ygv46MKI80+bOykdmqsNPMGNgoQ+HeW9cR3YOAP4s6BejQ5t3IWRPZCvwsN0k69OWzH8N/r6CyxWpusqRME9BSTz8tUWHMu+BHR0wao/dDg0m77S/C9b5E0JC0E4X523XNyXDQjxrv5mQVNfgkKO6UaZAshCpEBdEZV8d38wIGN6a885GhUa5jXC4m9trvq/q8xPXC2qzwBnVnHzYFgxM4x7NUfmy9WGYaxTo/s9BFMzLNjx8w8NV3rNXlqaX8QM9z91UEcSNgfvofY/ziCLqnVXVTN6Y2rGkY0uyc148ils/lTC3YpOH+iRDDGXfZGW/PpYp8wSX5HsqsygAlB9Qukdt5Y/5Gm/EkxR3rweAUbbt80OdAc8HxJuoMJPk+bXvt0YHlJORoMyKuMbw=
    client_secret: AgCMGZiGKLncccshaWyVmP8+n5ekfbFVMzXGbT2aaQh40aGvia5NugX3S+Dgqwoe8u94gRnndN3XaiL49XmHgpDgg22jhGN/byg06Wwh9MCptOUSCeRBA0a7IV60AkpauLKO1V/9fb2nFDt07La6G10LOkMtrraWWW/A4NB171JCHXJIdJIMjzPVYwv88aal1tHzwcYhxTZV6fiZlSV1jONbapaVB2bcSGXX8xEvW9yAlfAq17gBbfa5d45QEF7eQTiB/Mt+bMwP5t/aDsDRan+6CHUHJP2nS55q1K9IzrTTGD+xgppxkKh/qM5mLtrX2mDstmwYKht9ttmTHuBqq7o9t9smZVIAuQt5YPGXrNkm8RxYG6xlONLU7Pp6zQnU3iXs3aE42x79J3JbPlVW4Fc89PljOPNcgzeXPiO9Oj7V6wHQKhQJr5JXjZG1pfEZ/ctJ0nBmpbVj/hW8iS+/JREmCcvIfAmzZ7gDEo1RE6ZqJ8avF94YWE7ZZcTWvJF1kFSRmEHKqv8ttZXfShxu7g8KTM7wWVyBkTISrt+u/4Q8RGN9IN/ITUuo6TWEzVEIahAdfrbJWUTzMlqd81rrYJqiOSj6CNJUNTgwO+uaqluuH12pjvbbfsF+iAg0mEQbkeHqc6AjOP/QdJ5LY9wRaIrIH+U7PTepzROGoUSuwxgOzjiICTiRn5EK5AP6Vq8RhFWqC6X6Rwz2fRfKhLAnUBhxpWRDOUm68V00q2TGkbZBgwva7snes/PF8bbD4U+ogj7RKa1cWS3hIEP4o8vmrePW
  template:
    metadata:
      creationTimestamp: null
      name: infraproxy-credentials
      namespace: nfdigeneral
    type: secret
