---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unity-secrets
  namespace: portalgauss
spec:
  encryptedData:
    client_id: AgAmwZAu9gSZ3Y1PEL/nbRmTvsq6jtae1eXPZAAe9W1dQ/LBdNaVntcANUYhjmfanZpCwkV8XoxB+Tz20WFysDn4r2KmhFPDMc8qeCSPJj/tUzihQsJM09IL491njQfiFdeL7CakjwwGjvYu9k3YB8eFddOCMBr70kX+Uvk3CZlX4iRh4nfiCUvEwv9nj4y9nx+mkxiXeMtuaf9GVXw1NhzKlFqcIlVjUlyL937Dv8KdFCX63+l9SP9rZjt24m5QbvMBY7wR9C3lPqYa7ajpv9aybGQeZPF592gL+LgFLjZSxkkM/rJgcKIVE9viWntORsx22bAA2qt+yOEg9TaD0A75t6P4N6fTXt88BIa2K3ysq/QhHmhesguJbkJV5yUlKwUIaX/xo450/a/gfwaUlgAwiUw3RIB0L4Niz8zTisW4FHBiY7kq5Df1SPWHz71uUpGHCA7b+rY/fEVJXQa/sp8bdiSaWajoIQsHA1sbNiudcWm13wNDV2cctO7oTHPv5e6LHhgBASBD0Y1/Kctvbj4fjCgcUphvQhyFXn23OyvsEeXswpjJ0Tff6ormf82TzNNToHRqkh+NYF2W5pufJZ4S7eIm9e4lRqoNHBK3uDXPbBbw2oStSAWcfLQIzTfAM/8l8DevbP3TQI00689Drj9m0TyS0b0Mce/hDgX2im6YYdpm0vjc+QtYlxURXzSgl5tMJK0vzd80drPSPwpoLSOwukoc
    client_secret: AgCvyHDMwWHxvJvPTACgarOK2g9tJo5i9Gpm45hXkXMJkWtXmMktpq8kIBUCiPUAtVC2sRS89pIn+kJ6hzaaQHr/l7gCcTx5046xb77PDcdiOtwv8dwrMyzemwgUhP4fNQH5bmmRFMrFGERG+QarUB6wfdG5hbVcriU2oNBGa3/j3YjgksZL+nXhnTtMkuV/Of2Tcb9n0bt/tqZZ7l3L2DzvsKmdaWDYZd6/R0NfZeFYCaazjHvoRRBiDfokbKi8HOeSrK/2UNgAu8OpjJuP9DgBfjKuKqNHx3xODUvOmdwYRgphfh3indxgiBtkb4k9H8zlxxn6WKAh7SpEVWnY1FH4EXXgq3qnixyzNf1xjKeC+WunukS+GT2SrJcTGNcMWZF+lFFvYw0+kFU1CgGQEuLLQeWLmPbkWLKAgFSwbEnfVIf6ni8QogWGvdqQk/9/E+xNqhMoEN3QT9Qd7gWKrrbBObm5nMiqdiHze78VraoFrSY3aInJ5WvJbqmCKT9PmOnV+lf0UiLoRkxexnEIB8cIS+L6Po2xNI0s516S7EUbU2rv0c0pWl5e3hNnnSYHFvXIocImen8RDEEfUGanR6LCtNC8yycTbjNf5sLp6KqY2QUoULEG+7RJYm0cbcqGg8uNXp6D/mIxTgBwhrq0yNNkzxIo9VT3MpPojYaSd2mlA3Fgrcd4F068t2hFSb3zmHrMdFag8ijKczjOlL9RNkwzK+P4nSBdE/b68MpfQNZOTg==
  template:
    metadata:
      creationTimestamp: null
      name: unity-secrets
      namespace: portalgauss
    type: Opaque
